### ISSUE TITLE
README links to internal Zalando TechWiki

### ISSUE THREAD

**Issue by hjacobs** [zalando/restful-api-guidelines#1]
The README.md has two links pointing into Zalando internal infrastructure.

**Comment by fmueller** [comment]
I know, I searched for it before and found such links in other Zalando open source projects. These two are pointing to wiki and internal GitHub Enterprise. Is this something that has to be fixed? Just to clarify. Thanks in advance.

**Comment by hjacobs** [comment]
@femueller I don't see it as a security issue, but more as "not useful/helpful" for interested readers outside Zalando.

**Comment by hjacobs** [comment]
@fmueller what other Open Source projects did you find with such links?

**Comment by fmueller** [comment]
@hjacobs In https://github.com/zalando/ghe-backup I saw links to Zalando Pier One Installation. And you are right, for our public audience I'll improve on introduction text. Im thinking about a Zalando specific paragraph where we link to internal documents for further reading.

**Comment by hjacobs** [comment]
@fmueller sounds good, thanks.

**Comment by tfrauenstein** [comment]
I think, we should provide internal links -- they are helpful for main user group of Zalandos.
However, we should also markup these links as internal links as to improve external usage convenience.
Any ideas for concrete markup?

**Comment by ePaul** [comment]
@tfrauenstein: @fmueller edited the file in #6 to move the internal references (and some text around it) into a separate section titled "Zalando specific information". Is this enough, or do we need a special marker for "non-public link"?

**Comment by tfrauenstein** [comment]
I think a separate section is fine for the situation above -- but IMO not a general solution pattern.
For instance, there are still some links to our "Best Practises" (e.g. http://zalando.github.io/restful-api-guidelines/http/Http.html). Introducing new sections here is not adequate.

I simply propose convention to add "[internal link]" to the link text, e.g. "Best Practises [internal link]".

**Comment by fmueller** [comment]
Right, there are still other internal link and maybe in future we'll add more.

+1 for adding [internal link] to each internal link. Other votes on this?

**Comment by fmueller** [comment]
Closed. Internal link naming convention is merged and further discussion for separating intro and readme will take place in #9
