### ISSUE TITLE
Single page version would be nice for quickly browsing/searching

### ISSUE THREAD

**Issue by priesus** [zalando/restful-api-guidelines#10]
I usually love to use the browser search to quickly find what I'm looking for (e.g. when I have a keyword in mind and I know there's something in the guidelines about this).

The GitBook search doesn't seem so convenient. You still have to click through pages and don't have highlighted search results.

Is there a possibility to provide a single-page version of the book?

**Comment by fmueller** [comment]
It should be possible with 'gitbook build -f page' but for some reason in our setup this is not working out of the box. @mostlymagic Could this be cause by one of our plugins?

Or we need to upgrade our Gitbook version. I'll investigate more on this.

In the meantime you can build a PDF, by (on Mac with Homebrew):

brew install cask
brew cask install calibre
make init
npm install ebook-convert
node_modules/.bin/gitbook pdf

**Comment by tfrauenstein** [comment]
@fmueller as discussed, Iit would be great, if there is an easy way to also generate the pdf with gitbook pages, to ship it with the pages and let the intro pages link to the pdf. Is this feasible w/o bigger efforts?

**Comment by fmueller** [comment]
PDF generation is now part of the publishing travis build and you'll find the newest version under this link: http://zalando.github.io/restful-api-guidelines/guidelines.pdf

I'll still investigate a single page generation in HTML.

**Comment by fmueller** [comment]
I close this issue. Unfortunately there is not easy way to generate a singe page version via gitbook. For this, one has to use the pdf version.
