### ISSUE TITLE
Upgrade to Gitbook 3

### ISSUE THREAD

**Issue by fmueller** [zalando/restful-api-guidelines#106]
I think we should upgrade our used Gitbook version to version 3. It has breaking changes for us, we have to adapt some of our plugins.

By upgrading we can enjoy new features of Gitbook in future which can improve experience for readers of our guidelines.

**Comment by fmueller** [comment]
I close this issue as it is too much effort for now.

What I tried:
- upgrade https://github.com/zalando-incubator/gitbook-structured-toc to Gitbook 3 - works
- failed to upgrade https://github.com/zalando-incubator/gitbook-restructure-navigation to Gitbook 3
- failed to upgrade some other plugins as well

**Comment by whiskeysierra** [comment]
> I close this issue as it is too much effort for now.

:cry: It won't get less difficult over time, will it?

**Comment by fmueller** [comment]
@whiskeysierra It does not add any value to have Gitbook 3. I really would like to have the newest major version, but it seems we do not have a problem with latest 2.x.x version.

**Comment by ePaul** [comment]
Discussion in the guild meeting: Stay at 2.x.x for now, rediscuss it when we get a requirement which needs Gitbook 3.
