### ISSUE TITLE
Xs for Collection+JSON instead of checkmarks?

### ISSUE THREAD

**Issue by mamund** [zalando/restful-api-guidelines#112]
In the table accompanying the section [**Must: Use a well-defined subset of HAL**][1] you have a line for Collection+JSON with a row of Xs instead of checkmarks. 

What does this table indicate and why is Cj getting the Xs? In particular what does the checkmark for the "docs" column represent? Is there something that you find missing on the "doc" front that might change this status?

[1]: http://zalando.github.io/restful-api-guidelines/hyper-media/Hypermedia.html#must-use-a-welldefined-subset-of-hal

**Comment by hjacobs** [comment]
@mamund thanks for filing the question, I pinged our Zalando API guild (as I can't answer this myself) :smirk:

**Comment by whiskeysierra** [comment]
I can't remember why we decided for the X in the docs column, to be honest. In retrospect I think that's an error and we should change that. I would stick with the decisions for Simplicity and Compatibility. Adoption is hard to judge, I only find comments in blogs (see links in the guidelines) and not really much more. It just doesn't produce the same buzz as e.g. HAL.

**Comment by tfrauenstein** [comment]
👍

**Comment by tkrop** [comment]
@mamund Would a `-`  be easier to understand?

**Comment by mamund** [comment]
@tkrop 

it's not the symbol that i asked about, but the meaning behind it. "X" or "-" on "docs" indicated something lacking, missing, low-quality, etc. and I am asking what it would take to "fix" that kind of assessment.

note that i'm not asking about "Simplicity", "Compatibility", and "Adoption" here. I get that, I think.

**Comment by fmueller** [comment]
@mamund Thank you for asking about this. It seems we missed to add proper legend information. X means not sufficient for our need. For some implementations we just haven't found enough information and to not overcomplicated the comparison, we've decided to also add X in this case.

We should provide more explanation what the rating means and how it was generated. Tomorrow is our internal guild meeting where we discuss this.

In the meantime, if you have anything to add for Collection+JSON or have another opinion on the rating, please express your thoughts here.
