### ISSUE TITLE
Prefer objects for results/lists

### ISSUE THREAD

**Issue by dehora** [zalando/restful-api-guidelines#117]
With Open API, there's two basic ways to return a list of items

- arrays
- objects

Both are common use for APIs defined against these guidelines in Zalando.

I think it's worth recommending against array based responses and preferring object results. The main reason is that arrays design out extensibility, which is counter to the general principles. There's no way to extend an array with extra information or provide a home for common structures like pagination. This seems to lead to the definition of X-Headers to carry information (such as counts, but any kind of metadata really). Since Link headers have been dropped, APIs based on arrays have no real options for paging. Finally, there are odd bugs that can crop up when empty ends up meaning no more data in array responses, but also no data in the the current range, that are less likely to happen with explicit next/previous page declarations supportable by objects.

A knock-on consequence could be a need to firm up pagination models, and possibly defining an idiomatic structure for collections.

**Comment by fmueller** [comment]
We already mention this implicitly in our pagination chapter.

+1 for an explicit recommendation in our guidelines. It's also kinda mandatory when we think about our favoring of backward compatible changes in contrast to versioning: only with surrounding object one can add new fields.

**Comment by codekultur** [comment]
Created a PR for this: https://github.com/zalando/restful-api-guidelines/pull/126
