### ISSUE TITLE
Clarify use of Location and Content-Location for PUT/POST methods

### ISSUE THREAD

**Issue by dehora** [zalando/restful-api-guidelines#118]
HTTP does not make understanding the use Location and Content-Location easy. You have to bounce around RFCs, reason about combinations of response codes and methods, and generally tie a bunch of stuff together. We touch on this in a few places, but it's not clear the guidance is making things easy to understand as it could. For example, http://zalando.github.io/restful-api-guidelines/http/Http.html#success-codes focuses on 201 and says always set the Location header, but doesn't say why or for what reason (201 itself does not require a Location header, and a PUT request that would require a Location header would be odd, as PUT is sent to the target resource). As another example http://zalando.github.io/restful-api-guidelines/headers/CommonHeaders.html says the combination of Location and Content-Location is such that if they are equal this makes "a subsequent GET operation from the client side not necessary": on the other hand, [PUT is pretty clear in saying responses cannot be cached](https://tools.ietf.org/html/rfc7231#section-4.3.4), 

```
Responses to the PUT method are not cacheable.
```

But in the [definition of Content-Location elsewhere](https://tools.ietf.org/html/rfc7231#section-3.1.4.2) it says:

```
For a state-changing request like PUT (Section 4.3.4) or
   POST (Section 4.3.3), it implies that the server's response contains
   the new representation of that resource, thereby distinguishing it
   from representations that might only report about the action (e.g.,
   "It worked!").  This allows authoring applications to update their
   local copies without the need for a subsequent GET request." 
```

It's not clear how to resolve these statements without hairsplitting around client updating state versus clients updated caches.

This is less a criticism of the guidelines, and more that HTTP isn't organised in a way that makes explaining these things obvious to developers because it defines methods, headers and response codes independently with occasional cross-references. I suspect it requires discussing how the headers are to be used for each combination of PUT/POST/201/200. In turn that would suggest we should have a section dedicated to lifecycles (creating, updating and maybe deleting resources) that is optimised for API design, rather than organising the guidelines around HTTP elements.

**Comment by fmueller** [comment]
Good points. I'm also often confused about Content-Location and Location header. To be honest, I personally think that we overdo it in our guidelines with this specific header and its semantic. I mean I'm not aware of any service oder load balancer so far which is using the semantic of Content-Location header to cache responses of POST requests.

And for this reason I propose the following:
- Make usage of Content-Location a Could rule and say that it's only useful for POST with caching of response
- Make Location header for POST a Must rule
- exclude both headers for PUT

**Comment by ePaul** [comment]
@dehora I think the intended meaning of "Responses to the PUT method are not cacheable." is something like this (wording mine):

> When a cache receives the next PUT request, it MUST NOT simply reply with the cached response, but MUST forward the PUT to the origin server, and then forward that one's response back to the client.

(This is the same for other modifying methods like DELETE and POST.)

The Content-Location explanation says that you **can** cache the response to a PUT/POST for using it as a **GET** response to the indicated resource.

**Comment by ePaul** [comment]
Discussion in Guild meeting: it looks like Content-Location is seldom useful, thus we should avoid it at all.
→ reword the guideline to this goal.
