### ISSUE TITLE
Recommend against enums

### ISSUE THREAD

**Issue by dehora** [zalando/restful-api-guidelines#119]
We cover Open API enums in a few places, notably here: http://zalando.github.io/restful-api-guidelines/compatibility/Compatibility.html

> - Enum ranges cannot not be extended when used for output parameters — clients may not be prepared to handle it. However, enum ranges can be extended when used for input parameters.

> - Enum ranges can be reduced when used as input parameters, only if the server is ready to accept and handle old range values too. Enum values can be reduced when used as output parameters.

> - Use x-extensible-enum, if range is used for output parameters and likely to be extended with growing functionality. It defines an open list of explicit values and clients must be agnostic to new values (e.g. via casuistic with default behavior).

This is great and is accurate, but I see enums consistently in APIs based on the guidelines that are not closed sets. I think we need to recommend against using `enum` as top level guidance and not just describe the pitfalls in a general section. The `x-extensible-enum` is useful as a workaround, but the concept of an enum is closed by design, also it can't be used in JSON Schema which is necessary for events. Maybe we need a more direct way to describe an open-ended list of values.

**Comment by whiskeysierra** [comment]
I absolutely agree! :+1:

**Comment by ePaul** [comment]
In the API guild meeting we agreed to put a guideline into the JSON section, and refer to it from the Compatibility section.
