### ISSUE TITLE
Experience report with JSON Merge Patch and JSON Patch

### ISSUE THREAD

**Issue by whiskeysierra** [zalando/restful-api-guidelines#124]
Our guidelines have a section about [how to use the PATCH operation](http://zalando.github.io/restful-api-guidelines/http/Http.html#patch) and it basically has the following list of preferences:

1. PUT
2. JSON Merge Patch
3. JSON Patch
4. POST

I wanted to express my first experiences with this after implementing PATCH in a recent API. The specialty was (and is) that our resource is particularly large. We're talking about a data structure that has up to 20k nested JSON objects on 2 nested levels. Splitting it up didn't make sense for us since the whole thing, from a business perspective, is the actual unit of work (to be precise it's  a truck load of goods). We constructed an example of a typical size and measured/estimated an size of ~5MB.

We have multiple different consumers of this API operating on the resource and they need to update different, individual parts. E.g. adding a single property to one of the 20k elements. I tried to follow the list:

**PUT**
Too big for individual, smaller updates. For 20k individual, parallel updates (worst case) we would generate 100GB traffic.

**JSON Merge Patch**
[Section 2](https://tools.ietf.org/html/rfc7396#section-2) states:

> If the patch is anything other than an object, the result will always be to replace the entire target with the entire patch.  Also, **it is not possible to patch part of a target that is not an object, such as to replace just some of the values in an array**.

That significantly reduces the usefulness of the media type.

**JSON Patch**

Although I was not a big fan initially, because its imperative, RPC-style notion of operations in my mind didn't fit well with my understanding of REST. But after implementing it I have to say it's rather nice. Library support in my case was excellent. The content of the patch is still readable, although not as clear as JSON Merge Patch. Also a big benefit over PUT is that the server can implement optimistic locking without involving the client. PUT would require preconditions (ETag and If-Match). JSON Patch can simply be retried by the server if a conflict is detected.

I don't think that we have a strong need to adjust/change the guidelines right now. The current wording is fine. I just wanted to share some experience. If we feel like the guidelines could be extended, just let me know.

**Comment by ePaul** [comment]
Just a question from the implementation point of view: Did you apply the patch to a full representation of the object which then was stored back into the database (i.e. load object, apply patch, store object), or did you apply the changes just to the parts which actually were affected?

**Comment by whiskeysierra** [comment]
> Did you apply the patch to a full representation of the object which then was stored back into the database (i.e. load object, apply patch, store object)

Yes, including retries because we use optimistic locking.

**Comment by tfrauenstein** [comment]
@whiskeysierra thx. for this experience sharing.
I was not aware that JSON Patch does not support patching of array elements -- this is a mayor restriction. 
Yes, for the time being, I also see no need for changing the guideline. 
However, adding a hint would be great:  in your scenario of updating single objects in large collection JSON Patch is the right choice due to high payload volume and JSON Merge Patch restriction. 
Perhaps we can also http://erosb.github.io/post/json-patch-vs-merge-patch/ as further read reference.
