### ISSUE TITLE
Provide guidelines on batch/bulk requests and 207

### ISSUE THREAD

**Issue by dehora** [zalando/restful-api-guidelines#127]
WebDAV's 207 response code comes up from time to time and there's no specific guidance on using it, or not using it. More generally the guidelines don't cover idioms for batch requests. It would be worth looking at this area as bulk/batch processing is a common case. Even clearing up API terminology would be useful - "batch" in the industry is used to describe multiple http requests send inside a single request, as well as sending multiple records in a single object - "bulk" is also used for the latter case. There is further detail around whether the bulk/batch request results in an async "job" that can be checked for processing status.

An alternate approach taken to marking partial successes with 207 is to document 200 as successfully _processing_ a batch, but informing clients they need to check the details of the response entity to see what the processing results were for each item. Let's call this "client-must-check-response". For example this is how some AWS APIs work (Kinesis, SQS, DynamoDB). 

207 comes from WebDAV and it's context specific that they used 2xx instead of some other range. There's probably no ideal response class for a bulk response, but a downside is that 207 maps to the 2xx class which means generic http clients need to treat it as a special case when 207 is being used to describe partial failures/success. See [here](https://gist.github.com/dehora/409a14c52eece610c501) for more details on the history/intent.

**Comment by whiskeysierra** [comment]
> There's probably no ideal response class for a bulk response

I agree. My idea would be to give some power to the clients. There might be clients who want the *any*-semantic (2xx) while other prefer *all* (4xx). How about combining this with the `Prefer` header? The best match in the standard would be [handling strict and lenient](https://tools.ietf.org/html/rfc7240#section-4.4):

```http
POST /collection HTTP/1.1
Prefer: handling=strict
Content-Type: application/json

{"batch":[]}
```

```http
HTTP/1.1 500 Internal Server Error
Content-Type: application/json

{
    "type": "https://zalando.github.io/problem/partial-error",
    "errors": [
    ]
}
```

```http
POST /collection HTTP/1.1
Prefer: handling=lenient
Content-Type: application/json

{"batch":[]}
```

```http
HTTP/1.1 207 Multi-Status
Content-Type: application/json

{
    "errors": [
    ]
}
```

What do you guys think?

**Comment by ePaul** [comment]
@whiskeysierra The problem with using the `Prefer` header for that is that it is strictly meant to be just a hint, nothing the server has to obey.

**Comment by whiskeysierra** [comment]
Of course. So if the client doesn't hint what he wants the server can decide. One server may choose 207 the next 500.

**Comment by ePaul** [comment]
Discussion in our meeting:
* we look at bulk requests like groups of atomic requests, and always return 207, even if none are successful.
* 400/500 only for generic failures which happen before looking at individual items.

**Comment by ePaul** [comment]
Asynchronous requests are not covered by this, and might be preferred.

**Comment by tkrop** [comment]
> Asynchronous requests are not covered by this, and might be preferred.

@ePaul Thinking about this sentence, I disagree. A bulk/batch response in my opinion has always a higher priority than an asynchronous request. So if it is bulk/batch request, a response has to provide a multi-status object explaining which parts have been rejected or will be executed asynchronous.

**Comment by tkrop** [comment]
> (Still use 200 when all were successful.)

While writing this guidance, I'm not sure whether I would still uphold this decision. To allow for consistent handling by clients, it would be better to return 207 even in the case of full success.

200 only makes sense, if all clients only want to inspect the individual results if failures occur. Anyhow, I would still argue, that it should not be the service to decide about this.
