### ISSUE TITLE
Prefer functional names in oauth scopes

### ISSUE THREAD

**Issue by dehora** [zalando/restful-api-guidelines#129]
Not infrequently, oauth scopes are defined using a leading team name or a project name:
- `"myteam.content.read"`

We should prefer to have scopes organised around a bounded context eg "sales", or a domain function, eg "cart". A product/service name if it exists, is preferable to a project name (eg "grpc" the product name is better than "stubby" the internal project name). This doesn't affect auth mechanics  and the documentation doesn't encourage using team names, but it's quite common. 

There are at least two reasons to do this:
- Avoid complecting team names and project names with long lived API functions.  In Zalando at least, teams are to an extent encouraged to have function free names. Teams and projects come and go, APIs are forever. On the other hand a scope called "mighty-ducks.data.read" doesn't signal intent well. 
- For public facing systems we want a well organised set of bounded contexts and product domains that make sense to end users and not just Zalandos.

**Comment by whiskeysierra** [comment]
I wholeheartedly agree!

**Comment by ePaul** [comment]
Is this about the [Define and Assign Access Rights (Scopes)](http://zalando.github.io/restful-api-guidelines/security/Security.html#must-define-and-assign-access-rights-scopes) rule?

I did understand that our current solution with Yourturn just allows application name as the "thing before the dot"?

**Comment by codekultur** [comment]
I'm currently working on a concept for authentication and authorisation in the platform, that affects naming permissions as well. I would like to share and discuss my idea for naming permissions in the next guild meeting with you (idea so far is, that permissions are modelled around bounded contexts, but would like to introduce some more changes as well).

I'm still not sure, if the permission naming schema should be part of the public API guideline as they are very specific to Zalando (organisation and architecture). Maybe we should discuss this as well..

**Comment by ePaul** [comment]
> I'm still not sure, if the permission naming schema should be part of the public API guideline as they are very specific to Zalando (organisation and architecture). Maybe we should discuss this as well.

The whole guidelines are made for Zalando. Whoever wants to adopt them will need to see what applies to them anyways (and likely would have a fork to not be surprised by changes), so I wouldn't see this as a blocker.

On the other hand, one can question whether this actually belongs into **API** guidelines or somewhere else.

**Comment by ePaul** [comment]
Related: #132.

**Comment by LappleApple** [comment]
@dehora @ePaul @whiskeysierra @codekultur This issue dates back to August 2016. Is it still open to discussion/unresolved?

**Comment by codekultur** [comment]
This issue is related with https://github.com/zalando/restful-api-guidelines/issues/132 and will be fixed together with the other issue. Still in discussions...

**Comment by LappleApple** [comment]
Thank you for the fast updates, @codekultur.

**Comment by codekultur** [comment]
Guideline changes can be found here https://github.com/zalando/restful-api-guidelines/tree/new-naming-schema - should be merged after new naming schema is communicated.

**Comment by dehora** [comment]
Any progress on this issue?

**Comment by tkrop** [comment]
We are currently testing the practical consequences of the changed naming schema on routing and AWS setup. Before we integrate the naming changes we want to establish the process for acquiring and applying functional names.

**Comment by ePaul** [comment]
Closing for now.

**Comment by tkrop** [comment]
We will not work against a changing definition, so we reopen this issue, when things are clear.
