### ISSUE TITLE
Recommend functional names

### ISSUE THREAD

**Issue by bocytko** [zalando/restful-api-guidelines#132]
I will touch a very sensitive topic: service names. IMHO we should advise naming services that implement APIs to be with their name as close as possible to the API name itself.

I'm observing a high number of services with names that are more or less random (hero names, chemical elements, ...). Such names make it very difficult to understand the architecture of a system or even parts of it. It's also impossible to add such names to any kind of documentation or diagram.

A rule of thumb is to name the service with the root aggregate, entity or bounded context that's being managed by it. Examples:
- `Stock Location` for managing _Stock Locations_,
- `Sales Order` for managing _Sales Orders_,
- `Retail Catalog` manages _Retail Products_ (aggregate of product, price and stock data).
- `Fulfillment Order` for managing _Fulfillment Orders_, _Shipment Orders_, _Shipments_ (bounded context).

One can of course argue, that in different domains, an order means sth. different. However, prefixing the entities with the domain (bounded context) name is widely used: _Purchase Order_, _Sales Order_, _Fulfillment Order_, _Shipment Order_.
### Technical services & abbreviations

Code names are widely used for technical services, appliances and libraries (_Nakadi_, _buku_, _bubuku_, _spilo_), which is perfectly fine in my point of view. Other examples exist though (_Exception monitor_, _Deploy Control_).

Smart abbreviations like _Cuxy_ for _CUstomer proXY_ should be allowed for technical components like caches, tools.
### Suggestion for the guidelines

**Service names (and thus their public URLs)**
- Must: Service name is closely related to the entities, aggregate or bounded context that they manage (i.e. _Fulfillment Order_, _Sales Order_, _Stock Location_).
- Must: Use code names internally, don't expose them to clients.
- Could: Use code names for technical infrastructure components (like _Nakadi_).

/cc: @codekultur @tfrauenstein

**Comment by ePaul** [comment]
I guess this could go into the "Naming" section.

**Comment by codekultur** [comment]
I think we should discuss this together with the naming of permissions-topic, as they might relate - both should be modelled around bounded context names IMHO.

**Comment by LappleApple** [comment]
@ePaul @codekultur @bocytko Hey, is this question still on the table ("open") or did you resolve it?

**Comment by codekultur** [comment]
We are still discussing a coherent model for naming API hosts, permissions and event names based on Zalando's product structure and functional components. As we don't want to introduce a central API gateway, but use a DNS based approach (which is then coupled in some way to AWS accounts), this is a larger topic: We must find a solution that keeps those names resilient against organisational and technical changes. If you like to know more details of the current discussion, please let me know.

**Comment by codekultur** [comment]
Guideline changes can be found here https://github.com/zalando/restful-api-guidelines/tree/new-naming-schema - should be merged after new naming schema is communicated.

**Comment by bocytko** [comment]
Amazing to see this moving forward!

**Comment by akauppi** [comment]
Thanks, Bartosz, for bringing this up.

Only yesterday, I realised that “Bankroll API” has nothing to do with money, or bankrolls, but serving product pictures.

- asko
