### ISSUE TITLE
PDF version: some oddities

### ISSUE THREAD

**Issue by ePaul** [zalando/restful-api-guidelines#14]
Looking at the PDF version generated after #12, I've found some things to improve.
I have not looked at the generation process, so I have no idea if they even can be improved at all.

* Each page's header has "Introduction", not only in the "Introduction" section.
* There are some spurious blank pages (3, 4, 7, 26) – one of them (page 4) is titled "Table of Contents", but is otherwise empty.
* The Section titles have same size as the guideline titles.
* There should be authorship and copyright mentioned somewhere (e.g. on a title page). I guess this ties in to #7. Maybe also the generation date (and/or commit date/commit ID from which it was generated?)
* At some points there is a page break right after a title (e.g. page 18).

**Comment by fmueller** [comment]
@ePaul Do we wanna close this issue because the html version is our main version and improving the pdf version seems to be a lot of effort.

**Comment by whiskeysierra** [comment]
:+1:

**Comment by ePaul** [comment]
@whiskeysierra is this :+1: meant for my list of oddities or for @fmueller's proposal of closing the issue?

@fmueller I guess we decide to not support the PDF, but then we should make this clearer in the links in the README.

**Comment by fmueller** [comment]
Ok, I will do this @ePaul
