### ISSUE TITLE
Document If-Match + If-None-Match for PUT

### ISSUE THREAD

**Issue by ePaul** [zalando/restful-api-guidelines#154]
We should mention the usage of conditional requests for updates/creates, to avoid the lost update problem.

* `If-None-Match: *` when creating a resource with PUT makes sure you don't overwrite a resource created by someone else without noting.
* `If-Match: ...` when updating a resource with PUT (or PATCH) makes sure you don't overwrite changes by someone else without noting.

**Comment by ePaul** [comment]
@whiskeysierra: @tkrop suggested that you might want to write something here?

**Comment by tkrop** [comment]
Added extended section under common headers and removed existing description under performance. In addition I added reference from PUT and PATCH.

@codekultur have a look to the expected status code 412. If I remember correctly, this is different from our talk, but it is what is expressed by [RFC7232](https://tools.ietf.org/html/rfc7232#section-3.1).
