### ISSUE TITLE
Consider use of RESTful term in the guidelines

### ISSUE THREAD

**Issue by dehora** [zalando/restful-api-guidelines#161]
The guidelines lead with term RESTful, and while there are some use of the constraints, use of hypermedia in particular is limited (mostly to drive pagination). 

They guidelines don't argue against REST, but nor do they advocate strongly for example, for content models that use a state machine driven approach, where transitions are performed by clients working with document links. 

It's arguable then, the term could be removed from the leading material and point to the discussion elsewhere in the document on tradeoffs.

If done, this might require a new github project as "restful" is in the project url.

**Comment by hjacobs** [comment]
Linking the trigger of this: https://twitter.com/stilkov/status/806979435429773312 :smirk:

**Comment by hjacobs** [comment]
Still waiting for an answer to https://twitter.com/ebowman/status/807154435755536384 ...

**Comment by mohabusama** [comment]
The reply: https://twitter.com/stilkov/status/807219063185408000

Github API,, of course :)

**Comment by whiskeysierra** [comment]
> Github API,, of course :)

Totally disagree. They just provide links for reading. There is not state changed initiated through links.

**Comment by tfrauenstein** [comment]
I personally think this discussion is rather academic and provides no value for us. However, I propose to complement our guidelines with the footnote that we stick to usage of the term for our REST approximations (like the very industry majority) --> see #169
