### ISSUE TITLE
Security definitions example and guideline is not compatible with Swagger definition

### ISSUE THREAD

**Issue by dcherepovsky** [zalando/restful-api-guidelines#163]
https://github.com/zalando/restful-api-guidelines/blob/master/security/Security.md#-bookmust--secure-endpoints-with-oauth-20

`flow: password` shouldn't be used with `authorizationUrl`. It should be used with `tokenUrl`. Swagger definitions which follow current guideline are automatically invalid.

**Comment by hjacobs** [comment]
@dcherepovsky good point!

**Comment by codekultur** [comment]
Fixed with https://github.com/zalando/restful-api-guidelines/pull/166
