### ISSUE TITLE
Recommend use of commutative events

### ISSUE THREAD

**Issue by BGehrels** [zalando/restful-api-guidelines#170]
Designing a resilient and fail safe event based architecture is hard when you are relying on implicit event ordering assumptions. 

As an event sender, you will be forced to send events in the order they occurred. If you are unable to send one event (for example due to an illegal null field in your payload), your only option is to stop sending events completely, let an engineer fix that one event, and then continue. Skipping an event and sending it later will violate the ordering guarantees that are part of your APIs contract.

The same problem exists on the consumers side: If you are unable to process an event for any reason, you have two options:
- Retry again and again to consume the event, until it works (for example, because an engineer built a workaround). If the error is just a temporary database hick up, that is fine. If it is a software bug, event consumption will effectively freeze until an engineer fixes the bug. Even if all the other following events would be perfectly consumable. Freezing in a live environment seems no acceptable solution.
- Log the event (or put it into a dead letter queue), skip it and continue. This approach solves the "freezing" problem, but comes with it's own downside: You will not be able to reconstruct the application state reliably and (semi-) automatically, because replaying the failed events later will violate the ordering guarantees and therefore give undefined results and probably lead to data corruption/data loss.

As a conclusion, relying on message ordering in your event based architecture is a pretty bad idea. 

Sending commutative events, that can be sent and received out of order will solve these problems. As a consumer, even if i could not process one of the events for some time, i will eventually converge into a consistent state again. It will probably take some more thoughts during system design to get those right, but i have not seen cases in the last four years where this was an unsolvable problem.

So, here is my Pull Request: https://github.com/zalando/restful-api-guidelines/pull/178

I would even say, let's make it a *must* instead of a *should*, but since i do not know if i've missed some essential requirements, i sticked with the should.

So: feedback welcome.

**Comment by codekultur** [comment]
I totally agree with your points and would add one more: Relying on the order in the transport layer makes it hard to dynamically scale your application. You can only have one thread reading from the queue and one thread sending to the queue if you like to keep the order.
Of course you could use sharding and keep the order per shard (if this is possible within your problem domain) to scale up, but you cannot just dynamically scale based on the load of the message queue.

**Comment by valgog** [comment]
@BGehrels I would love to get more details on your use cases. Let's meet and discuss these use-cases. Especially the ones that do not need ordering.

**Comment by valgog** [comment]
@codekultur Solving the problem of reordering on the application level could be quite a difficult task, depending on the limitations you have. If ordering *is* a retirement, one has to deal with this strong limitation. That is why it would be so important to understand what are the real use-cases and if the ordering is not important indeed.

**Comment by BGehrels** [comment]
From what i experienced in the past years, messaging clients can be somehow clustered in three categories:

# Systems that need access to the history of a resource
BI systems, audit trails and metrics collectors are common examples. For these kind of systems it is easy to reorder events. They have to maintain a persistent representation of the history anyway. Given that they do not prematurely throw away the raw data, it's mostly a matter of `ORDER BY seq_key` to get those into a correct order again.

# Systems that need access to the (as) current (as possible) state of a resource
In these cases, the application uses the event as a state change notification. It will hold a cached read only version the latest seen state and use events to update those caches. If you receive an event with an older `seq_key` than the one of your currently cached version, you can simply ignore the event. Otherwise, you update the cache with the state you just received.

This implies that you send self-contained events - events that contain information about _"what happened"_ as well as the _resulting state_.

# Systems that need access to the state of the resource at the time the event has been sent
Those systems mostly react on the _"what happened"_ Part of an event. These systems can often be made idempotent and commutative by fostering immutablility in the senders domain: If an "order" is mutable and referred by it's id, the "CANCELED" event and the "SHIPPED"-event make must be reordered by the receiver to make sense of them. When it is versioned, versions are immutable and the entity is referred to as (entityId, version, EventType), Order1 v1 CANCELED, Order1 v2 SHIPPED makes sense again, regardless of their sorting sequence.

# Conculsion
This third case is probably the hardest, and there is not a one-size-fits-all solution for it. But during the last years of working with messaging for inter-service-communication i've not seen a use case where ordering requirements could not be avoided by thinking twice how to structure your events and your domain.

Nonetheless, since there are and will probably be cases that can not circumvent the ordering requirements, i formulated this paragraph as a *SHOULD*, not as a *MUST* :-).
