### ISSUE TITLE
Permission of Events should correspond to API Permissions

### ISSUE THREAD

**Issue by fmueller** [zalando/restful-api-guidelines#171]
We already state in our guidelines that events should correspond to API design principles, should be review and should be aligned with business entities exposed via the restful API. There is also a paragraph about permissions and that they will be introduced via Nakadi. (see http://zalando.github.io/restful-api-guidelines/events/events.html)

I think we should also point out more clearly that events should use permissions of corresponding restful API. This would keep data access consistent across both APIs, restful one and events.

What do you think?

**Comment by ePaul** [comment]
Related: #132, #129.

**Comment by ePaul** [comment]
Discussed today: we want a MUST here, as those permissions are for data protection, not for things like load/performance considerations.
