### ISSUE TITLE
Publish an epub

### ISSUE THREAD

**Issue by matozoid** [zalando/restful-api-guidelines#175]
If there is an option to export an epub somewhere, please turn it on. This way I could throw it on my ereader and read through the whole book comfortably.

**Comment by fmueller** [comment]
Very good point. Because we have some custom plugins, it can be hard to enable this in the build (like with PDF). But I try it.

**Comment by fmueller** [comment]
@matozoid I added necessary documentation to readme (see pull request) which should enabled you to build it locally. The ePub file looks quite good. Enjoy. :-)

**Comment by matozoid** [comment]
Thanks!
