### ISSUE TITLE
Recommend rules for restful API to model (complete) business processes

### ISSUE THREAD

**Issue by tkrop** [zalando/restful-api-guidelines#183]
Recently, I observed that we get very small API definitions for review which cover only parts of business processes - or worse provide only a thin wrapper around the data base resource.  As effect the business processes and resources are distributed over many APIs creating invisible implicit dependencies, which make it hard to understand the logic of the business processes and the relation between resources.

In my opinion this is an API design (and service design) we should discourage in the guidelines - as we currently try do in our API workshop.

Therefore, I suggest add rules to the guideline that should to encourage the following design practices:

1. Resources should be designed to represent business processes, e.g. like orders, to prevent thin wrappers around databases that normally tend to shift business logic from service to clients.
2. An API should contain the complete business processes with respect to its representing resources, to enable clients to understand the business process, to foster a consistent design of the business process, to allow for synergies from description and implementation perspective, and to prevent implicit invisible dependencies between APIs.

Beside, this new rules, we should rephrase our rules about resource limits to make clear, that limitation rules are targeted to encourage the detection of complete and sometimes generic sub-processes, that should be cut out to reduce the complexity of an API and service.

**Comment by codekultur** [comment]
See https://github.com/zalando/restful-api-guidelines/tree/model_compleate_business_processes for a first proposal.

**Comment by ePaul** [comment]
Here is [the diff](https://github.com/zalando/restful-api-guidelines/compare/model_compleate_business_processes?expand=1).
