### ISSUE TITLE
Forbid designing parameter chains in URLs

### ISSUE THREAD

**Issue by fmueller** [zalando/restful-api-guidelines#184]
Currently I've seen APIs with following patterns in URLs:

/resourceName/{identifier1}/{identifier2}/{identifier3} (nested identifier structure, not nested resources)

I assumed we have a rule to prohibit this but it turned out we haven't. I talked with @codekultur about this, he was surprised as he assumed the same.

I'd like to:
- decide if wanna forbid this design pattern
- find a better headline/name for this

**Comment by ePaul** [comment]
Discussed in the meeting: This should be added as text to the "Must: Identify resources and Sub-Resources via Path Segments" rule in the resources section.
