### ISSUE TITLE
new guideline: must process events in a way that tolerates duplicates

### ISSUE THREAD

**Issue by ePaul** [zalando/restful-api-guidelines#185]
This is a guideline for event consumers, not for the API itself.

Add some reasoning, like "at-least-once" delivery semantics.

**Comment by tkrop** [comment]
I don't understand: This rule is out of scope of an API guideline. In maximum we can add a sentence that suggests clients to react like this. We currently have to pull requests hanging that address related issues from API side. What is the expected task related to this issue? Can't we address this aspect in the pull requests?

**Comment by maxim-tschumak** [comment]
I agree with you, @tkrop. I've added a comment to PR #178

**Comment by fmueller** [comment]
The idea was in the meetup back then that it would be good to state this extra, how clients should act on consuming events. We have similiar rules for Restful API consumers (e.g. robustness principle).

**Comment by maxim-tschumak** [comment]
Ok, that makes sense @femueller, let's have here also some advice for the event consumers. I'll provide a PR.

**Comment by fmueller** [comment]
Btw @maxim-tschumak, you referenced the wrong Felix Müller ;-)
