### ISSUE TITLE
Describe how different access scenarios and supported token types must be documented

### ISSUE THREAD

**Issue by codekultur** [zalando/restful-api-guidelines#197]
As we will have APIs in the future supporting different access scenarios for Zalando APIs, APIs need to document which access scenarios and token types are supported and how authorisation works.

Current idea is to define a Swagger extension for this.

**Comment by codekultur** [comment]
Introduced a must rule here: https://github.com/zalando/restful-api-guidelines/tree/document-access-scenarios

Should be merged after services migrated to Platform IAM and new tokens are used.

**Comment by ePaul** [comment]
*Update:* Narrative for rollout is being worked on, when it is clarified we should update the guidelines.

**Comment by ePaul** [comment]
*Update*: We want at least document the current state of the art. @codekultur will have a look.

**Comment by zeitlinger** [comment]
closed due to inactivity (no objection from guild meeting)
