### ISSUE TITLE
Refer to RFC 7807 for the common error object

### ISSUE THREAD

**Issue by ePaul** [zalando/restful-api-guidelines#2]
I just noticed (looking for the April fools RFCs) that there is a new [RFC 7807](http://tools.ietf.org/html/rfc7807) defining a JSON error object, which seems to be based on the draft to which we are referring in the common data objects section.

That section should be adapted to refer to this RFC instead.

The RFC defines it as `application/problem+json`, while our guidelines are using `application/x.problem+json`. I guess we need some guideline about transitioning between both, because old clients might expect the content type with `x` (and old servers send it with `x`), while new clients would expect it without `x` (and new servers send it without `x`).

**Comment by hjacobs** [comment]
:+1:

**Comment by mostlymagic** [comment]
@ePaul rather than filing an issue, why don't you submit a pull request?

**Comment by ePaul** [comment]
> @ePaul <https://github.com/ePaul> rather than filing an issue, why don't
you submit a pull request?

I noted that on a weekend, when I don't work, and filed the issue so I
don't forget it. I will create a pull request as soon as I find some time
to do it (if noone else does it earlier).
