### ISSUE TITLE
Common Data Objects: Separate Receipient from Address

### ISSUE THREAD

**Issue by meshcalero** [zalando/restful-api-guidelines#203]
Currently the Address model covers two aspects WHO and WHERE. If you want to model recipients with multiple addresses, or add additional information about the person receiving something that has nothing to do with its address, you can't nicely do this.

If we would instead have two distinct models (e.g. Party and Address) for the two aspects we could overcome that problem.

To avoid misunderstanding, we could also rename the attribute business_name within address to something like care_of, to make it clear that the business is not the recipient, but only the place where you find the recipient. If we want to model businesses as recipients (AFAIK we don't cover B2C business yet), we could still keep business_name in recipient.

**Comment by ePaul** [comment]
Discussed in Guild meeting today:

* reword the existing guideline to not prescribe this exact object format, but define the field names, and allow objects with different structure.

**Comment by ePaul** [comment]
Discussed in today's meeting:
* We also want to combine the other "common field names" into this rule.
* mention that fields referring to other entities' identifiers should be named `xyz_id` (and not e.g. `customer_number`)
* having an example schema (for copy + paste) is a good idea.
* rename the chapter to "Common data types", including both fields (generic + address) and objects (problem + money)
