### ISSUE TITLE
Make validation logic change an extra chapter

### ISSUE THREAD

**Issue by fmueller** [zalando/restful-api-guidelines#204]
Make added paragraph about validation logic in #191 an extra rule.

**Comment by fmueller** [comment]
Related to #177

**Comment by tkrop** [comment]
I hope you mean section. Chapter would be over emphasized.

**Comment by tkrop** [comment]
@tfrauenstein Can you although solve this with #248?

**Comment by ePaul** [comment]
Was not done with #248.

**From the meeting**:

* It might be useful to mention explicitly "Please mention your validations in the API description", not just as a subphrase in a bullet point in the compatibility section.
* We decided that for now it is not needed, we already have too many rules.
