### ISSUE TITLE
Design chapter about error handling

### ISSUE THREAD

**Issue by fmueller** [zalando/restful-api-guidelines#205]
In last weeks the API guild discussed several times that API providers should think more about design of error handling and error mitigating across services.

We want to have a dedicated chapter for error handling.

Please add your thoughts on this here @ePaul @tfrauenstein @tkrop @codekultur @dehora and all the others I forgot.

**Comment by fmueller** [comment]
Findings in today guild meeting: move 'Do not expose Stack Traces' and 'Use Problem Json' to this new chapter (from 'Common Data Object' chapter).

**Comment by tkrop** [comment]
Consolidation of this topic makes sens: We although have a section [must provide error documentation](http://zalando.github.io/restful-api-guidelines/http/Http.html#must-provide-error-documentation). In the before mentioned section I see the problem, that it has some kind of inconsistent guidance on when to document errors - functional: yes, technical: no, but no guidance how to exactly distinguish them, e.g. is `403 - not found` technical or functional?

**Comment by tkrop** [comment]
May be we although need a proper client guidance, how to implement proper error handling. This may include some similar topics to the ones in API operation chapter.

**Comment by ePaul** [comment]
**From the meeting:** We currently don't see the need for the refactoring, so we don't do this now.
