### ISSUE TITLE
Add guideline for header parameters

### ISSUE THREAD

**Issue by ePaul** [zalando/restful-api-guidelines#206]
Triggered by Nakadi's latest API proposals ([e.g. Nakadi #592](https://github.com/zalando/nakadi/pull/592/files#r106128701)), we want to have a guideline which restricts putting significant parameters (i.e. ones which decide the main semantics of an operation, not just context like language, data formats, etc.) into HTTP headers.

Those should be put preferably into the URL, i.e. either as path (if part of an resource identifier) or query parameters. If that is not possibly, a request body with POST can be used.

**Comment by dehora** [comment]
@tkrop @ePaul :1st_place_medal: thanks for actioning this quickly, it's very much appreciated

**Comment by ePaul** [comment]
Duplicate of #207 (which has a better description).
