### ISSUE TITLE
Give better guidance on when to use GET with headers and query parameters or POST with body regarding size limits.

### ISSUE THREAD

**Issue by tkrop** [zalando/restful-api-guidelines#207]
API designers sometimes face the problem, that they have to provide extensive structured request information with GETs, that may even conflicts with the size limits of clients, load-balancers, and servers. In this situations API designers and developers have to chose between:

1. GET with URL encoded query parameters,
2. GET with header parameters,
3. POST with body content.

Currently, we do not give proper guidance to handle this case, and what are the advantages and disadvantages.

We discussed this in the last guild meeting and came to the following conclusions:

* It feels unnatural for users to provide request parameters via headers.
* Header parameters are itself object to size limitations, thus no *real* solution to the size problem.
* Size limits on query parameters and headers are not reliable at all and depend more on clients, routers, and server as well as settings as on the difference between header and query parameters.
* Query parameters are the preferable choice to express request information, even if the URL encoding limits the readability to a small degree.
* If the structuring of the query information it too extensive, a POST with the request in the content body should be used to transport the query information. The end-point should be marked to behave like a GET (need to work out syntax).

In addition we would like to add an advise that headers are reserved for contextual information that are not part of the data model of the API.

Please comment further suggestions and opinions to this issue.

**Comment by ePaul** [comment]
An additional issue with OpenAPI 2.0 is that there is no way to put complex objects into anything other than a body parameter, because there is no way to specify how it would be serialized. So putting an object into a header parameter (or query or form or path parameter, by the way) is just not possible in any defined way. In Nakadi's case, they are defining it as a string, with the format property referencing the schema definition.

OpenAPI 3.0 will help here (defining some "styles" for simple cases, and a way to use a media type for more complex ones), but we are not there yet.

**Comment by ePaul** [comment]
From the conceptual point of view, I think the main meaning of an operation should be expressed with the resource name and its query parameters, i.e. what would go into the URL. Request headers are for context information. When we have "please calculate the difference between these cursors" or "please add these cursors to those shifts", the cursors (and shifts) are the main input.

**Comment by ePaul** [comment]
Using POST, or distributing the "complex object" on multiple simple query parameters. The latter one won't work well for bulk requests, of course.
