### ISSUE TITLE
Add mandatory Zally usage to API review procedure

### ISSUE THREAD

**Issue by fmueller** [zalando/restful-api-guidelines#209]
We plan to go live with Zally (https://github.com/zalando-incubator/zally) and therefore usage of it should be mandatory before an API is handed over for review.

- add paragraph about Zally usage to API review procedure chapter
- add usage information or link to it

**Comment by tfrauenstein** [comment]
👍 

hint: a) PR in review procedure repo -- not guideline relevant.
b) There are other aspects that need to be updated:
- OpenAPI 2.0
- syntax check via Swagger.io -- see my mail about Zally OpenAPI 2.0 compliance check
- YAML not JSON format
- review via dedicated PR on GH/GHE (no Stash or Google doc anymore) -- some editorial consequences

**Comment by whiskeysierra** [comment]
> YAML not JSON format

YAML is a superset of JSON. Any valid JSON document is also valid YAML.

**Comment by tkrop** [comment]
> YAML is a superset of JSON. Any valid JSON document is also valid YAML.

Surly true Anyhow, Basic JSON-less YAML syntax allows far better human readability. We currently state:

> You should use YAML format (instead of JSON) for the OpenAPI API definition files due to its improved readability.

Should be we change this to:

> You **must** use YAML format (instead of JSON and without JSON syntax) for the OpenAPI API definition files due to its improved readability.

to take willi's remark into account?

**Comment by fmueller** [comment]
I prepare a guideline change to make this clear @tkrop and will update our internal review procedures.

YAML is must and JSON should not be used for Swagger files.

**Comment by tfrauenstein** [comment]
👍

**Comment by tfrauenstein** [comment]
@fmueller When you prepare the PR -- a short hint to the Zally Project in the introduction of the "General Guidelines" section would be helpful too. Thx.
