### ISSUE TITLE
Gender guideline?

### ISSUE THREAD

**Issue by ePaul** [zalando/restful-api-guidelines#211]
There was a request in our hipchat to have a guideline about how to encode a gender (for customers, articles, pages).

This issue serves to document the arguments, and possibly find a guideline.

**Comment by AlexanderYastrebov** [comment]
It seems there are at least following use cases:
* customer sex
* customer salutation
* customer gender
* article gender (or set of genders to express unisex)

https://en.wikipedia.org/wiki/Sex_and_gender_distinction
https://en.wikipedia.org/wiki/ISO/IEC_5218
http://microformats.org/wiki/gender-formats

**Comment by ePaul** [comment]
There is also the related concept "target group", which is something like "Men, women, children, possibly baby".

**Comment by oporkka** [comment]
In my opinion, it's best to concentrate on the target gender of the articles in catalog instead of the "sex" of the customer. Then we should be talking about `man` or `woman`. If it's not a binary selection but there can be several values, unisex can be presented by having the both values `["man", "woman]`. Otherwise we have to define more options.

**Comment by fmueller** [comment]
We should ask product management for common terms and if common terms would solve an issue.

**Comment by tkrop** [comment]
I think, we can do this only wrong 😞.

From a customer perspective `gender` is a good neutral term, but when it comes to possible values: `man`, `woman` ... [here a potential complete list](http://itspronouncedmetrosexual.com/2013/01/a-comprehensive-list-of-lgbtq-term-definitions/#sthash.vys9GbHy.dpbs) - I have to pass. 

For products, I think, `target_groups` is a good name, but what does it encode? Only gender or gender and age? Seems to be a list ...

**Comment by fmueller** [comment]
It's not really an API design topic, more about a common Glossary across our product if I understodd you correctly.

**Comment by tkrop** [comment]
@fmueller Yes and no. Glossary is exactly, what we are doing in [Common Data Objects](http://zalando.github.io/restful-api-guidelines/common-data-objects/CommonDataObjects.html) and some other sections. So it could be part of our guideline.

**Comment by fmueller** [comment]
Especially this case is highly dependent on business context imho. So I personally find it extremely hard to find a good guideline which fits all needs: only a long list of possible encodings. If this adds value should be discussed.

**Comment by oporkka** [comment]
I find that the guidelines is needed. I have seen API endpoint which requires `gender=MR|MRS`. Could be unified to `gender=man|woman`.

**Comment by dehora** [comment]
> This issue serves to document the arguments, and possibly find a guideline.

The best case I can see here is updating the text to indicate no global guidance.

**Comment by jhorstmann** [comment]
IMHO the only reasonable guideline would be "don't use gender in your api, it's too complicated". Depending on the usecase there might be several alternatives that should be choosen on a case-by-case basis, like "salutation" or "target group".

**Comment by oporkka** [comment]
For the time being and I think very much in the observable future we'll have the need to pass parameters called "gender". What was the initial motivation was to have one proposed set of values to avoid that one API is using `gender=(MR|MRS)` and another `gender=(man|woman)` and one service returning even male/female for the field.

**Comment by ePaul** [comment]
Discussed in the meeting:

We think there is no urgent need to define this in the guidelines for the whole company.
It should be done use case specific.
