### ISSUE TITLE
Expose information about owning tenant in order to build external authorisation

### ISSUE THREAD

**Issue by codekultur** [zalando/restful-api-guidelines#221]
As authorisation in the multi-tenant platform becomes more and more complex, we want to make it possible to handle authorisation outside the actual service (e.g. in some infra-structure component in front of the service). Therefore information about the owning tenant of a certain resource must be made accessible for a potential external authorisation logic (that then compares the tenant id in the token with the owner of the data).

Discussion around this topic is done in [an internal document](https://docs.google.com/a/zalando.de/document/d/1cqa6sevpUbZd_q-n4j-pnuIaZ2UNqNaVOkwKTI4ch80/edit?usp=sharing).

**Comment by codekultur** [comment]
I think we have to look a little bit deeper into variant 2:

GET is easy: If the returned payload contains the owing tenant, and the authorisation code knows to find the owner in the payload, it's easy to do authorisation.

Creating new resources via POST (or PUT) is easy, too: The owner of that data could be taken from the token (or explicitly specified via the payload and checked, that the token holder may create entities in the context of the tenant specified in the payload (or URL))

But when it comes to updating resources (PUT, DELETE), this variant has the same drawback as variant 1: Before updating the resource, the service must check, that the owner of the existing resource is equal to the tenant extracted from the token. Of cause it cannot just rely on a owner set in the payload.

So in the end we should either come up with a third variant (without duplicating DB calls), or we should just accept, that the authorisation logic cannot be implemented independent of the actual service.

**Comment by tfrauenstein** [comment]
Tagging data resources with data ownership information is a initially-write-once-activity.
So each update trial with different owner should fail.
If this rule is implemented by all multi tenant server business logics, both centralised authorisation variants works w/o additional get-ownership-info roundtrip. (Editorial remark: I would not call this rule a "decentralized, local authorisation logic")

P.S: IMO it feels better to have this initial design discussions on multi tenant security implementation outside the scope of the public API guideline repo, e.g. via internal draft google doc.

**Comment by ePaul** [comment]
**From the meeting**: Postponed for now, as a central authorization engine for multi-tenancy support is not yet planned concretely.
