### ISSUE TITLE
Add guidance for handling of multiple values query parameter

### ISSUE THREAD

**Issue by fmueller** [zalando/restful-api-guidelines#223]
Currently we give no guidance in our guidelines in which form multiple values query parameters should be specified in an API:

`?parameter=value1&parameter=value2&parameter=value3`

or

`?parameter=value1,value2,value3`

We may also consider possible framework implications, maybe some frameworks only allow one of the approaches.

**Comment by whiskeysierra** [comment]
Copying my own response from the chat:

>  Both are fine, imho. If you use Spring it will actually support both at the same time, if you use a Collection as a parameter to your controller. Unfortunately you can only specify one of them in OpenAPI. Generally speaking most REST purists prefer the first since it looks and feels more HTTP. But the second one could be way shorter if your parameter name is longer, so that's also something to consider, especially in regards of maximum URL length.

**Comment by ePaul** [comment]
See Parameter → collectionFormat in Swagger.
* Should be defined explicitely in API
* we mention advantages/disadvantages of both

**Comment by ePaul** [comment]
Fixed by #236.
