### ISSUE TITLE
Remove library level guidance dependency on json-fields

### ISSUE THREAD

**Issue by dehora** [zalando/restful-api-guidelines#224]
From the section [Performance.md#-bookshould--support-filtering-of-resource-fields](https://github.com/zalando/restful-api-guidelines/blob/master/performance/Performance.md#-bookshould--support-filtering-of-resource-fields)

> The approach we recommend for field filtering is a Zalando Github project, json-fields. It defines a formal grammar for the ANTLR parser generator and provides a ready-to use library for Java / Jackson based projects (Maven link). Teams that use other JSON serializers are encouraged to contribute to the open source project and create their own parser / framework based on this grammar.

This puts a dependency on a library into the guidelines. That seems to be contrary to API-first. It's not clear how widely adopted the standard or library [1] is even within Zalando or that it's been known this design is effective and successfully adopted. The concern is that this approach was  standardized ahead of sufficient experience.

In any case, the guidelines should specify in a way that doesn't require a library and a grammar file pinned to a particular runtime. 

----

[1] The library itself has problems, it introduces a runtime dependency on guava (and antlr), but that's best filed upstream on the library itself.

**Comment by tkrop** [comment]
@dehora agreed that the library is far from being a good reference. We should directly describe the syntax and semantic of the standardized filter, in a way that allows anyone to implement it.

**Comment by tfrauenstein** [comment]
👍  we already identified this action item, but missed to track it.
