### ISSUE TITLE
Remove large graphic from guideline introduction

### ISSUE THREAD

**Issue by dehora** [zalando/restful-api-guidelines#225]
The graphic in the introduction takes up half the page. It could be removed to allow the content to take priority.

----

<img width="944" alt="screen shot 2017-05-09 at 09 13 41" src="https://cloud.githubusercontent.com/assets/5454/25841424/f8c08f7a-3497-11e7-9e14-298a41b99e23.png">

**Comment by tfrauenstein** [comment]
I would like to keep the graphic -- it contributes to "branding" of our API activities. 
But I propose to resize the image 1/3 (ca. 65pts).

**Comment by whiskeysierra** [comment]
> it contributes to "branding" of our API activities

Do we actually use it anywhere else?

**Comment by tfrauenstein** [comment]
We have used it as logo for the API Guild (tech wiki, newsletter etc.) and in Tech Blogs so far.

**Comment by tfrauenstein** [comment]
#240
