### ISSUE TITLE
Use rfc2119 keywords to indicate guidance levels

### ISSUE THREAD

**Issue by dehora** [zalando/restful-api-guidelines#226]
The guidelines mandate guideline levels without explaining what they mean. It's customary to use RFC2119 in such cases as they're widely understood in the industry. MSFT and GOOG guidelines both use RFC2119. There doesn't seem to be much value in having  undefined terminology.

This can be added to the introduction:

>Conventions Used in These Guidelines
>
>The requirement level keywords "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED", "MAY", and "OPTIONAL" used in this document (case insensitive) are to be interpreted as described in [RFC 2119](https://www.ietf.org/rfc/rfc2119.txt).

With the following mapping:

| Current term | RFC2119 |
| ------------ | ------------- | 
| Must |  Must | 
| Should | Should |
| Could | May |  

The changes in the text are minimal (`could` is replaced by `may`). Also the `required` term allows the guidelines to indicate and discuss mandates that come from aspects such as rules of play.

**Comment by tfrauenstein** [comment]
👍

**Comment by ePaul** [comment]
From the meeting: We agree this is a good idea.
When changing the word could to may, we need to make sure the build process (Gitbook plugin for highlighting) still works.

@dehora Do you want to work on this?

**Comment by dehora** [comment]
Ok, see https://github.com/zalando/restful-api-guidelines/pull/232
