### ISSUE TITLE
Clarify compatibility status of Open API definitions and generated code

### ISSUE THREAD

**Issue by dehora** [zalando/restful-api-guidelines#227]
It's possible to use multiple Open API definitions to define the same JSON structure. 

The guidelines talk about compatibility in terms of the JSON at "runtime" and not about compatibility of object definitions. The guidelines also say code generation is fine. From [here](http://zalando.github.io/restful-api-guidelines/tooling/Tooling.html):

> The following frameworks were specifically designed to support the API First workflow with OpenAPI YAML files
>...
> - Swagger Codegen: template-driven engine to generate client code in different languages by parsing Swagger Resource Declaration
> - Swagger Codegen Tooling: plugin for Maven that generates pieces of code from OpenAPI specification

Nothing is said about the compatibility of the definition itself with respect to generated code. Changing a definition file such that client code breaks but the runtime output is the same might lead to confusion around what a compatibility break is.

It could be argued that the emphasis on the REST plus API-first principles, and the compatibility section would make it obvious that as long as the runtime JSON doesn't break, Open API changes are compatible. I'm not sure this is sufficient because it's implicit.

**Comment by ePaul** [comment]
From the meeting:
* We agree that the compatibility guarantees are just for the "on-the-wire" (JSON) format described by OpenAPI, in the sense that clients following the old API definitions still work with the new API. We don't agree source or byte code or similar compatibility for anything generated from it – updating a client to a new API definition version would usually imply changing some of the using code (if you are using a generator at all).
* The whole Tooling section is not really part of the guidelines, more some kind of appendix. We might need to think about how to make this clearer.

**Comment by ePaul** [comment]
I opened pull requests #141 + #142 for this.

**Comment by ePaul** [comment]
@dehora could you have a look at the pull requests?

**Comment by ePaul** [comment]
With both PRs being merged, I think this can be closed. @dehora please reopen if you think I missed something.

**Comment by dehora** [comment]
> With both PRs being merged, I think this can be closed.

👍  Nice work!
