### ISSUE TITLE
Improve HTTP method guidance

### ISSUE THREAD

**Issue by dehora** [zalando/restful-api-guidelines#234]
The guidance ["Use HTTP Methods Correctly"](https://github.com/zalando/restful-api-guidelines/blob/master/http/Http.md#-bookmust--use-http-methods-correctly) could be improved and needs some editing:

- In general: the guidance tries to summarise what HTTP specifies, but doesn't explain how to map methods to common concerns (such as creating a resource or updating). It's not optimised for people trying to solve problems. See [Google's guidelines](https://cloud.google.com/apis/design/standard_methods) for an alternate layout that works from common API needs to HTTP.

- GET. There's no need to say anything about 404 or collections. This section can be shortened.

- GET with Body. Should be a top level guideline. It comes up regularly and should be made easier to find in the guidelines for API designers. The "don't use headers for queries" statement should also be a top level guideline.

- POST. The post to collection pattern is described but could use some rewording.

- PATCH and updating. The wording should be rephrased to not have one approach per "endpoint" to having one approach per API, or at least trying to reduce the variability per API to make customers jobs easier.

**Comment by tfrauenstein** [comment]
@dehora As discussed, let us proceed like follows here:

a) Yes, an API developer use case oriented presentation could be helpful, abstracting, respectively referencing to HTTP and REST details. Typical use cases could be "c/r/u/d resource object", "retrieval from data collection", "batching" etc. Let us also evaluate #guild-api chat to identify most relevant use cases. I would propose additional top-level chapter for here -- it does not define guidelines, but helps applying the guidelines for specific use cases. Let us open in this sense a separate issue for further tracking. 

b) The other topics are more editorial -- partially already addressed by latest version. Let us create here a concrete PR to make progress and close this issue.

Thank you!

**Comment by ePaul** [comment]
**From the meeting**:

Closing this for now. @dehora Feel free to reopen when you have more detailed proposals.
