### ISSUE TITLE
Reduce guidance dependency on Nakadi project

### ISSUE THREAD

**Issue by dehora** [zalando/restful-api-guidelines#237]
The event models defined in the Nakadi project are required in the guidelines but the data models are currently managed in the Nakadi project. This is different to how common models like Money and Problems are handled.

The first step proposed is to reduce the number of references to the technology project without changing the basic guidance - this issue tracks that work. Follow on issues can look at inverting the dependency (eg having the data models embedded in the guidelines or a public web page) such that the Nakadi software project is informed by the guidelines rather than the other way around.

See #230

**Comment by tfrauenstein** [comment]
Guild meeting: let's close this issue -- all changes have been done; there is only one open issue as work in progress #265
