### ISSUE TITLE
Make Restful API Guidelines Mobile-Friendly

### ISSUE THREAD

**Issue by netme** [zalando/restful-api-guidelines#238]
Current API guidelines are not mobile friendly:

![photo_2017-05-23_14-19-44](https://cloud.githubusercontent.com/assets/96552/26354010/1e493f18-3fc3-11e7-84c6-3c39cb8ba4f3.jpg)

We need to find a solution to make it usable.

**Comment by ePaul** [comment]
While I doubt that many people are developing API's on mobile devices, you are right that it should be possible to read them there. Any proposals are welcome.

**Comment by duergner** [comment]
Would it be maybe already enough to have the menu collapsed by default on mobile?

**Comment by netme** [comment]
@duergner yes, that sounds like a plan

**Comment by maxim-tschumak** [comment]
I tried to insert a JS script which disables the `:navbar` via user local storage. To achieve this I included another gitbook plugin. Unfortunately, I didn't succeed to build the project (using 5.11 node version). 

If someone wants to try on his own, here is the patch:
```
diff --git a/book.json b/book.json
index ba5dac2..d709808 100644
--- a/book.json
+++ b/book.json
@@ -12,7 +12,8 @@
     "restructure-navigation",
     "anchors",
     "edit-link",
-    "-sharing"
+    "-sharing",
+    "addcssjs"
   ],
   "pluginsConfig": {
     "structured-toc": {},
@@ -26,6 +27,9 @@
     },
     "edit-link": {
       "base": "https://github.com/zalando/restful-api-guidelines/edit/master"
+    },
+    "addcssjs": {
+      "js": ["js/disable-sidebar-on-startup.js"]
     }
   }
 }
diff --git a/js/disable-sidebar-on-startup.js b/js/disable-sidebar-on-startup.js
new file mode 100644
index 0000000..af17485
--- /dev/null
+++ b/js/disable-sidebar-on-startup.js
@@ -0,0 +1 @@
+localStorage.setItem(':sidebar', false);
diff --git a/package.json b/package.json
index 3337842..93c4c4b 100644
--- a/package.json
+++ b/package.json
@@ -9,6 +9,7 @@
     "gitbook-plugin-include-codeblock": "1.8.2",
     "gitbook-plugin-structured-toc": "0.2.1",
     "gitbook-plugin-restructure-navigation": "0.1.0",
+    "gitbook-plugin-addcssjs2": "^1.0.0",
     "gh-pages": "0.12.0",
     "gitbook-plugin-edit-link": "2.0.2",
     "gitbook-plugin-anchors": "0.6.0"
```


I propose to migrate to Gitbook 3 (or 4, depends on when we are going to do the migration)

**Comment by ePaul** [comment]
Related: #231, #69, #10.

**Comment by maxim-tschumak** [comment]
With the new versions of the GitBook, this problem becomes obsolete. We will migrate to the newer version in #260.
