### ISSUE TITLE
Add comparison of different link standards

### ISSUE THREAD

**Issue by whiskeysierra** [zalando/restful-api-guidelines#24]
Right now the guidelines state:

> Should: Use Standards for Hypermedia Link Types
>
> To represent hypermedia links in payload results, we should consider using a standard format like HAL, JSON API, JSON-LD with Hydra, or Siren. (Hint: Read Kevin Sookocheff’s post, for instance, to learn more about the hypermedia types.)

We probably should not allow all link standards in the long term, since we are going for a consistent API look and feel. To move that discussion forward, maybe we could start adding a comparison of different standards.

**Comment by fmueller** [comment]
Good point. @zmeda already did a comparison of different HATEOAS implementations: http://zmeda.github.io/mc-hateoas-evaluation/#/ We can use this as starting point of our comparison.

**Comment by tfrauenstein** [comment]
Our plan was: 
step 1) restrict guideline to HAL and json:api for the time being. 
step 2) Align on Pros and Cons (based on separate doc, for the time being) <-- initial draft from Boris
step 3) Agree on some guideance update which one to be preferred (in which situation)

I propose to proceed like this -- step 1) immediately; step 2) @fmueller with Boris -- as input for next Guild JF
