### ISSUE TITLE
New Guideline: APIs should not support HTTP caching (because they are authenticated)

### ISSUE THREAD

**Issue by maxim-tschumak** [zalando/restful-api-guidelines#252]
Related to / triggered by #228.

Background: We have several X-headers which potentially influence the results of API calls. A naive cache could get confused by this if this is not taken into account.

**Comment by ePaul** [comment]
**From the meeting:**
By default no caching is supported. If client-side caching of a resource is allowed, it must be mentioned in the API definition (and then the proper Vary-headers must be set).
