### ISSUE TITLE
Possible to make pdf available

### ISSUE THREAD

**Issue by ehmkah** [zalando/restful-api-guidelines#259]
Would it be possible to make the guidelines as a pdf accesible? Or if that is already possible where do I find the pdf?

Yes I know its possible to create it locally, but I lost an hour and it is still not working. Would be realy cool?

**Comment by ePaul** [comment]
We previously had a PDF, but I think there were some problems with the generation ... therefore we got rid of it (because the HTML version is the authoritative version anyways).

**Comment by ehmkah** [comment]
OK. I don't know whether it helps but a single page html would be also a good solution. Just a file which can be sent directly to the printer.

**Comment by ePaul** [comment]
A single page PDF sounds nice. If you (or someone else) knows how to produce this (in addition to the multiple page one), this would be a welcome addition.

**Comment by fmueller** [comment]
Hi @ehmkah, I sent you a locally built PDF file to the email address I found on your Github profile.

Can you please give us detailed error message what did not work when you tried the steps described in out readme file to build it locally?

**Comment by ehmkah** [comment]
Maybe the reason was a wrong configured Mac OS X system. I installed nodeJS (npm 4.2.0) with homebrew. Than npm installs different packages all over the hard disk. 

I get the following error
```
    Error loading version latest: Error: Cannot find module 'internal/fs'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at evalmachine.<anonymous>:40:20
    at Object.<anonymous> (/Users/michi/.gitbook/versions/2.6.7/node_modules/graceful-fs/fs.js:11:1)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)

TypeError: Cannot read property 'commands' of null
```
During installation I get the error - do not know whether it was important
`Installing GitBook 2.6.7
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance`

Unfortunately, npm and javascript is not (yet) my default working environment. So it would be helpful to me to read which version of node and npm are required. This avoids updates which do not solve the problem

In the end, my solution was: install virtual box and run a fresh linux inside. Then everything worked as described by your documentation.

PS: Thank you for sending my the pdf via mail. That was great!

**Comment by fmueller** [comment]
I added a hint for node version, see #261, and we wanna upgrade to current Gitbook version soon, see #260.

As it is working for you and you received the PDF via email, I close this issue.
