### ISSUE TITLE
Migrate build process + markup to ASCIIdoc(tor)

### ISSUE THREAD

**Issue by maxim-tschumak** [zalando/restful-api-guidelines#260]
**As** maintainer, contributor, and user of the RESTful API Guidelines
**I want** the Guideline publishing process to be based on a maintained version of the used software
**So that** the build process is stable and we can make use of latest features and plugins

~~**As** maintainer, contributor, and user of the RESTful API Guidelines~~
~~**I want** the Guideline to be based on the latest stable GitBook version~~
~~**So that** the build process is stable and we can make use of latest features and plugins~~

Related issues: #231, #69, #10, #238.

**Comment by maxim-tschumak** [comment]
For the meeting on 2017-07-04: if nobody wants to do this - feel free to assign this one to me.

**Comment by mfellner** [comment]
These two gitbook plugins the project depends on are no longer available on github.com:

* gitbook-plugin-restructure-navigation
* gitbook-plugin-structured-toc

However they are still on npm: https://www.npmjs.com/~mostlymagic. I suggest recreating the GitHub repositories under a dedicated org and re-uploading future versions of those plugins under the `@zalando` namespace on npm.

**Comment by maxim-tschumak** [comment]
I tried to migrate to ASCIIDoc, here is the result:
* Source code: 
* HTML: https://maxim-tschumak.github.io/asciidoc-guidelines/
* PDF: https://maxim-tschumak.github.io/asciidoc-guidelines/index.pdf

All the features we use currently are supported. ASCIIDOC is more powerful and configurable.
We may also have a look at [Sphinx](http://www.sphinx-doc.org/en/stable/).

**Comment by whiskeysierra** [comment]
generated links look weird, but apart from that I like it

 > https://maxim-tschumak.github.io/asciidoc-guidelines/#__span_style_color_bf0000_strong_must_strong_span_propagate_proprietary_headers

**Comment by maxim-tschumak** [comment]
@whiskeysierra true. It's possible to set custom ids for the headers (and we should definitely do this if we decide to use asciidocs)

**Comment by whiskeysierra** [comment]
That's a neat feature since it allows to rename the headline without links to break.

**Comment by maxim-tschumak** [comment]
@whiskeysierra I've just set the custom ids - now we are SEO friendly :)

**Comment by tkrop** [comment]
@maxim-tschumak if links change, we have to change Zally too ...

**Comment by maxim-tschumak** [comment]
@tkrop Yes, but they will be stable for future changes - which is good :)

**Comment by ePaul** [comment]
I updated the initial comment + Issue title to reflect what we decided last meeting.

**Comment by ePaul** [comment]
Waiting until the current big PRs are merged, to avoid conflicts.

**Comment by maxim-tschumak** [comment]
During the migration, all the Rules will get an assigned ID as specified in this [internal document](https://docs.google.com/document/d/19A9n4q_JwjpFR3jLnyiHF09CQxQf0T04smPAO0Yvlyc/edit).
