### ISSUE TITLE
Section "13. Data Formats" contains contradictory requirements

### ISSUE THREAD

**Issue by PetrGlad** [zalando/restful-api-guidelines#262]
If this document strives to conform RFC 2119 as stated in "1. Introduction" section then these two requirements in "13. Data Formats" are mutually exclusive
* Must: Use JSON as the Body Payload
* May: Use other Media Types than JSON

I suggest merging it into single section "Should: Use JSON as the Body Payload" which would list considerations that migh allow to chose alternative formats.

Also "May: Use other Media Types than JSON" says "But only do this if you can not transfer the information in JSON." - which also can be improved. E.g. I can imagine that _any_ binary data can be Base64 encoded and put into JSON string.

**Comment by tkrop** [comment]
Yes, I think we have been aware of this contradiction, when we added the new section that allows to provide other contents, in hope it would express the requirement to provide resources in JSON as default. May be it is time to combine both sections to be more precise and not contradictory.

@PetrGlad Can you create a pull request with your suggested changes?

**Comment by PetrGlad** [comment]
OK, I'll make a PR
