### ISSUE TITLE
Property naming convention is incompatible with IANA link relations

### ISSUE THREAD

**Issue by whiskeysierra** [zalando/restful-api-guidelines#264]
Since the latest changes to hypertext controls there is an incompatible corner case with the following two guidelines: 
- [Property names must be snake_case (and never camelCase).](https://github.com/zalando/restful-api-guidelines/blob/master/json-guidelines/JsonGuidelines.md#-bookmust--property-names-must-be-snake_case-and-never-camelcase)
- [Use common hypertext controls](https://github.com/zalando/restful-api-guidelines/blob/master/hyper-media/Hypermedia.md#-bookmust--use-common-hypertext-controls)

> The name of an attribute holding such a HttpLink object specifies the relation between the object that contains the link and the linked resource. Implementations should use names from the IANA Link Relation Registry whenever appropriate.

All standard link relations use *hyphen-case*, e.g. [`version-history`](https://tools.ietf.org/html/rfc5829#page-4), which would yield:

```json
{
  "version-history": "http://localhost/revisions"
}
```

**Comment by tkrop** [comment]
@meshcalero can you prepare pull request with the not to translate the IANA link relation to snake_case? Would this be appropriate?

**Comment by meshcalero** [comment]
I would actually propose to convert them to snake-case, as hypen-case attribute names may lead in many programming language bindings to language specific name conversions or require quoted attribute names.

As the enforcement for IANA names is primarily about consistency across API, not so much about identiy to IANA names, a conversion to snake-case should not hurt.
