### ISSUE TITLE
Adding an optional property is a breaking change for PUT (for updating)

### ISSUE THREAD

**Issue by whiskeysierra** [zalando/restful-api-guidelines#266]
We always consider the addition of optional properties as a non-breaking change:

> Add only optional, never mandatory fields

> Ignore new and unknown fields in the payload

That doesn't work for `PUT`:

1. Server introduces new optional property
2. Client A updates the property to some meaningful value
3. Client B requests the resource but ignores the property since it's unknown to it
4. Client B modifies some other property using `PUT`, i.e. it replaces the resource
5. :boom: the property is now accidentally removed

An alternative would be to use `PATCH`, but that comes with a different problem, since removing by intention is not possible then (at least not with merge patch):

|                     | `PUT` | `PATCH` |
|---------------------|-------|---------|
| supports removal    | yes   | no      |
| remove accidentally | yes    | no     |

It would not be a problem if clients would send unknown fields back rather than ignoring them. That is usually harder to implement and also not demanded by the guidelines right now.

**Comment by AlexanderYastrebov** [comment]
> It would not be a problem if clients would send unknown fields back
but we can not rely on this and there is no way to distinct between intentional removal and accidental one

**Comment by tkrop** [comment]
@whiskeysierra good analysis. Just for curiosity: have you experience this problem in an actual failure case?

Anyhow, I like to ask, whether this is a problem at all?

As I see it, this is a problem when thinking of services as database wrappers. When thinking of resources as business processes, this situation will very likely not appear, because the update operation itself a business process creating a new resource.

In addition, the problem can only appear when a single resource is updated by more than one client. In my opinion, the default pattern is only client A is acting on resource with create and update, i.e. controlling the business process.

Anyway, how should we address this. I see the following options:

1. Warn about this issue in PUT?
2. Warn about this issue in the compatibility section?
3. Address this issue in the section about modeling business processes instead of creating database wrappers as additional warning why not to do this?

**Comment by AlexanderYastrebov** [comment]
@tkrop `when a single resource is updated by more than one client` is a precondition, yes.
I think the issue should be clearly outlined in Compatibility/Prefer Compatible Extensions section.

**Comment by whiskeysierra** [comment]
> When thinking of resources as business processes, this situation will very likely not appear, because the update operation itself a business process creating a new resource.

I don't get it. Can you elaborate?

> In addition, the problem can only appear when a single resource is updated by more than one client. In my opinion, the default pattern is only client A is acting on resource with create and update, i.e. controlling the business process.

I haven't seen an API yet that has a single consumer, tbh. But even then, if there are cases (and your use of *default* implies that), I'd say we should prepare for this. A common pattern that I see is that different clients act on different aspects of resources,

**Comment by tkrop** [comment]
>  A common pattern that I see is that different clients act on different aspects of resources.

@whiskeysierra but this is exactly what I meant. If you implement business processes, you do not act on resources, especially not on an optional property. You act by creating new resources, that creates a new business process (step), that changes the business process resource with the optional property in response.

It does not matter whether, this is done by one service or multiple, but having this perspective makes sure that their is always only one client actually changing a resource, i.e. the service handling the business processes around the resource or the business process itself. It ensures, that the business logic resides on the services exposing the business processes.

This is very different to the approach having a thin db-wrapper like API with properties that are changed by multiple consumer implementing the business process. If you do this, the business logic tends to be distributed over all consumers on multiple systems, as you describe for your the above problem use case.

I think this is an anti-pattern that should be prevented by modeling resources as business processes.  The lost property after update is only one the most common failure problems with it, I have seen breaking business processes multiple times. In my opinion, properties in business process resources should as good as never be change by a simple state change operation, which in best case only obscures the complexity of the related business process on the server.

**Comment by AlexanderYastrebov** [comment]
@tkrop We can not fix the world but we can raise an awareness of the issue and its appearance.

**Comment by tkrop** [comment]
> @tkrop We can not fix the world but we can raise an awareness of the issue and its appearance.

@AlexanderYastrebov I'm not suggesting this. But seems as the issue is part of a different problem.

**Comment by tfrauenstein** [comment]
Any concrete proposal, how we should change the guidelines as to address this problem?
What about the following proposal:

"Ignore new and unknown fields in the payload"    
--->
"Be prepared for new and unknown fields in the payload, 
i.e. ignore new field but don't eliminate it from payload used for subsequent PUT calls"

**Comment by duergner** [comment]
@tfrauenstein would be good but I think that's quite hard to actually achieve when implementing it.

I'm not aware of any JSON data binding library on the JVM space being able to do this.

**Comment by whiskeysierra** [comment]
Jackson can do it, using @JsonAnySetter.

On 18 Jul 2017 14:18, "Michael Duergner" <notifications@github.com> wrote:

@tfrauenstein <https://github.com/tfrauenstein> would be good but I think
that's quite hard to actually achieve when implementing it.

I'm not aware of any JSON data binding library on the JVM space being able
to do this.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/zalando/restful-api-guidelines/issues/266#issuecomment-316046436>,
or mute the thread

**Comment by tfrauenstein** [comment]
created PR #274
