### ISSUE TITLE
Consider to redesign common address attributes (salutation/first-name/last-name)

### ISSUE THREAD

**Issue by whiskeysierra** [zalando/restful-api-guidelines#269]
Based on discussions in #250

http://www.siliconglen.scot/usability/courtesytitles.html

It raises valid questions regarding:
- single name field, instead of splitting up first and last name
- free, single text field, instead of fixed set of salutations/titles
- deduce gender from title/salutation

**Comment by ePaul** [comment]
**From the meeting**:

Which (engineering or business) problem do we have to solve here?

@whiskeysierra Could you propose a way how the guideline should be changed to cover your concerns?

**Comment by whiskeysierra** [comment]
> Which (engineering or business) problem do we have to solve here?

I'd say it's a *social* one. 

1. There are many cultures that don't have the concept of first and last name.
2. Salutation, if used correctly, is just for addressing the user. Mostly in written form. This doesn't have to be a fixed set of values. I don't see a reason to put people into boxes. Let them choose their *title*.
3. Asking for gender feels really weird to me. In particular I believe to remember that it's even illegal to require it if it's not needed to do your business. I'd argue we don't need it. What I can imagine would be a preference for collections (women, men, gender). That does not necessarily correspond to my gender, since I can buy stuff for my daughter or wife.

Those are my personal opinions. Changing the guidelines to represent them implies that product/business is backing this.

**Comment by ePaul** [comment]
**From the meeting:** No immediate action identified.
