### ISSUE TITLE
API Discovery section should be clarified

### ISSUE THREAD

**Issue by PetrGlad** [zalando/restful-api-guidelines#275]
Since api-discovery projects were moved from github.com to our internal GHE
the link to https://github.com/zalando-incubator/api-discovery is now broken.
A side effect of this is that recommendation to use API Discovery endpoint `https://example.com/.well-known/schema-discovery` is now incomplete and missing any hints on required format and rules for `schema-discovery` resource.

I could not find recommendations for schema discovery in [OpenAPI spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md). Discovery does seem to be out of it's scope. Also RFC [Defining Well-Known Uniform Resource Identifiers (URIs)](https://tools.ietf.org/html/rfc5785) requires that all names below "/.well-known/" must be registered.
But [IANA registry](https://www.iana.org/assignments/well-known-uris/well-known-uris.xml) of such names does not list anything related to OpenAPI or Swagger.

The resolutions could be (not necessarily mutually exclusive) 
* Copy-paste the format details from internal project team-architecture/api-infrastructure (but still it should note that it is not a standard one).
* If this format is not an open specification but is used only at Zalando then we should remove this section or limit it to most generic recommendations.

**Comment by maxim-tschumak** [comment]
Thanks for your input @PetrGlad!

We are going to roll out a new API discovery process soon. The current solution relies on the `.well-known` schema discovery endpoint. That's why we don't want to touch this guideline so far. After the change in the discovery workflow, we will adjust the respected guideline.

I'm going to adjust the link to the `api-infrastructure` repository since it's broken.

**Comment by PetrGlad** [comment]
Also https://stackoverflow.com/questions/41660658/openapi-or-swagger-json-auto-discovery

**Comment by PetrGlad** [comment]
@maxim-tschumak It is a bad idea to refer internal project in open document. Therefore I did  not list that as possible resolution.

A good solution would be to register schema discovery name in IANA since all other users of OpenAPI spec would benefit from it.

**Comment by maxim-tschumak** [comment]
You are right @PetrGlad - I'm removing the internal link from the guideline and rephrasing the description.

I like your idea of registering the schema discovery name in IANA. Our future discovery solution will not rely on an additional endpoint though.

**Comment by PetrGlad** [comment]
A less intrusive recommendation could be to put declaration into `/openapi.json`

**Comment by dehora** [comment]
>Since api-discovery projects were moved from github.com to our internal GHE
the link to https://github.com/zalando-incubator/api-discovery is now broken... and missing any hints on required format and rules for schema-discovery resource.
>
>> The current solution relies on the .well-known schema discovery endpoint. That's why we don't want to touch this guideline so far. After the change in the discovery workflow, we will adjust the respected guideline.

@PetrGlad @maxim-tschumak In the meantime are the guidelines [here](http://zalando.github.io/restful-api-guidelines/api-operation/ApiOperation.html) broken? If they are, I don't think we can wait on a future undefined solution to fix them. Can we restore the linked project or inline the syntax into the guidelines?

**Comment by tkrop** [comment]
@dehora I think we can live with describing the process instead of linking to the source repository for now. @maxim-tschumak has prepared this in #276.

**Comment by ePaul** [comment]
Did #277 solve the problem of this issue, i.e. can this be closed?

**Comment by ePaul** [comment]
**From the meeting**: The "well-known registration issue is still open.
The API tooling team is considering a solution to replace this, until then this is waiting.
