### ISSUE TITLE
Should we have a limit of resources?

### ISSUE THREAD

**Issue by whiskeysierra** [zalando/restful-api-guidelines#28]
Right now we have two [sections](http://zalando.github.io/restful-api-guidelines/naming/Naming.html#should-limit-of-resources) in the guidelines about limiting the number of resource/sub-resources to an arbitrary limit:

> Should: Limit of Resources
>
>To keep maintenance manageable, and to avoid violations of the “separation of concern” principle, an API should not expose more than 16 resources. If you exceed 16 resources, first check if you can split them into separate subdomains with distinct APIs.
>
>Should: Limit of Sub-Resource Levels
>
>There are main resources (with root url paths) and sub-resources (or “nested” resources with non-root urls paths). Use sub-resources if their life cycle is (loosely) coupled to the main resource, i.e. the main resource works as collection resource of the subresource entities. You should use <= 3 sub-resource (nesting) levels -- more levels increase API complexity and url path length. (Remember, some popular web browsers do not support URLs of more than 2000 characters)

I agree with limits, but I'm not sure whether we can have something as concrete as *16* in there. I'd consider 5 to be a lot of resources already. But there might be valid excuses for it.

**Comment by tfrauenstein** [comment]
I think that we should keep the rule (btw: we merged it now, originally it was part of a bunch of 5 rules that I proposed and sent for review based on discussion with TUK guy, now some 6m ago). 

Yes, 16 is quite high and arbitrary -- but it is the upper limit and it is a should rule. 
I would like to have a hard upper limit -- perhaps 12 is a better choice? -- but would add before with certain emphasis that usually more than 4-6 resources is an indicator that functional isolation and separation of concern principle is violated.

**Comment by fmueller** [comment]
I would emphasize more on separation of concerns and single responsibility design patterns.

Nevertheless is an upper bound somehow necessary although it really depends on the context as usual. So, my proposal is: Adding more general guidance about proper design aspects (SoC and SRP) and leave the rule as it is.

**Comment by ePaul** [comment]
Parent-Issue: #41.

**Comment by tfrauenstein** [comment]
created PR  #71 without hard upper limit
