### ISSUE TITLE
Make hyperlinks in (and between) APIs more usable

### ISSUE THREAD

**Issue by ePaul** [zalando/restful-api-guidelines#294]
As discussed in our meeting today, we want to make links in APIs more easily usable by client developers.

We discussed two approaches:
* The runtime approach proposed by @andreasowczarek includes putting HTTP method, resource type, title, etc. in a hyperlink control object (beside the `href` property we already have).
* The design time approach proposed by me includes pointing in the schema definition which includes the hyperlink description to the resource (type) definition (= path item, in OpenAPI), so client developers always know what they can do with the link.

Maybe there could be some way of combining both without too much overhead.

**Comment by ePaul** [comment]
A while ago (during the development of OpenAPI 3.0) I made the proposal https://github.com/OAI/OpenAPI-Specification/issues/577, which basically allowed to add to an "interface" (which has mostly the same format as a path item, but without parameters) to a property with `type: string` and `format: uri`.

That proposal was not adopted in OpenAPI 3.0, but OpenAPI 3.0 now has a different way of specifying links (a [`links` property in a response](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#linkObject)). We should verify whether using this fulfills our needs (which might be a reason to drive the adoption of 3.0 forward), or whether this needs extensions to be useful.

**Comment by dehora** [comment]
> As discussed in our meeting today,

Others reading the guidelines won't necessarily know who "we" is.

> we want to make links in APIs more easily usable by client developers.

There are two approaches I know of - [html `<a>`](https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-a-element) and [atom `<link>`](https://tools.ietf.org/html/rfc4287#section-4.2.7).  My guess is @andreasowczarek's idea is akin to this with an additional "options" property to indicate the method. 

> OpenAPI 3.0 now has a different way of specifying links... We should verify whether using this fulfills our needs 

A pre-requisite is having a clear stance on v3 in the guidelines and what it means to work with two major versions of this spec, which will be the reality for end users for some time. 

The link object enables a very RPC style (`operationRef`). The last time I looked it's effectively the default design position (calling it link is somewhat confusing) and that will definitely (imo) impact tooling. I think Open API link's utility depends on what the guidelines are trying to make easy for developers. If it's to enable a style of approach like gRPC or Google Cloud's guidelines then it's pretty suitable for that. If it's a hypertext control, I suspect there's a bit of work to do, and may require the guidelines to recommend a profile of OAS link to veer away from implicit RPC.

**Comment by ePaul** [comment]
> Others reading the guidelines won't necessarily know who "we" is.

You are right. I'm wondering of how we (Zalando's API Guild aka the maintainers of this repository) can make it more visible to outside observers/contributors that we have bi-weekly Zalando-internal meetings where these issues are discussed (beside other topics).

I would say we should try to lay down the important arguments here in comments to issues, though sometimes we also have internal reasons which can't be shown in public.

**Comment by ePaul** [comment]
> There are two approaches I know of - [html `<a>`](https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-a-element) and [atom `<link>`](https://tools.ietf.org/html/rfc4287#section-4.2.7).  My guess is @andreasowczarek's idea is akin to this with an additional property to indicate the method (akin to the "options" header). 

You (as an employee of Zalando and member of the API guild) can look at our Rolling Agenda document, @andreasowczarek' presentation is linked from there.

We already have the `href` property for links in [Rule #164](http://zalando.github.io/restful-api-guidelines/#164), @andreasowczarek's proposal is to add some more (optional) attributes to allow clients *at runtime* to know what to do with a link. (`method`, `type`, `accept`, `auth`, `title`).

**Comment by dehora** [comment]
>  I'm wondering of how we... can make it more visible
> 
> You (as an employee of Zalando and member of the API guild) can look at our Rolling Agenda document, @andreasowczarek' presentation is linked from there.

One suggestion would be to make significant design improvements and proposals like this public.

**Comment by ePaul** [comment]
**From the meeting**

We are closing this for now, as we don't see an urgent need right now. Can be reopened when the need arises.
