### ISSUE TITLE
Host Must Not Contain Protocol

### ISSUE THREAD

**Issue by maxim-tschumak** [zalando/restful-api-guidelines#295]
`host` property in the root of the Open API definition must not contain protocol.
There is already a Zally [check](https://github.com/zalando-incubator/zally/blob/master/server/src/main/java/de/zalando/zally/rule/NoProtocolInHostRule.kt) for this rule().

What do you think about including this rule into the Guidelines under [API Naming](http://zalando.github.io/restful-api-guidelines/#api-naming) chapter?

**Comment by whiskeysierra** [comment]
I'd say this is covered:

>The host (name or ip) serving the API. This MUST be the host only and does not include the scheme nor sub-paths. It MAY include a port. If the host is not included, the host serving the documentation is to be used (including the port). The host does not support path templating.
>
> [OpenAPI](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#fixed-fields)

**Comment by maxim-tschumak** [comment]
@whiskeysierra You are right! Thanks for the research.
@tfrauenstein This is a good example of a "rule" which is not part of our Guidelines, but still a good candidate for a Zally check.
