### ISSUE TITLE
Proper usage of OpenAPI schema definitions

### ISSUE THREAD

**Issue by maxim-tschumak** [zalando/restful-api-guidelines#296]
We should address and motivate proper usage of `Definitions` feature of OpenAPI.

There are different aspects:
- API designer should use `Definitions` (instead of embedding a model)
  - For better readability (e.g. in Swagger UI)
  - For re-usage
  - Consistency over all our APIs
- API designer must avoid unused Definitions in the specification
  - Artefacts if automatic code generation is used (provider and consumer)
  - Source of irritation for (potential) API consumer
  - [Zally Check](https://github.com/zalando-incubator/zally/blob/master/server/src/main/java/de/zalando/zally/rule/NoUnusedDefinitionsRule.kt) is already implemented

What do you think? Should we address any other aspects?

**Comment by whiskeysierra** [comment]
> API designer should use Definitions (instead of embedding a model)

I wouldn't be so black and white here. There are benefits to embedding.

> For better readability (e.g. in Swagger UI)

Highly subjective. Constantly switching between definitions and operations doesn't help with readability either. It's like having constants for every single literal in the code even if it's used only once. More often than not, inlining a response actually helps the flow when reading from top to bottom.

> For re-usage

That should be the obvious reason for when to switch from embedding to definition. Re-use always has the risk of introducing coupling of two or more aspects that may have been better off as separate things with their own evolution. Somethings it's coincidence that two definitions are the same and they can't diverge later if somebody merged them into one. It's obviously not always the case, but it's a risk that API designers/maintainers should be aware of.

**Comment by maxim-tschumak** [comment]
Thanks for your input @whiskeysierra 

> > API designer should use Definitions (instead of embedding a model)

>I wouldn't be so black and white here. There are benefits to embedding.

Maybe a "MAY" rule/guidance.

> > For better readability (e.g. in Swagger UI)

> Highly subjective. Constantly switching between definitions and operations doesn't help with readability either. It's like having constants for every single literal in the code even if it's used only once. More often than not, inlining a response actually helps the flow when reading from top to bottom.

After Swagger UI parsed the API spec it shows all Definitions on the top level (not within the endpoint specs). It may be very useful for potential consumers - "which resources are part of the API".

> Re-usage

I agree with you

**Comment by tkrop** [comment]
**From Meeting**:
* different opinions in guild about how restrictive rules should be and what readability is
* argumentation is not strong enough, need additional reasoning

**Comment by ePaul** [comment]
**From the guild meeting:**

We currently don't see enough motivation for this.
Feel free to reopen if we get more arguments.

**Comment by maxim-tschumak** [comment]
OK, In order to keep Zally consistent to API Guidelines, I've created a [PR](https://github.com/zalando-incubator/zally/pull/568) to deactivate related rule.
