### ISSUE TITLE
Various HTTP Header related inconsistencies

### ISSUE THREAD

**Issue by meshcalero** [zalando/restful-api-guidelines#297]
Rule 133 "Use standardized Headers" doesn't really fit to main section "API Naming". 

I would suggest to incorporate the text into the intro of main section "14. Common Headers" or move the whole rule there. Maybe we want to link to section [14] and [15] from [132].

It is also questionable if we need a rule "Use Hyphenated HTTP Headers" [131] at all, as section "15. Proprietary Headers" restricts proprietary headers to a well defined set, and those have hyphenated names.

**Comment by ePaul** [comment]
*From the meeting*

* Sounds good. Could you open a pull-request with those changes?

**Comment by maxim-tschumak** [comment]
Agree with the first two paragraphs (and preparing a PR..).

> It is also questionable if we need a rule "Use Hyphenated HTTP Headers" [131] at all, as section "15. Proprietary Headers" restricts proprietary headers to a well defined set, and those have hyphenated names.

I wouldn't remove [131]: 
- [131] and [132] belong together
- [131] is not stated explicitly elsewhere
- There is an automated Zally check for this guideline (incl. some historical information about the violations)

What do you think?

**Comment by maxim-tschumak** [comment]
Zally issue has been created: https://github.com/zalando-incubator/zally/issues/591

**Comment by ePaul** [comment]
@meshcalero do the changes made in #317 fix the issue from your point of view?

**Comment by meshcalero** [comment]
@ePaul Looks good for me. Closing as #317 has been merged already
