### ISSUE TITLE
Add guideline for optimistic locking in REST APIs

### ISSUE THREAD

**Issue by tkrop** [zalando/restful-api-guidelines#301]
After a discussion in the guild chat participants suggested to add a best practice section for optimistic locking to the guidelines. As good starting point the following [internal documentation about different options](https://techwiki.zalando.net/display/DT/Optimistic+Locking+in+REST) was suggested:

* Option 1: Last-Modified / If-Unmodified-Since
* Option 2: Hardcore REST with only URLs in list requests
* Option 3: ETags in result entities of list requests
* Option 4: Version numbers in result entities of list requests

**Comment by matterche** [comment]
As we already discussed this topic internally at least twice and find more teams being interested in existing approaches I would definitely support the creation of a corresponding section in the guidelines.

**Comment by ePaul** [comment]
*From the meeting*
* new appendix "best practices"
* links from relevant sections
* list all options apart from two, with pro/con.
* help wanted.

**Comment by matterche** [comment]
I would be happy to help. Will approach @ePaul offline :)

**Comment by matterche** [comment]
- [ ] Add new appendix "best practices"
- [ ] List all options with pro/con.
- [ ] Add links from relevant sections
- [ ] Extend changelog

**Comment by matterche** [comment]
Opened a pull request: #330 Please could someone have a look?
