### ISSUE TITLE
PDF guide has lost cover page

### ISSUE THREAD

**Issue by darrenr** [zalando/restful-api-guidelines#305]
I noticed in the latest version (last 3 days) your PDF version lost the cover page. I suspect this is due to  a change / bug in the asciidoctor docker container.

**Comment by tkrop** [comment]
Confirmed this bug in a local build.

**Comment by tkrop** [comment]
Unfortunately, this is a current aciidoctor-pdf limitation (see [issue 233](https://github.com/asciidoctor/asciidoctor-pdf/issues/233)).
