### ISSUE TITLE
Guideline on API Version Number is Impractical for Reviews

### ISSUE THREAD

**Issue by tkrop** [zalando/restful-api-guidelines#310]
The current guideline for API version numbers is impractical for the review process. It requires API writers to update the minor or major version after the review has been done, while changing the "review" number on each request (see [rule 116](https://zalando.github.io/restful-api-guidelines/#116)).

This results in the problem that a reviewer cannot review the version number as it will be only changed afterwards. This results in more errors of releasing API with incorrect versions. Today most reviews are using GH/GHE which provide a commit hash for distinguishing reviewed API versions. In addition, this rule is hardly unknown or in consequences is unexpected, so that it is mostly not applied correctly.

I suggest to change the rule to standard semantic versioning, which is the most expected and formally already used process for API versioning.

**Comment by ePaul** [comment]
**From the meeting**:

- Experience shows that the draft versions were never really used.
- We can track changes during review via the pull requests
- patch versions are potentially useful for editorial changes (typo fixes)

Therefore we want to use semantic versioning, with
- patch = editorial changes (updating is not enforced)
- minor = compatible changes with additional functionality
- major = incompatible changes (only allowed after alignment with consumers)

@tkrop drafts the rule change.
