### ISSUE TITLE
Check Options for Zalando's Tech Principles

### ISSUE THREAD

**Issue by tkrop** [zalando/restful-api-guidelines#319]
[Zalando' Tech Principles](https://github.bus.zalan.do/team-architecture/zalando-tech-principles) have been moved out of the public domain when we changed our Open Source Strategy. We now need to check the options for to provide public access again.

**Comment by hjacobs** [comment]
I would like to have the Zalando Tech Principles somewhere online again (in Zalando scope) :smile:, in the meantime I still keep the read-only archived repo around: https://github.com/hjacobs/zalando-tech-principles.

**Comment by tfrauenstein** [comment]
Yes, @tlossen is currently checking option to move it to Zalando OSS.

**Comment by ePaul** [comment]
@hjacobs thanks, in #309 the link was changed to point to your fork, this is how we noticed this.

**Comment by tlossen** [comment]
this is the new home: https://github.com/zalando/engineering-principles (currently still private)
