### ISSUE TITLE
Rule #150 incorrectly references discussion of 207 for rate limiting

### ISSUE THREAD

**Issue by conorclifford** [zalando/restful-api-guidelines#323]
The [rule 150](http://zalando.github.io/restful-api-guidelines/#150), in particular, when discussing the `429` response code, contains the following:

> Too many requests - the client does not consider rate limiting and sent too many requests. See Must: [Use 207 for Batch or Bulk Requests](http://zalando.github.io/restful-api-guidelines/#152).

This incorrectly links to http://zalando.github.io/restful-api-guidelines/#152 where it should actually link to http://zalando.github.io/restful-api-guidelines/#153, which is "Must: Use 429 with Headers for Rate Limits [153]"

**Comment by ePaul** [comment]
Thanks for noting. We found already quite some of those off-by-one wrong links, which were likely caused by the migration to AsciiDoc (in #282), maybe we should systematically check all of them.
