### ISSUE TITLE
Use Specific HTTP Status Codes [150] Denies PATCH -> 204

### ISSUE THREAD

**Issue by roxspring** [zalando/restful-api-guidelines#341]
Rule 150 to use specific HTTP status codes seems to suggest that the only successful PATCH responses are:
* 202 Accepted (implies asynchronous, change may or may not happen in the future)
* 200 OK (implies synchronous completion, suggests some content will follow)

But it that leaves a seemingly obvious cases unsupported: 
* 204 No Content (implies synchronous completion, but nothing further to say)

Any reason not to allow 204 responses to a PATCH?

**Comment by tkrop** [comment]
@roxspring this seems to be a valid request. I would use `PATCH` with `204` as a standard synchronous response. `205`, which we even do not have in the list may be necessary, if applying a patch has consequences the patcher could not have anticipated. But `204` seems for me a valid request. 

Does anyone remember why it is not in the list?

**Comment by whiskeysierra** [comment]
Accepted is 202. 204 is No Content.

**Comment by roxspring** [comment]
Thanks @whiskeysierra. Had to re-read several times before I could see the typo you were pointing out.

Corrected in original comment, request to allow 204 No Content still stands.

**Comment by tkrop** [comment]
From guild meeting: want to extend methods with PATCH.

**Comment by tkrop** [comment]
@roxspring can you create the PR?

**Comment by roxspring** [comment]
No time today but should be able to open a PR here and on Zally later in the week.
