### ISSUE TITLE
Consider adding a section about recommended "API-First" (OpenAPI/Swagger) tools

### ISSUE THREAD

**Issue by hjacobs** [zalando/restful-api-guidelines#35]
I think we should consider linking our recommended OpenAPI tools in the RESTful API guidelines:

* https://github.com/zalando/connexion
* https://github.com/zalando-stups/friboo
* https://github.com/zalando/play-swagger

(and others)

Obviously this would somewhat duplicate what is listed on the [Swagger Open Source Integrations page](http://swagger.io/open-source-integrations/), but IMHO a curated list in our guidelines has extra value as we already know which tools do not properly work and we specifically want API-first.

**Comment by hjacobs** [comment]
This section would also be really handy for people to link to (answering a "support" question), we are maintaining a similar list for STUPS OAuth integrations (http://docs.stups.io/en/latest/appendix/oauth-integrations.html).

**Comment by ePaul** [comment]
I guess swagger-codegen (+ our own swagger-codegen-tooling) also belong in such a list.

**Comment by hjacobs** [comment]
@ePaul sure, my list was not exhaustive.

**Comment by fmueller** [comment]
Can you prepare a pr with the suggested tooling section @hjacobs?

**Comment by hjacobs** [comment]
@fmueller sure, just wanted to check first whether others find that useful as well :smile:

**Comment by tfrauenstein** [comment]
I like the initiative for recommended OpenAPI tools section.
However, I think we should continue to update the corresponding section in the "API Practises" Doc https://docs.google.com/document/d/1Dqgkfxm2Jt9mVSraOYWSfKq3cKaZwf_VOgYDRuUf7kI/edit#heading=h.i7nw1hn4w2ox
Would prefer to keep API Design Guideline separated from Tooling and Implementation Practises.

**Comment by fmueller** [comment]
@tfrauenstein I'd like to see it as some sort of a reference section where we just propose some tools to implement our guidelines - also for public audience. The internal document is not usable for Non-Zalandos. This does not mean that we should drop the internal 'API Practices' doc.

**Comment by tfrauenstein** [comment]
@fmueller we can do it -- but I would avoid unclear scopes and consistently maintaining redundancies.
We have the "Practises Doc" with corresponding chapter and it is no. 1 choice of teams to get infos on implementation practices. I don't see here prio to also share tooling and implementation practises with the rest of the world.

**Comment by fmueller** [comment]
My suggestion is, adding an internal link to our guidelines so that teams can find best practices and implementation hints when reading our guidelines. Furthermore, due our guidelines also have public audience I'd add a section with public tool links.

@hjacobs Your view on this?

**Comment by whiskeysierra** [comment]
> Furthermore, due our guidelines also have public audience I'd add a section with public tool links.

I agree. Adding a link from a rule to an open source (reference) implementation makes sense. Maybe even the other way around, i.e. having a link from our projects to the rules. It's a nice way to promote our guidelines as well as our open source projects.

This applies to

- json-fields: Filter filtering
- problem, problem-spring-web, friboo, connexion: Problem types
- twintip, twintip-spring-web: Schema discovery
- jackson-datatype-money: Money
- tracer: Flow-ID
- riptide, jackson-module-unknown-property: resilient clients

Am I missing something? @hjacobs @jmcs
