### ISSUE TITLE
Should collections consume 2 resources in "Limit number of Resources [146]"?

### ISSUE THREAD

**Issue by roxspring** [zalando/restful-api-guidelines#356]
Currently the Zally implementation literally counts the number of path entries in the swagger file and ensures that this number is below some configured paths_count_limit (currently 8). This has the effect that any collection of `things` instantly burns up two of the allowed paths `/things` and `/things/{id}` - is that the intention of this guideline?

In my team we were considering a variation where we just put a limit on the count of top-level resources i.e. `/things`, `/things/{id}`, `/things/{id}/related-thing/` all count as a single top-level resource, where `/extra/`, `/extra/stuff/` would count as a second top-level resource. It occurred to me that this might have been the original intention of the rule?

**Comment by maxim-tschumak** [comment]
Good catch! The rule implementation is incorrect. It's not about the number of paths.

The current guideline rule is imprecise and doesn't tell us if we should check top-level resources only or all resources. (It's probably meant to be not too precise)

I believe it makes sense to count top-level resources only. Just in order to be not too strict.

**Comment by maxim-tschumak** [comment]
@ePaul @tkrop @mfellner please have a look

**Comment by ePaul** [comment]
For the reference, those numbers came in in issue #28 (PR #71) (previously it said 16, with a harder wording, which was already in there before we started version control on the guidelines). (@tfrauenstein and @whiskeysierra were involved back then, too.)

There was no mention of "only count top-level" in the discussion, and I would read it as counting all resources (including "sub-resources", i.e. resources whose names contain one or more slashes). However, I can understand that others read it differently.

However we decide, we should certainly clarify the wording in the rules here.

(Actually, I think the name "resource" here is wrong, as e.g. `/orders/{id}` is not one resource, but an unlimited family of resources, one for each value of the parameter: `/orders/1`, `/orders/2`, `/orders/3`, ... We don't want to count each of this.)

**Comment by roxspring** [comment]
Just to make sure I understand your suggestion @tkrop, the following would all relate to a single type of resource:
```
GET /customers
POST /customers
GET /customers/{id}
POST /customers/{id}/some-customer-focused-action
```
Whereas the following would be a second resource:
```
GET /addresses
POST /addresses
GET /addresses/{id}
```
Sub-resources are a little unclear but you'd be happy with a Zally rule interpreting these as a third resource:
```
GET /customers/{id}/addresses
GET /customers/{id}/addresses/{addr}
```

I like this interpretation. It's much more generous than the current Zally implementation (which I think would have counted 7 resources in my examples), and less arbitrary than just counting top-level entries. Selfishly, it's also more useful to our team than the top-level interpretation as we have a number of microservices who's paths _all_ relate to some shared resource and therefore have a single top-level prefix `/shared-resource/{id}/`

Again, if there's consensus I'm happy to implement the Zally fix, but still wonder whether the guideline would benefit from some clarification and/or examples.

**Comment by tkrop** [comment]
@roxspring now you have exposed the real difficult part of the question. If a resource is exposed via two different paths, I would like to count this as one - but I know this could be very difficult to calculate. Consequently,

```
GET /customers/{id}/addresses
GET /customers/{id}/addresses/{addr}

GET /addresses
POST /addresses
GET /addresses/{id}
```
should all be counted as one address, *iff* the resources of the list respectively single resource endpoints are the same. However, I'm not sure whether this an often see pattern.

**Comment by tkrop** [comment]
@roxspring @maxim-tschumak @ePaul should we update the rule to clarify such an interpretation?

**Comment by tfrauenstein** [comment]
Yes agreed, we should update the rule to be more precise. 
1) /resource and /resource/{id} is counted as one resource (delivered as collection or instance).
Perhaps we should use consistently the term 'resource type' here.
2) Limit 'number of resources' includes top- and sub-resource types. 
3) For definition and checking simplicity reasons, I suggest to count a resource type exposed as top-level and as sub-level resource twice. This design is not often applied and quite exotic.
3) Of course, a resource typically is exposed via multiple endpoints (http methods)

**Comment by ePaul** [comment]
@roxspring do you want to propose a pull-request along the lines described by @tfrauenstein?

**Comment by roxspring** [comment]
Didn't get time last night, will aim to have a PR opened by Friday.

**Comment by roxspring** [comment]
PR #361 opened.

I chose to use the term "resource family" for grouping related resources since "type" is too strongly associated with json schemas and produces/consumes media types in this context. Hope that's ok.
