### ISSUE TITLE
API-id must be provided

### ISSUE THREAD

**Issue by tfrauenstein** [zalando/restful-api-guidelines#371]
We should change rule #215 from "should" to "must" ( see http://zalando.github.io/restful-api-guidelines/index.html#215 ).

The API id is crucial to identify APIs throughout their life cycle; it is required, for instance, to support API Review tracking, API Linter tracking, API History via Portal consistently over the API change evolution, and is a crucial metadata for our API management procedures.

And the API-title is not an equivalent substitute for API-id since it eventually gets updated.

**Comment by whiskeysierra** [comment]
What about existing APIs?

**Comment by tfrauenstein** [comment]
Of course, as always we are backward compatible:
Existing APIs don't have the api-id. Correspondingly, API management and tooling may not provide full consistent feature support for these APIs; and these APIs will be red-flagged in the portal. 
Of course, API-ids can be added to existing APIs without loosing API History, Review Tracking etc. as long as the API-title is not simultaneously changed. 

Yes, when we update the rule, we should say something about backward compatibility and migration path.

**Comment by tkrop** [comment]
We already say in the [introduction](http://zalando.github.io/restful-api-guidelines/#zalando-specific-information):


<i>In case guidelines are changing, following rules apply:
* existing APIs don’t have to be changed, but we recommend it
* clients of existing APIs have to cope with these APIs based on outdated rules
* new APIs have to respect the current guidelines
</i>

Isn't this enough to cover the backward compatibility aspect?
