### ISSUE TITLE
Document `Retry-After` with 503

### ISSUE THREAD

**Issue by ioggstream** [zalando/restful-api-guidelines#377]
## I suggest

  - a rule to  explicit the usage of `Retry-After` header when 503

## Feedback welcome ;)

**Comment by whiskeysierra** [comment]
Isn't the RFC already specific enough?

> Servers send the "Retry-After" header field to indicate how long the
   user agent ought to wait before making a follow-up request.  When
   sent with a 503 (Service Unavailable) response, Retry-After indicates
   how long the service is expected to be unavailable to the client.
>
> https://tools.ietf.org/html/rfc7231#section-7.1.3

**Comment by ioggstream** [comment]
iiuc:

  - https://tools.ietf.org/html/rfc7231#section-6.6.4 503 MAY Retry-After

let me know,
R.

**Comment by ioggstream** [comment]
Hi @tkrop and thanks for your reply!

I think the scenario is quite similar to the 429 and X-RateLimit: you tell client to back-off.

In both cases the reply and/or the header could be set by the api-gateway or another front-end component which is aware of the problem (eg. too many "runnable" requests, ...)

imho as for the 429, the clients must get and honor a Retry-After.

**Comment by tkrop** [comment]
@ioggstream Sorry for the late response. You did not get my point:

Writing this as advice into the guideline will create effort in API, service, and client design, that does not pay off. Most responses will still not carry this information, even if you force your service to do so. So it does not make sense to enforce it this way.

What would be interesting is a client advice to honor 503 with a retry that respects the `Retry-After` header. Unfortunately, our guidelines are for practical reasons are focused on API design - neither service nor client design -, which makes it currently difficult to argue or find a place for such a rule.

**Comment by tkrop** [comment]
@ioggstream 

> * the https://opensource.zalando.com/restful-api-guidelines/#153 seem focused on service design

Good observation. We do this sometimes, because API design sometimes effects service design.

> Do you have other (public) guidelines for service design, resiliency & co?

No we thought about this multiple times, but always felt that our API Guild and the Guideline is not the right place to start such an initiative. It is related, but other Zalando's have a participate here.

**Comment by ePaul** [comment]
**From the meeting**:

One option would be to just add a short sentence with link to the HTTP status table entry for 503. This does not force anyone to implement it, but suggests it.
