### ISSUE TITLE
Clarification on x-api-id

### ISSUE THREAD

**Issue by dehora** [zalando/restful-api-guidelines#378]
> [Should: Provide API Identifiers [215]]( http://zalando.github.io/restful-api-guidelines/#215)

In the guidelines, it's not clear what `x-api-id` denotes, ie, whether it denotes the API definition, an instance of the API accessible to users, or something else. 

As an example, the Nakadi project defines its API with the original intent it could be run by multiple teams. Should each accessible instance of the API have an `x-api-id`, or should there be a single one for the API specification? 

This may also have implications for tooling like portals that are relying on the `x-api-id` as a lookup key and for elements of the definition, like scopes.

**Comment by maxim-tschumak** [comment]
@dehore I agree with you, we should make it clear in the guidelines.

We use OpenAPI standard to provide **interface** specification. There could be multiple **implementations** of this interface (different instances, services, etc.). A good internal example are [`lizzy`](https://github.com/zalando-stups/lizzy) installations within Zalando. There are 50+ deployments of the same API. Callback endpoints are also good candidates to have the same API specification (e.g. SNS interface).

**Comment by tkrop** [comment]
I like to cite a main rule from our linked [API Identifier proposal](https://docs.google.com/document/d/1lRXcTZbZMnFeTVCaazitSWxSdKXGWkOUn99Gr-huNXg):

> The owner of the API has to ensure that the API identifier is applied consistently to any API specification version describing the same API - across multiple applications as well as compatible and incompatible changes - to ensure that the API history reflects all related deployments and channels as long as the same consumers are expected to consume the API.

More details how to apply the API identifier can found in the [FAQ section](https://docs.google.com/document/d/1lRXcTZbZMnFeTVCaazitSWxSdKXGWkOUn99Gr-huNXg/edit#heading=h.fbnt9hzhgsl2).

@dehora When I was writing the API Guideline rule, the decision was not to include to many details into the rule - to prevent information overload -, but to refer to the proposal for more information. Do you think we need to reconsider this approach and give more details in the rule itself?
