### ISSUE TITLE
X-RateLimit-Reset incompatible with Github

### ISSUE THREAD

**Issue by whiskeysierra** [zalando/restful-api-guidelines#379]
[Rule 153: ](http://zalando.github.io/restful-api-guidelines/#153) defines three headers for rate limiting (apart from `Retry-After`):
- X-RateLimit-Limit
- X-RateLimit-Remaining
- X-RateLimit-Reset

I believe they are borrowed from Github's API, but they differ in how they interpret the `X-RateLimit-Reset` header:

> The time at which the current rate limit window resets in **UTC epoch seconds**.
>
> https://developer.github.com/v3/#rate-limiting

> The relative time in **seconds** when the rate limit window will be reset.
>
> http://zalando.github.io/restful-api-guidelines/#153

Github does define an example:

```http
HTTP/1.1 200 OK
Date: Mon, 01 Jul 2013 17:27:06 GMT
Status: 200 OK
X-RateLimit-Limit: 60
X-RateLimit-Remaining: 56
X-RateLimit-Reset: 1372700873
```

Zalando doesn't define an example in the guidelines, but I'd expect this:
```http
HTTP/1.1 200 OK
Date: Mon, 01 Jul 2013 17:27:06 GMT
Status: 200 OK
X-RateLimit-Limit: 60
X-RateLimit-Remaining: 56
X-RateLimit-Reset: 2513
```

Is it intentional that we differ from Github here?

**Comment by whiskeysierra** [comment]
Other Companies/APIs that use the same approach as Github:

- [Twitter](https://developer.twitter.com/en/docs/basics/rate-limiting) (note additional `-` in `Rate-Limit`)
- [Vimeo](https://developer.vimeo.com/guidelines/rate-limiting)
- [Hipchat](https://developer.atlassian.com/server/hipchat/hipchat-rest-api-rate-limits/)

I found some that use relative seconds, but none of the big players.

**Comment by whiskeysierra** [comment]
[Reddit](https://github.com/reddit-archive/reddit/wiki/API) seems to use seconds.

**Comment by tkrop** [comment]
Good point and good investigation.

@whiskeysierra Wasn't it you writing the initial rule ;).

I think we should discuss this in the next guild meeting. Having a difference to a common understanding is a problem, but changing the rule isn't optimal too.

**Comment by whiskeysierra** [comment]
Nope, not that I know of.

**Comment by ioggstream** [comment]
I prefer to stick with the current implementation:

  - The current implementation follows the same specs of Retry-After;
  - X-RateLimit-Reset and Retry-After are better to be aligned;
  
imho

  -  `X-RateLimit-Reset: 1372700873` is potentially broken because it relies on client-server ntp synchronization and on jitter added to the date by the server 
  -  in my spec I advertise the server to only expose seconds, the client to support both (seconds and unix timestamp)

**Comment by ioggstream** [comment]
@whiskeysierra @tkrop I'm preparing a draft RFC proposal on throttling headers,
using the same semantic provided here.

- https://github.com/ioggstream/draft-polli-ratelimit-headers
- https://ioggstream.github.io/draft-polli-ratelimit-headers/draft-polli-ratelimit-headers.html

Are you interested in contributing?

**Comment by whiskeysierra** [comment]
Answered on twitter: https://twitter.com/whiskeysierra84/status/1151464580855599104
