### ISSUE TITLE
Rule 144 contains questionable advice

### ISSUE THREAD

**Issue by whiskeysierra** [zalando/restful-api-guidelines#383]
[Rule 144: Should: Only Use UUIDs If Necessary](https://opensource.zalando.com/restful-api-guidelines/#144) currently lists the following as a negative aspect:

> not ordered along their creation history and no indication of used id volume

I'd argue that this can and has been a downside for us in the past. Having a sequence that increases monotonically without gaps is not desirable in most cases, since it allows someone from the outside to regularly measure velocity and derive some insights that wouldn't otherwise be possible.

**Comment by tkrop** [comment]
@whiskeysierra this is surely a considerable aspect that public exposed IDs, that are able to transport information about our business success, should be designed carefully with respect to such considerations. A random value (e.g. a UUID) can be a solution here beside others.

As these public exposed IDs are an exception, I would still argue, that our should rule as well as the argumentation is reasonable. Especially, the ordering along the creation history is an often favorable behavior in company internal APIs.

**Comment by whiskeysierra** [comment]
> As these public exposed IDs are an exception

Doesn't that imply that we always need to translate IDs of this kind to some external format and back?
