### ISSUE TITLE
Separate public guidelines and Zalando-internal concerns

### ISSUE THREAD

**Issue by ePaul** [zalando/restful-api-guidelines#394]
Currently our guidelines are represented as "guidelines everyone can adopt", while at the same time they contain many Zalando-specific issues, and even internal links at several places.

Similarly, the evolving of those guidelines happens in a semi-open-source model: All changes have pull-requests here in Github, but at the same time we discuss them internally in our bi-weekly API Guild meetings which are only accessible to Zalando employees.

The guidelines are also used as a base in some other Zalando Open-Source projects (e.g. [Nakadi](https://github.com/zalando/nakadi/)).

Reusing those guidelines elsewhere is currently difficult, though there are [142 forks](https://github.com/zalando/restful-api-guidelines/network/members), of which at least some have edited the guidelines substantially to adapt them to their uses.

Can we make this reuse easier by separating Zalando-specific parts out? Or have them separately in the code, but somehow merged together for the viewed version?

**Comment by tkrop** [comment]
I think, we could allow external collaborators to join the meeting. We need just announce it a bit more.

Regarding the question to separating internal information: I see an advantage of keeping the guideline easy applicable for us. Having a separate internal guideline application document makes it much more difficult. At the moment I would vote against it.

**Comment by ddufourboivin-zalando** [comment]
I've started reading through the rules and had the same though as @ePaul . 

Maybe, without removing the internal links completely, we could visually split them. A frame and/or an Icon (tiny Zalando logo) pointing out to Zalando employees that there is extra information just for them there.

OR

We could have an internal document with the Zalando-only additions to those rules and the open-source document very quickly links to specific sections of that document, yielding only a few "Zalando employees, read further here" with a link to that document. That would minimise the Z-related content in the OSS version.

**Comment by tkrop** [comment]
Zalando employee boxes sounds like a nice approach, but this would even emphasize this more.

**Comment by ddufourboivin-zalando** [comment]
But having a more obvious visual about it also allo non-Zalandos to skip it more easily.

> This colour or design? Don't even read it.

**Comment by ddufourboivin-zalando** [comment]
I understand your point and agree.

👍 It's a lot cleaner and more open-source-friendly if there are none.
👎 It means 2 distincts documents to read and some effort to "synchronise the reading" between them.

The 👍however overweight the 👎 here in my opinion since this **is** an open source project and the OSF-Factor (_Open Source Friendlyness_, just created that term...) should go first.

**Comment by ePaul** [comment]
From the Meeting:

We see two general approaches:

* stay with our current "coding in the open" approach, having it accessible for Zalando employees
* go fully "open source", removing all Zalando-specific references

@dehora @tfrauenstein @therealpadams could you please agree on an approach?

**Comment by dehora** [comment]
@ePaul I recommend removing Zalando specific references and doing so as soon as possible.

I've created https://github.com/zalando/restful-api-guidelines/pull/401 to remove existing private links, including the one added in #350, until this issue gets resolved.

There are I think at least two Google documents that are public, referenced in the guidelines. It's not at all clear what their status is (does the guild own them?), and at least one of those contained a link to a private document.

**Comment by tfrauenstein** [comment]
"internal links" are no black-or-white problems: 

We open sourced our guidelines to share it with the industry, help other orgs to create their guidelines and foster an industry API culture. Our ambition was not to create an industry REST design standard and to restrict to rules that are ready for industry consent. Hence, it is more the "coding in the public" approach. 

The guidelines contain tons of Zalando specific aspects (introduction, naming, security, permissions, events, examples, ... ). I agree, that we should reduce and localize Zalando specific guideline aspects as to support easy external re-usage and even maintenance of external customization forks. But in balancing the trade-offs, usually we see higher priority in guidelines being optimized for our usage and engineering efficiency. 

We already have highlighted all links to internal documents as "internal" -- to ease reading by externals. We should check if we can further reduce the number of links. Internal links should not be deleted, if it likely helps our engineers to apply the rules more efficiently or with higher quality, e.g. by connecting the guideline with relevant infrastructure tool support or providing relevant internal context information.

**Comment by ePaul** [comment]
**From the meeting**
The main problems are linked internal google-docs, because anyone can request access.

Three links to Google docs are still left (two docs.google.com, one go.gl), which need to be made safe.

We agree to remove those (@API management team), and to not link google docs or any URL shortener from our guidelines in the future.

**Comment by tfrauenstein** [comment]
I think we should minimize, but keep some links to internal Google docs.
However, we provide support to make doc links safe: they will be redirected via API Portal that ensures that Zalando OAuth authentication takes place before google doc can be accessed.
@maxim-tschumak provides this feature and updates Guidelines, thanks!
