### ISSUE TITLE
Fix formatting in PATCH article

### ISSUE THREAD

**Issue by ddufourboivin-zalando** [zalando/restful-api-guidelines#396]
In the [PATCH](https://opensource.zalando.com/restful-api-guidelines/#patch) section, this

> - successful PATCH requests will usually generate 200 or 204 (if resources have been updated
> - with or without updated content returned)

should read

> - successful PATCH requests will usually generate 200 or 204 (if resources have been updated with or without updated content returned)

**Comment by ePaul** [comment]
Likely a leftover from the ASCIIdoc conversion.

**Comment by tkrop** [comment]
Fixed in #403.
