### ISSUE TITLE
Fix English grammar in DELETE article

### ISSUE THREAD

**Issue by ddufourboivin-zalando** [zalando/restful-api-guidelines#397]
At the beginning of the [DELETE](https://opensource.zalando.com/restful-api-guidelines/#delete) article,

> DELETE request are used

should read

> DELETE requests are used

**Comment by ePaul** [comment]
Just my opinion: For such small changes directly opening a PR is less overhead (and will result in faster resolution) than creating an issue.

**Comment by tkrop** [comment]
Fixed in #403.
