### ISSUE TITLE
Replace German quotation marks by English quotation marks

### ISSUE THREAD

**Issue by ddufourboivin-zalando** [zalando/restful-api-guidelines#398]
Example from the [DELETE](https://opensource.zalando.com/restful-api-guidelines/#delete) article:

> The semantic is best described as »please delete the resource identified by the URL«.

Those are German styled quotation marks. If this documentation is in English, it should read:

> The semantic is best described as "please delete the resource identified by the URL".

## Task

Search in all of the documentation and fix all of them, not only the example provided here.

**Comment by ePaul** [comment]
I actually like my »german older literature style« quotation marks (in normal texts you would find `„…“`) – those can be mixed with the ASCII ones in the code samples, and are not easily confused.

If you want to be typographically correct, use the `“...”` (66-99) style of quotation marks, not the ASCII ones (`"..."`) everywhere (outside of code examples, of course).

**Comment by ddufourboivin-zalando** [comment]
[PR open](https://github.com/zalando/restful-api-guidelines/pull/402)
