### ISSUE TITLE
Clarify usage of time zones in time formats

### ISSUE THREAD

**Issue by valgog** [zalando/restful-api-guidelines#4]
Examples and the last paragraph of the [data time format section](https://github.com/zalando/restful-api-guidelines/blob/master/data-formats/DataFormats.md#-bookmust--use-standard-date-and-time-formats) are not consistent. 

Are the time zones other than UTC allowed in payloads?

**Comment by whiskeysierra** [comment]
> Are the time zones other than UTC allowed in payloads?

The way I understand the sentence, yes. Basically input can be any offset (from UTC), but output should be in UTC, so normalized. I'm not sure if this is actually desirable, but I think this is what it says. I agree that the paragraph can certainly be improved.

**Comment by valgog** [comment]
@tfrauenstein Thomas, what do you think on that topic?

I personally would allow correct usage of Time Zones. Or do we want to go conservative and recommend to use only times in UTC?

**Comment by whiskeysierra** [comment]
I think we should allow any offset/timezone in both requests and responses. Maybe we can encourage UTC for simplicity/consistency, not sure though.

**Comment by fmueller** [comment]
I'm with @whiskeysierra. Timezones are always hard and mostly handled wrong. I'd propose a Should paragraph for encouraging UTC in our guidelines.

**Comment by tfrauenstein** [comment]
Yes, here the current guideline is somehow contradicting and I share Willi's interpretation. 

We can be more precise and a bit less restrictive -- so I propose the following update:
a) (zone) offset may be used (both, in request and responses) -- this is simply defined by the standards
b) however, we encourage to restrict to UTC (and go without offsets) when dates are passed and (above all) returned. From experience we know that zone offsets are not easy to understand and often not correctly handled. Note also, that zone offsets are different from local times that may include summer time savings.
c) latest when it comes to storage, all dates should be consistently stored in UTC (without zone offset)
d) localization should be done locally by the services that provide user interfaces, if required

**Comment by whiskeysierra** [comment]
I guess we can close this now.
