### ISSUE TITLE
Request for consensus on formal or informal language

### ISSUE THREAD

**Issue by tkrop** [zalando/restful-api-guidelines#417]
Currently, our guideline is written in very different styles with respect to citations, emphasis, punctuation, and casual vs. formal language. I would like the guideline to use a more consistent style and language.

A major point to achieve this would be to reach consensus with respect to casual vs. informal language, i.e. do we (1) like to write a more casual language utilizing *we* and *you*, or do we favor (2) a more formal language that avoids direct addressing readers and writers.

**Comment by whiskeysierra** [comment]
I prefer (1).

**Comment by tfrauenstein** [comment]
👍 -- (1) preferred

**Comment by ddufourboivin-zalando** [comment]
English has the virtue of not having this _Sie/vous_ vs _du/tu_ concept. Even using _we_ and _you_ remains polite (maybe not _formal_, but still not _casual_). I am for keeping _you/we_.

**Comment by tkrop** [comment]
Okay, consensus seems to use *you/we*.
