### ISSUE TITLE
Don't specify all possible HTTP status codes

### ISSUE THREAD

**Issue by ePaul** [zalando/restful-api-guidelines#42]
The guidelines currently say (in section "HTTP", rule "[Must: Providing Error Documentation](http://zalando.github.io/restful-api-guidelines/http/Http.html#must-providing-error-documentation)"):

> The OpenAPI specification shall include definition of all error status codes and error descriptions
> that possibly will be returned; they are part of the interface definition and provide important
> information for service clients to handle exceptional situations and support troubleshooting.

I think we should instead encourage to not document common HTTP errors which have no special meaning for this API, but just the default HTTP meaning, and can happen always (like 500, 503, ...).

Clients should be prepared for unexpected response codes, and in case of doubt handle them like they would handle the corresponding x00 code. Adding new response codes (specially error responses) should be considered a compatible API evolution.

(This might also affect the compatibility section.)

**Comment by ePaul** [comment]
(This text arrived in the guidelines with  a68803b, thus parent issue: #41.)

**Comment by tfrauenstein** [comment]
I think we should not mix both aspects.
a) API spec: intention of the guideline was: "explicitly define the returned errors as part of the interface spec". IMO it should be valid also for common HTTP errors. 
However, a bad practise is: defining error codes in the API that are not yet returned, but look like good candidates to be returned in some future with more experience in implementation operation.
b) Compatible API changes: define adding newly returned errors in API as compatible extension. Hence, clients should be prepared for unexpected response error codes -- at least they should provide analog handling as for corresponding x00 code as default.

P.S: We discussed it in a more recent API Guild meeting and actually @whiskeysierra accepted an action item to provide PR for corresponding update of both guidelines.

**Comment by ePaul** [comment]
@tfrauenstein I'm not sure how to distinguish "error codes that are not yet returned" from "error codes that are returned" in an API first setting (i.e. before any implementation is there).

What triggered this issue was the question whether we (as API designers) need to add a '500' (internal Server error) and '503' (temporary not available) response for all operations, because one can never be certain that these don't happen, or if we can simply omit them from the description, and expect the client to handle them anyways.

**Comment by whiskeysierra** [comment]
- differentiation between technical and functional errors
- technical errors don't need to be specified (covered by frameworks, e.g. 401, 403, 406, 415. doesn't add any value to the API)
- functional problems need to be specified, that includes a 404 if a resource wasn't found (if and only if it's actually a special case)
- Should include meta information, e.g. Retry-After, problem body, etc. to help the client handle it gracefully
- different problem types, if and only if status code is not sufficient
