### ISSUE TITLE
Use OpenAPI 3 Examples in the Guidelines

### ISSUE THREAD

**Issue by maxim-tschumak** [zalando/restful-api-guidelines#441]
We want to fully support OpenAPI 3. Therefore we need to replace the Swagger examples with valid OpenAPI 3 examples in the whole guidelines.

### Acceptance criteria
- [x] Only OpenAPI 3 snippets are used in the guidelines

**Comment by ePaul** [comment]
Not sure about "replace", but at least adding the 3.0 examples should be done (where they differ).

**Comment by maxim-tschumak** [comment]
@ePaul Our idea was to promote OpenAPI 3 usage (+ backward compatibility with Swagger 2). And I also think we don't want to waste so much space to provide both variants as example specification snippets.

I'm preparing a PR. We can continue the discussion based on it.
