### ISSUE TITLE
Review for compatibility section

### ISSUE THREAD

**Issue by ePaul** [zalando/restful-api-guidelines#45]
*(This is a part of #41, see there for the general view.)*

Commit a68803b changed those things in the Compatibility section:

* a small typo fix :white_check_mark: 
* completely reworded the itemized list in "Prefer compatible extensions" rule
* reword the "Avoid versioning" + "Use Media type versioning, not URI versioning" rules, leaving three rules "Avoid versioning", "Use media type versioning" and "Don't use URI versioning".
* reword the documentation version rule (without change of meaning, I think).

Please [check the diff](https://github.com/zalando/restful-api-guidelines/commit/a68803b1ed6025d37200e8d456075488f7d51068#diff-bf72c91a3bee08729395c486d36a5cc2) and comment here.

**Comment by fmueller** [comment]
I acknowledged specific change suggestions by @tkrop which he did as line notes.

Will you prepare a PR for this @ePaul?

**Comment by ePaul** [comment]
Yes, as soon as I find time for it.
