### ISSUE TITLE
Idempotency Guidelines

### ISSUE THREAD

**Issue by whiskeysierra** [zalando/restful-api-guidelines#456]
In several past reviews we ended up discussing (variants of) the following three major techniques on how to implement idempotency:

1. Conditional Requests, [RFC 7232](https://tools.ietf.org/html/rfc7232)
2. *Foreign Key* Pattern
3. Idempotency Key, https://stripe.com/docs/api#idempotent_requests

I'd like to use this issue to kick-off a focused discussion on those techniques. My goal is to extend the guidelines with a table that compares them in an objective manner:

|                                 | Conditional Requests | *Foreign Key* Pattern | Idempotency Key |
|------------------------------------|--------------------------|----------------------------|---------------------------|
| Applied with HTTP methods       | `PUT`/`PATCH`                  | `POST`                   | `PUT`/`POST`/`PATCH`       |
| HTTP Standard                   | ✔️ Yes                | ✖️ No                     | ✖️ No                     |
| Prevents concurrent creation  | ✔️ Yes              | ✔️ Yes                  | ✖️ No                    |
| Prevents lost updates           | ✔️ Yes                | ✖️ No                    | ✖️ No                   |
| Supports safe retries           | ⚠️ With effort                  | ⚠️ With effort        | ✔️ Yes                 |
| Inspectable (by intermediaries) | ✔️ Yes                | ✖️ No                 | ✔️ Yes                |
| Exact same response             | ✖️ No             | ✖️ No     | ⚠️ With effort           |
| Requires additional `GET`<br>(before `PUT`/`POST`/`PATCH`) | ✖️ Yes   | ✔️ No   | ✔️ No        |

I don't claim that the table is complete. Let's use it as a starting point and extend/modify it as we go along. @tkrop It would also be helpful if you write 1-2 sentences on the foreign key pattern (I know I asked you this before somewhere but I can't find your answer anymore. Sorry!)

**Comment by tkrop** [comment]
I'm not absolutely sure whether the table makes sense, as all three patterns are used to solve totally different problems, which might be obscured by the above collection of properties. E.g. I would only apply the *foreign key pattern* to `POST` and the `conditional requests` to `PUT`. Anyhow, if we are able to make this clear ...

@whiskeysierra what do you exactly mean with "supports safe retries" and by "requires additional GET"?

Thanks for asking.about some words. May be *foreign key* is not the best term for it - I already had a discussion with @tfrauenstein about it, but I'm still not sure about a better term.

I was originally referring to a general pattern of process resources to possess a *natural uniqueness constraint* with respect to a parent process resource. E.g. a shopping card or a shopping session is expected to create exactly one order process. This uniqueness constraint can be reflected in a process resource by adding a *foreign key* referring to the parent resource. A similar pattern exists for data resources, that expand a specific parent resource with new properties.

In my opinion, the *foreign key pattern* can be implemented to also "support safe retries" and to provide "exact same responses". As this may not be the easy default implementation, I would mark this as third option with yellow as possible.

**Comment by whiskeysierra** [comment]
> I'm not absolutely sure whether the table makes sense, as all three patterns are used to solve totally different problems, which might be obscured by the above collection of properties.

That's true. I'm not suggesting that we agree on one pattern and forbid to use the rest. I'd rather have the table used as a tool for API designers to decide which one fits their use case the best, since all of them have pros and cons.

> Anyhow, if we are able to make this clear ...

We should.

> I would only apply the _foreign key pattern_ to `POST`

That's the primary use case, agreed. Although from a technical perspective there is nothing wrong with using it for PUT, is there?

> `conditional requests` to `PUT`

What about `PATCH`?

> what do you exactly mean with "supports safe retries"

I don't really remember, to be honest. Looking at it now, I believe all patterns should have a *Yes* there.

> and by "requires additional GET"?

A conditional request requires the most current ETag or last modified to work which a client only get's by issuing an additional `GET` request. The other two patterns don't need this since they both use client-side knowledge (foreign key) or client-side generated keys (idempotency key).

> but I'm still not sure about a better term.

We used to call it *remote id*, although I'm not 100% whether that's the best term for it.

> In my opinion, the _foreign key pattern_ can be implemented to also "support safe retries" and to provide "exact same responses"

But still exclusively for *create* but not for *update*, right?

**Comment by tkrop** [comment]
>>    I would only apply the *foreign key pattern* to `POST`
>
> That's the primary use case, agreed. Although from a technical perspective there is nothing wrong with using it for `PUT`, is there?

Feels wrong for me. If you have a *foreign key*, it should be used as *primary key* in `PUT`. This, I would not define as an application of the *foreign key pattern*.

>> `conditional requests` to `PUT`
>
> What about `PATCH`?

True. Add: and `PATCH`

>>    what do you exactly mean with "supports safe retries"
>
> I don't really remember, to be honest. Looking at it now, I believe all patterns should have a Yes there.

I agree.

>> and by "requires additional `GET`"?
>
> A conditional request requires the most current `ETag` or last modified to work which a client only get's by issuing an additional `GET` request. The other two patterns don't need this since they both use client-side knowledge (foreign key) or client-side generated keys (idempotency key).

Acknowledged. To make it clearer I suggest to describe the row "Requires additional `GET` before `PUT`/`POST`)"

I suggest to add an additional row called "default HTTP method" or just "applied with HTTP methods", that states only `PUT` for the *conditional requests*, `POST` for the *foreign key pattern*, and may be `PUT`/`POST` for the *idempotency key*. Using this, we can merge the two lines for "prevents concurrent creation". I also stick to my suggestion to introduce a third option (*with effort*) for certain fields. My table would look as follows:


|                                 | Conditional Requests | *Foreign Key* Pattern | Idempotency Key |
|------------------------------------|--------------------------|----------------------------|---------------------------|
| default HTTP method       | `PUT`                   | `POST`                   | `PUT`/`POST`       |
| HTTP Standard                   | ✔️ Yes                | ✖️ No                     | ✖️ No                     |
| Prevents concurrent creation  | ✔️ Yes              | ✔️ Yes                  | ✖️ No                    |
| Prevents lost updates           | ✔️ Yes                | ✖️ No                    | ✖️ No                   |
| Supports safe retries           | ✔️ Yes                  | ✔️ With effort        | ✔️ Yes                 |
| Inspectable (by intermediaries) | ✔️ Yes                | ✖️ No                 | ✔️ Yes                |
| Exact same response             | ✖️ Possible                | ✔️ With effort     | ✔️ Yes           |
| Requires additional `GET`<br>(before `PUT`/`POST`) | ✖️ Yes   | ✔️ No   | ✔️ No        |

PS: may be you can find a yellow sign for *with effort*.

**Comment by ePaul** [comment]
From the guild meeting: We agree that it would be a good idea in general to have something like this in the guidelines.

**Comment by whiskeysierra** [comment]
@tkrop I took your table and replaced the one in the top comment.

**Comment by whiskeysierra** [comment]
@tkrop 

> Supports safe retries

I believe conditional requests and foreign key both require the same effort on the client side, since as consumer would interpret 412 or 409 as an indication that the request failed because the resource already existed (The same applies to conditiona requests and updates).

> Exact same response

I'd say it would violate a conditional request to send a previous success message, therefore I'd use "No" there. Foreign key is debatable, but I'd also say it kind of violates the idea, e.g. what happens if other parameters change in between. Idempotency keys support this aspect from a spec's perspective, but the implementation is still requiring a lot of effort, imho.

**Comment by tkrop** [comment]
>> Exact same response
>
> I'd say it would violate a conditional request to send a previous success message, therefore I'd use "No" there.

Good catch. I actually missed that :+1:

**Comment by tkrop** [comment]
@whiskeysierra Let move forward and start a PR.
