### ISSUE TITLE
Review for General Guidelines + design principles sections

### ISSUE THREAD

**Issue by ePaul** [zalando/restful-api-guidelines#46]
*(This is a part of #41, see there for an overview.)*

Commit a68803b1 [changed these things in the General Guidelines section](https://github.com/zalando/restful-api-guidelines/commit/a68803b1ed6025d37200e8d456075488f7d51068?short_path=f7d5d68#diff-f7d5d68455a127a569820bd8b8829a0a):

* rewording of the Resources section
* space removal
* new section "Use domain specific resource names".

In the [Design principles section those thing changed](https://github.com/zalando/restful-api-guidelines/commit/a68803b1ed6025d37200e8d456075488f7d51068?short_path=bfe0f0a#diff-bfe0f0ae16a871fb3de7371f18e3c1ad):

* link to internal document (Restful API practices) was removed, instead
* a generic sentence was added about the goals.

Please review the diff and comment here.

**Comment by tkrop** [comment]
I reviewed the general-guidelines as well as the design-principles. Had only one comment on design-principles.

**Comment by ePaul** [comment]
Thanks, somehow I missed the change to "Design principles". I'm fixing the typo.

**Comment by fmueller** [comment]
Reviewed, LGTM after minor editorial fix.

**Comment by ePaul** [comment]
Thanks, closing this issue.
