### ISSUE TITLE
Remove rule "May Use /api as first Path Segment [135]"

### ISSUE THREAD

**Issue by whiskeysierra** [zalando/restful-api-guidelines#462]
https://opensource.zalando.com/restful-api-guidelines/#135

Alternatively we may choose to switch it from "May" to "May not". It doesn't serve any significant purpose anymore and just pollutes the URL space.

**Comment by tfrauenstein** [comment]
👍

**Comment by ePaul** [comment]
Hmm, maybe SHOULD NOT?

**Comment by tkrop** [comment]
I think removing is the best practice. We do not really have a problem with `/api`. It just isn't used very often in new APIs. So not mentioning it at all as an option will suffice for I think 99.9%.

**Comment by maxim-tschumak** [comment]
From the meeting:
* Let's change the rule title to "SHOULD NOT ..."
* If you have internal and external endpoints, create 2 API specifications (and not use an API prefix)
* You may use the base path as part of servers declaration (part of deployment info): e.g. one service implements >1 APIs.
