### ISSUE TITLE
Review for HTTP section

### ISSUE THREAD

**Issue by ePaul** [zalando/restful-api-guidelines#47]
*(This is a part of #41, see there for an overview.)*

Commit a68803b1 [changed these things in the HTTP section](https://github.com/zalando/restful-api-guidelines/commit/a68803b1ed6025d37200e8d456075488f7d51068#diff-8d6e0f72d85703dfe338d1135d48a0bf):

* added table "Redirection codes" in the "Use Meaningful HTTP Status codes" rule
* added some entries to the "Client side error codes" rule
* adding new table "Client side error codes" containing server side error codes.
* adding "Providing error documentation" rule (there are already #42 + #43 about this)
* rewording of the second paragraph in the gzip compression rule 
* rewording of the first paragraph in the "Support filtering of resource fields" rule

Please review the diff and comment here.

**Comment by ePaul** [comment]
Obviously, the second table "Client side error codes" needs to be renamed to "Server side error codes".

**Comment by fmueller** [comment]
LGTM. We already had improvements on this section after the merge from Google doc, for instance wording of gzip compression rule.

**Comment by ePaul** [comment]
Thanks, closing this issue.
