### ISSUE TITLE
typo in compatibility section

### ISSUE THREAD

**Issue by lucas03** [zalando/restful-api-guidelines#477]
> Enum ranges cannot not be extended when used for output parameters

Is double negative here a typo? :) 

https://github.com/zalando/restful-api-guidelines/blob/e3888fb0e559fa16573d7d275f61b1611b838df1/chapters/compatibility.adoc

**Comment by maxim-tschumak** [comment]
Good catch! Do you want to create a PR?

**Comment by lucas03** [comment]
sure, I'll create a PR. 

what about `megabytes for strings` for `megabytes of strings` in here -> https://opensource.zalando.com/restful-api-guidelines/index.html#108
