### ISSUE TITLE
Review for Hypermedia section

### ISSUE THREAD

**Issue by ePaul** [zalando/restful-api-guidelines#48]
*(This is a part of #41, see there for an overview.)*

Commit a68803b1 [changed these things in the Hypermedia section](https://github.com/zalando/restful-api-guidelines/commit/a68803b1ed6025d37200e8d456075488f7d51068?short_path=514a20f#diff-514a20fc7cfdb1e4b7475ae35ce98641):

* rewording in the introductory section
* changed + formatted links
* added paragraph for the "Use URIs for custom link relations" rule
* added rule "Use Standards for Hypermedia Link Types" (this was later modified in #38, and will be addressed separately when we come to a decision).

Please review the diff and comment here.

**Comment by fmueller** [comment]
LGTM. And we also had changes in this section since Google doc merge.

**Comment by ePaul** [comment]
Thanks. Closing now.
