### ISSUE TITLE
Review for Naming section

### ISSUE THREAD

**Issue by ePaul** [zalando/restful-api-guidelines#49]
*(This is a part of #41, see there for an overview.)*

Commit a68803b1 [changed these things in the Naming section](https://github.com/zalando/restful-api-guidelines/commit/a68803b1ed6025d37200e8d456075488f7d51068?short_path=339ece0#diff-339ece072d9177f785c00b603253405b):

* changed clarification for "Pluralize Resource names" rule
* reword rule " Consider Using  Nested URLs When the Access Pattern Allows" → "Consider Using (Non-) Nested URLs" (with several changes in the text, too, and examples of non-nested URIs).
* added rules "Limit of Resources" and "Limit of Sub-Resource levels" → these were later removed in #23.
* some text changes to "Use conventional Query strings" rule

Please review the diff and comment here.

**Comment by fmueller** [comment]
LGTM

**Comment by ePaul** [comment]
Thanks, closing this issue.
