### ISSUE TITLE
Link to JSON-fields library is a dead link

### ISSUE THREAD

**Issue by ChrisDeBruyne** [zalando/restful-api-guidelines#492]
In the Tooling chapter you are referring to a library called JSON-fields.
The link pointing to https://github.com/zalando-incubator/json-fields is not working.
 
Did the library move or is it no longer available?

**Comment by maxim-tschumak** [comment]
Good catch!

The mentioned tool hasn't been open-sourced yet (it was in zalando-incubator previously).

We should remove the entry. @ChrisDeBruyne Would you like to create a PR?

**Comment by ChrisDeBruyne** [comment]
Sure, I'll create one.
