### ISSUE TITLE
Review for Pagination rule

### ISSUE THREAD

**Issue by ePaul** [zalando/restful-api-guidelines#50]
*(This is a part of #41, see there for an overview.)*

Commit a68803b1 [changed these things in the Pagination section](https://github.com/zalando/restful-api-guidelines/commit/a68803b1ed6025d37200e8d456075488f7d51068?short_path=dad0fe8#diff-dad0fe8d18a4af765b1911d662a3073b):

* some wording changes to "must support pagination" and "Prefer Cursor-Based Pagination, Avoid Offset-Based Pagination" rules.

Please review the diff and comment here.

**Comment by ePaul** [comment]
Not a change introduced by that diff, but the nested list is not valid markdown syntax (and thus looks broken both in Github and in Gitbook).

`* *` needs to be changed to a single, but more indented `*`.

**Comment by fmueller** [comment]
Thanks for fixing indentation. After this LGTM.

**Comment by ePaul** [comment]
Thanks, closing this issue.
