### ISSUE TITLE
Customer_id example in rule #174 conflicts with backward compatibility constraints

### ISSUE THREAD

**Issue by tfrauenstein** [zalando/restful-api-guidelines#500]
https://opensource.zalando.com/restful-api-guidelines/#174
gives customer_id as example for good naming which is in principle right. However, here we have to make very clear that there are backward compatibility constraints in Zalando where customer_number and customer_id have been defined with different semantics.

**Comment by ePaul** [comment]
@tfrauenstein will open a PR.
