### ISSUE TITLE
Review for Common Headers

### ISSUE THREAD

**Issue by ePaul** [zalando/restful-api-guidelines#52]
*(This is a part of #41, see there for an overview.)*

Commit a68803b1 [changed these things in the Common Headers section](https://github.com/zalando/restful-api-guidelines/commit/a68803b1ed6025d37200e8d456075488f7d51068?short_path=3d6b00f#diff-3d6b00fa4281598f0260f98d60422e42).

(Later this was renamed to "Proprietary Headers" in #5)

* adding headers `X-Frontend-Type`, `X-Device-Type`, `X-Device-OS`, `X-Uid` with description
* extended description of `X-Tenant-Id` (this was later modified in #18)

Please review the diff and comment here.

**Comment by tkrop** [comment]
Reviewed changes and added only one comment to commit. Please review comment.

**Comment by whiskeysierra** [comment]
> adding headers X-Frontend-Type, X-Device-Type, X-Device-OS, X-Uid with description
> extended description of X-Tenant-Id (this was later modified in #18)

Can we take the chance to rename the headers to `X-UID` and `X-Tenant-ID`? (I know headers are case insensitive, but those two look just weird. It's also not consistent with `X-Device-OS`.)

**Comment by ePaul** [comment]
I guess whoever added those header names took the [Prefer Hyphenated-Pascal-Case for HTTP header Fields](http://zalando.github.io/restful-api-guidelines/naming/Naming.html#should-prefer-hyphenatedpascalcase-for-http-header-fields) rule to strictly without reading the text »Exceptions are common abbreviations like “ID.”« in it.

So yes, renaming sounds good.

**Comment by fmueller** [comment]
+1 for renaming the tenant header

**Comment by ePaul** [comment]
Just to sum up the suggestions:

* rename headers (in documentation) to use `-UID` or `-ID` instead of the Pascal-cased variants `-Uid`/`-Id`
* use an UUID instead of `Zalando-Fashion-Store` in the example for `X-Tenant-ID`.

I'll do this when I find time.

**Comment by fmueller** [comment]
Thank you @ePaul for your work on this.
