### ISSUE TITLE
Reusable schema for Money

### ISSUE THREAD

**Issue by whiskeysierra** [zalando/restful-api-guidelines#520]
We have a schema for [Problem](https://opensource.zalando.com/restful-api-guidelines/#176) that API designers can rely on by simply referring to it by URL.

`Money` would be a good candidate to offer that as well in my opinion since we use it a lot of APIs.

**Comment by whiskeysierra** [comment]
Not sure if the following deserves a separate issue, if yes please say so:

In addition I'd advocate to disallow using `Money` in an [inheritance/polymorphism](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#schemaComposition) construct, i.e. only the guidelines should allow extensions to the `Money` object. APIs better treat it as an immutable, scalar value that may or may not be extended in the future but is not within their power to manipulate in any structural way.

Primary reason for this restriction is that I've several cases now where API authors were trying to squeeze multiple amounts into one object in order to enforce a single currency.

**Comment by tfrauenstein** [comment]
Yes, I agree: Guidelines should also provide schema for Money (analogue to Problem schema). 
But why you want to disallow extensions of the money object?

**Comment by whiskeysierra** [comment]
> But why you want to disallow extensions of the money object?

Because it would make any existing library build on top of it useless if you want to support the extension on client side. Composition allows to be equally expressive and it preserves re-usability of code.

**Comment by whiskeysierra** [comment]
Examples:

## Inheritance

```json
{
  "amount": 19.99,
  "currency": "EUR",
  "formatted": "19,99 €"
}
```

```json
{
    "price_formatted": "19,99 €",
    "price": {
      "amount": 19.99,
      "currency": "EUR"
    }
}
```

**Comment by tfrauenstein** [comment]
ok, let's restrict it, but also motivate it -- along the lines discussed above. thx!

**Comment by whiskeysierra** [comment]
- [ ] Add link to https://github.com/zalando/jackson-datatype-money
- [ ] Include inheritance and composition examples
- [ ] Argue in favor of composition
    - compatible with library support
    - https://en.wikipedia.org/wiki/Liskov_substitution_principle
    - more flexible, e.g. mixed currencies (less coupling in this case of two amounts to one currency)
    - self describing
