### ISSUE TITLE
Naming conventions for enum values

### ISSUE THREAD

**Issue by whiskeysierra** [zalando/restful-api-guidelines#530]
There are no naming conventions that cover enum values.

I've seen several different styles in our APIs so far:
- `MY_VALUE`
- `my-value`
- `my_value`

Does it make sense to try to standardize that to become more consistent?

**Comment by zeitlinger** [comment]
yes, good idea!

**Comment by whiskeysierra** [comment]
A collection of useful references:

- [OpenAPI 3: Enum](https://swagger.io/docs/specification/data-models/enums/), uses lower-case (not clear whether hyphen or underscore since examples are single words only)
- [Google JSON Style Guide: Enum Values](https://google.github.io/styleguide/jsoncstyleguide.xml#Enum_Values), uses upper-underscore examples
- [Github API v4](https://developer.github.com/v4/enum/issuestate/): uses upper-underscore

**Comment by tkrop** [comment]
@whiskeysierra sounds like `upper-underscore` is has the lead in other standards;  I would vote for 1. or 2. to keep `enum` values distinguishable from properties.

**Comment by whiskeysierra** [comment]
>  I would vote for 1. or 2. to keep `enum` values distinguishable from properties.

Agreed. 

Option 1 is familiar to enums in C-style languages. Option 2 feels more HTTP-ish (not sure why, tbh).

**Comment by zeitlinger** [comment]
I would also go with 1 as it's the most adopted - although I personally like 2 more.

**Comment by vadeg** [comment]
I would go with 1. Option 2 is also fine.

**Comment by tfrauenstein** [comment]
I prefer MY_VALUE (option 1), as to clearly distinguish values from variables and other elements.

**Comment by gewald** [comment]
I would also go with option 1.

**Comment by whiskeysierra** [comment]
Regarding code generation, the enum style doesn't really matter since it can be mapped based on its string value:

```java
public enum Event {
    FORGOT_PASSWORD("forgot password");

    private final String value;

    private Event(final String description) {
        this.value = description;
    }

    @JsonValue
    final String value() {
        return this.value;
    }
}
```

**Comment by ePaul** [comment]
*From the meeting*:

* each API should use only one style for their enums (and extensible enums)
* we want to recommend one style (before deciding which one, we'll have a look at statistics of current usages in our API repository).

**Comment by tkrop** [comment]
I have kept the analysis simple using the following `jq | awk`-pipe:

```
less apis-2019-10-31.json | jq -r 'select(.state == "ACTIVE") | .. | select((type == "object") and (has("enum") or has("x-extensible-enum"))) | (if (.enum != null) then .enum else [] end) + (if (."x-extensible-enum" != null) then ."x-extensible-enum" else [] end) | .[]' | awk '($0 ~ "^[0-9]+$") { x["n"]++; next } ($0 ~ "^[a-z0-9-]+$") { x["l-"]++; next } ($0 ~ "^[A-Z0-9-]+$") { x["u-"]++; next } ($0 ~ "^[a-z0-9_]+$") { x["l_"]++; next } ($0 ~ "^[A-Z0-9_]+$") { x["u_"]++; next } ($0 ~ "^[a-zA-Z0-9_\-]+$") { x["b"]++; next } { x["o"]++; print $0 } END {for (k in x) { print k OFS x[k]; } }'
```

The result are:

| Regexp               | Active | Active+Inactive |
|------------------------|----------|---------------------|
| `^[A-Z0-9-]+$`     |   3540 | 5646 |
| `^[A-Z0-9_]+$`    |   1388 | 2916 |
|  `^[a-z0-9-]+$`     |   1071 | 4873 |
|  `^[a-z0-9_]+$`     |   116 |    278 |
|  `^[a-zA-Z0-9_\-]+` | 157 |    466 |
|  others                   |   18 |     200 |

**Comment by whiskeysierra** [comment]
My awk skills are a bit rusty. Can a single enum count towards multiple
naming conventions? For example, `active` could be lower underscore, lower
hyphen and snake case.

**Comment by tkrop** [comment]
The script is written, so that every word is only counted once (`next`). So the first matching regexp wins. Ups, and there is the bug. The `-` versions include the once without anything. I will correct the above table.

**Comment by whiskeysierra** [comment]
> The script is written, so that every word is only counted once (`next`). So the first matching regexp wins.

That is not really representative, is it? I feel that an enum value should count towards each matching pattern, otherwise the ordering of patterns in your script determines a priority and affects the results.

**Comment by tkrop** [comment]
Added this summing up to my [above comment](https://github.com/zalando/restful-api-guidelines/issues/530#issuecomment-548700745).

**Comment by whiskeysierra** [comment]
So `UPPER_UNDERSCORE` catches the majority of enum values that are currently in use. Correct?

`MY-VALUE1` is surprisingly widespread.

**Comment by tkrop** [comment]
> MY-VALUE1 is surprisingly widespread.

Yes, surprisingly.

However, it is interesting, that in the past `my[-_]value1` has been used so much more often.

**Comment by tkrop** [comment]
Found `parse error: Expected separator between values at line 885208, column 1` preventing 3/4 of the data not being parsed. Will update the data, when I created a new corrected repository dump.

**Comment by tkrop** [comment]
Changes above tables to contain latest results.

**Comment by ePaul** [comment]
**Decision in the meeting**:

We go with UPPER_UNDERSCORE. @whiskeysierra will word the rule and open a PR.
