### ISSUE TITLE
Clarify interaction of `fields` and `default`

### ISSUE THREAD

**Issue by dehora** [zalando/restful-api-guidelines#533]
It's not clear whether the [`fields` parameter](https://opensource.zalando.com/restful-api-guidelines/index.html#157) is intended to have a `default` (at the level of design), or if it's intended to be used only to create partials from a whole. As things stand in the guidelines, it seems to not be an incorrect approach technically speaking. to combine the two so as to allow a resource using fields to return a partial object by default.The follow on implication is an API designer using these guidelines can require a client that wants to obtain a whole object to ask for every field at every level of depth.

**Comment by tkrop** [comment]
I think this is related to #483, because if `fields` is combined with `default` it pretty much renders `embed` useless. May be we should than focus on one rule for both aspects. I would favor `fields` than.

@mescalero what do you think?

**Comment by whiskeysierra** [comment]
> if `fields` is combined with `default` it pretty much renders `embed` useless

Can you elaborate on that?

**Comment by ePaul** [comment]
To add to the guideline:
* default value for this parameter is counter-intuitive, and should not be used

We also discussed whether it might make sense to make this parameter required, but didn't come to an agreement here. So for now we don't add anything about this to the guidelines.

**Comment by whiskeysierra** [comment]
https://en.wikipedia.org/wiki/Principle_of_least_astonishment
