### ISSUE TITLE
Duplicate rule for currency/country codes?

### ISSUE THREAD

**Issue by aaronkorver** [zalando/restful-api-guidelines#534]
We love the work done on these.  While reviewing we noticed that 
[May: Use Standards for Country, Language and Currency Codes [170]](https://opensource.zalando.com/restful-api-guidelines/#170) and 
[May: Standards could be used for Language, Country and Currency [128]](https://opensource.zalando.com/restful-api-guidelines/#128) seem to be duplicates of each other.

Was wondering if this was on purpose?

**Comment by ePaul** [comment]
128 is in Section 8 (JSON guidelines), 170 is in Section 16 (Data formats).

I don't think it was on purpose, there likely something did go wrong during some restructuring – maybe result of sloppily resolving a merge conflict (and likely before we introduced the numbering).

170 has nicer formatting, so I would propose we retain this one, and delete 128.

**Comment by whiskeysierra** [comment]
Should we put both rule ids/links on it?

**Comment by aaronkorver** [comment]
When my team reviewed, they did like it being in both sections.  As they could see if one was simply modeling JSON they may not go and read the Data format section.  So if you keep both, just have one link to the other.

My vote is to keep the 128 section and drop 170

**Comment by tkrop** [comment]
I think, this rule is best fitting with the section *Data Formats*. In my opinion, the distinction between *JSON Guidelines*, *Data Formats*, and *Common Data Types* is a bit artificial, as all of them are related to pure JSON object design. May be we should move this chapters closer together.
