### ISSUE TITLE
schema definition of global money object is broken

### ISSUE THREAD

**Issue by juheise** [zalando/restful-api-guidelines#537]
https://opensource.zalando.com/restful-api-guidelines/#173
￼
> Use the following common money structure:
>
>     Unresolved directive in chapters/common-data-types.adoc - include::../money.yaml[]
>
> APIs are encouraged to include a reference to the global schema for Money.

**Comment by ePaul** [comment]
This was caused by #532, which moved the money.yaml file to a new directory, but didn't adapt this include directive.
