### ISSUE TITLE
Recommendations for links and IDs

### ISSUE THREAD

**Issue by fmueller** [zalando/restful-api-guidelines#54]
In last API guild meetup we decided to update guidelines on links usage in payload and ids:

- all links should be present in _links field which can also be used multiple times in one payload
- favor simple IDs if in same namespace/system otherwise think about using URNs e.g. urn:warehouse:FG-AS-123-FD

**Comment by ePaul** [comment]
I think we should not pretend to use the `urn` URI scheme without actually [registering a URN namespace](https://tools.ietf.org/html/rfc3406).

**Comment by whiskeysierra** [comment]
> I think we should not pretend to use the urn URI scheme

`zrn` it is then ;)

**Comment by fmueller** [comment]
It's more about a meaningful example which we should provide in our guidelines if we emphasize usage of URNs.
