### ISSUE TITLE
Spectral ruleset

### ISSUE THREAD

**Issue by morten-nielsen** [zalando/restful-api-guidelines#544]
Could the Zalando Guideline be available as a ruleset for Spectral? Or do you only support Zally?
https://stoplight.io/p/docs/gh/stoplightio/spectral

**Comment by ePaul** [comment]
Hi, thanks for your question.
We just discussed this in our API guild meeting.

We didn't look at Spectral before. From a first glance, it seems like implementing a ruleset for our guidelines would not that easy, as most of the rules are not easily described in a declarative language. So most of the rules would need to be implemented in custom functions, basically reimplementing all the rules in Javascript we have currently in Zally implemented in Kotlin.

We currently don't have the capacity to invest into another tool doing the same things. If you (or someone else) would implement the ruleset for Spectral (or other linting tools), we can link them in the [Tooling](https://opensource.zalando.com/restful-api-guidelines/#appendix-tooling) section of the API guidelines.

Out of interest: Why do you need a separate tool?

**Comment by whiskeysierra** [comment]
I'd close this for now as we won't do anything here. That does not mean to suppress any ongoing discussion on this.

**Comment by morten-nielsen** [comment]
The main driver behind using Spectral is that it has has smaller footprint over Zally, as it has a CLI option. This fits much better to any stage of our DevOps process and CI/CD pipeline.

**Comment by whiskeysierra** [comment]
https://github.com/zalando/zally/tree/master/cli

**Comment by morten-nielsen** [comment]
It requires a server install

**Comment by christiansiegel** [comment]
Did anyone pursue creating spectral rulesets based on the zalando guidelines?

**Comment by philsturgeon** [comment]
There's this. https://github.com/baloise-incubator/spectral-ruleset/blob/main/.spectral.yml
