### ISSUE TITLE
Warning headers to be deprecated in next RFC

### ISSUE THREAD

**Issue by ioggstream** [zalando/restful-api-guidelines#548]
## Warning

The Warning header field is going to be deprecated in the next http semantic. See 
https://tools.ietf.org/html/draft-ietf-httpbis-cache-06#section-5.5

and the http mailing list

@whiskeysierra @tkrop discussion here https://github.com/dret/I-D/issues/125

**Comment by ePaul** [comment]
It's currently mentioned in rules [189](https://opensource.zalando.com/restful-api-guidelines/#189) and [190](https://opensource.zalando.com/restful-api-guidelines/#190) about API deprecation.

**Comment by ePaul** [comment]
Possible alternatives: [RFC 8594: Sunset](https://tools.ietf.org/html/rfc8594) or [Deprecation (currently in "Internet Draft")](https://tools.ietf.org/html/draft-dalal-deprecation-header-01).
