### ISSUE TITLE
Contradicting points regarding X-Flow-ID

### ISSUE THREAD

**Issue by quanganhtran** [zalando/restful-api-guidelines#549]
[Section 183](https://opensource.zalando.com/restful-api-guidelines/index.html#183) gives an example of an x-flow-id: `GKY7oDhpSiKY_gAAAABZ_A`
[Section 233](https://opensource.zalando.com/restful-api-guidelines/index.html#233) dictates the charset of x-flow-id to be base64: `[a-zA-Z0-9/+]`. The example given in section 183 is of an invalid x-flow-id.

Since these points are contradicting, it would be good to correct the example or expand the allowed charset.

As a sub-question: Does 233 mean UUIDs cannot be used as an x-flow-id?

**Comment by whiskeysierra** [comment]
Good catch!

The regex and reference to base64 is incorrect and confusing at best.

I believe we should be more forgiving and allow for the following formats:

- base64
- base64url
- UUID
- underscores (as in the example in rule 183)

Regular expression could be changed to `^[\w\/\-+=]+$`
