### ISSUE TITLE
Examples for good problem types

### ISSUE THREAD

**Issue by whiskeysierra** [zalando/restful-api-guidelines#550]
In [Rule 176](https://opensource.zalando.com/restful-api-guidelines/#176) we advocate for `application/problem+json` but we don't give good examples and guidance for:

- when to use a custom problem type
- good values for problem types

While the RFC encourages a URI reference that can be dereferenced:

> This specification encourages that, when
      dereferenced, it provide human-readable documentation for the
      problem type (e.g., using HTML [W3C.REC-html5-20141028]).
>
> https://tools.ietf.org/html/rfc7807#page-5

I'd suggest to pick non-URL types, e.g. `my-custom-problem-type`. It frees us from situation where locations URLs change and one would need to server a proper HTML page there. We have OpenAPI for that, imho.

**Comment by ePaul** [comment]
Sounds good. Do you (@whiskeysierra) want to work on this?

**Comment by whiskeysierra** [comment]
Yes, I will.
