### ISSUE TITLE
Clarify Deprecation Header usage

### ISSUE THREAD

**Issue by tfrauenstein** [zalando/restful-api-guidelines#562]
copied from API-Guild chat: Daniel Konczyk:

1) Hi, was actually going through these changes today and it would be great to get some clarification. https://opensource.zalando.com/restful-api-guidelines/#189 starts with During deprecation phase, the producer should add a Deprecation header [...] with the sunset date value. However https://tools.ietf.org/html/draft-dalal-deprecation-header-02 states that Deprecation header carries a deprecation date (past/future, aka 'deprecated since') or "true" value, while the actual sunset date should be sent through the Sunset header. Any reason we have it differently?

2) Additionally, what should happen if there are e.g. two fields deprecated at different times under the same uri - what date would we return in the Deprecation header?

3) Oh and one last thing - have you considered providing a specification extension for the actual date that should be set in the header, since there's nothing in the OpenAPI at the moment to support that and seems that proposals for additional fields (deprecation-related) were not accepted. We already support extensions (e.g. x-extensible-enum), so it could be useful to be able to set the deprecation date this way too?

**Comment by tfrauenstein** [comment]
1) yes, wording in the rule is misleading -- the header is about the deprecation date and not the sunset date. We did not (yet) include rule for sunset header field (see https://tools.ietf.org/html/rfc8594) -- to be further discussed.

2) If two fields are deprecated at different times, we should recommend to return the smaller date.
The main info about deprecation (of elements) should be anyway provided with the OpenAPI API spec.

**Comment by konczyk** [comment]
Thank you, 

> 1. yes, wording in the rule is misleading -- the header is about the deprecation date and not the sunset date. We did not (yet) include rule for sunset header field (see https://tools.ietf.org/html/rfc8594) -- to be further discussed.

The same `sunset` term is used in other rules (187,190) - I think it would be good to clarify the wording across the document, as the difference between these dates is quite significant.

> 2. If two fields are deprecated at different times, we should recommend to return the smaller date.
>    The main info about deprecation (of elements) should be anyway provided with the OpenAPI API spec.

Was there any particular reason guidelines settled on a date in the header instead of `Deprecation: true` (or both, as defined in the RFC)? If we have to inspect the api spec for details anyway, it feels the date in a header is less useful and might be confusing at times?

> 3. yes, OpenAPI not (yet) supports deprecation dates (it is a boolean). We require to provide this kind of information in the description fields (see https://opensource.zalando.com/restful-api-guidelines/#187) and avoided make use of custom extensions.

That rules says 
```If deprecated is set to true, the producer must provide a sunset date and describe what consumers should use instead (possibly via links to details) in the description section.```

 while this field could easily hold a date too, it can also contain arbitrary data, so code autogeneration for deprecations would not be possible. Allowing **true** as an option in the header could easily fix that problem (as would an extension mentioned earlier). Is that something that could be considered?

**Comment by tkrop** [comment]
I have the feeling we should propagate the `should/must` usage of the `Deprecated: <true|since-date>` and `Sunset: <deadline-date>` headers together to prevent misleading interpretation of fast readers and message receivers.

**Comment by hjacobs** [comment]
As I see this deprecation header: what is the relation to OpenTracing (definition of baggage items) to track calls to deprecated endpoints?

**Comment by whiskeysierra** [comment]
> As I see this deprecation header: what is the relation to OpenTracing (definition of baggage items) to track calls to deprecated endpoints?

@hjacobs Can you elaborate on that? Are you suggesting to use baggage items rather than headers?

**Comment by hjacobs** [comment]
@whiskeysierra no, I was just asking on how we integrate it for OpenTracing and whether we already thought about conventions for OpenTracing tags (baggage items are probably wrong for this use case). I created an internal Zalando issue to discuss this (will contact you via DM).

**Comment by tkrop** [comment]
@hjacobs We discussed this aspect in the meeting: Currently, we cannot give any advice how service and client owners should implement this aspects. We would like Riptide, open-tracing libraries, or our infrastructure to support this aspect. However, we have not figured out the best way yet, as we have to address client as well as server side monitoring aspects.

**Comment by whiskeysierra** [comment]
> We would like Riptide, open-tracing libraries, or our infrastructure to support this aspect.

I considered this for the `Warning` header back in the day already but decided against it, because we were also using Logbook in most services and you could easily have an alert on the presence of a deprecation header there:

```
$httpHeadersSunset matches '.*'
```

See also https://github.com/zalando/logbook/blob/master/docs/scalyr.md
