### ISSUE TITLE
Change build process to not need a personal access token

### ISSUE THREAD

**Issue by ePaul** [zalando/restful-api-guidelines#568]
Currently, the build process to create the web side from the repository is [running on Travis CI](https://travis-ci.org/zalando/restful-api-guidelines), and publishes the result by pushing to the gh_pages branch.

For that, it's using a `GH_TOKEN` variable configured in the [project settings](https://travis-ci.org/zalando/restful-api-guidelines/settings), which is a [personal access token](https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line).
This token was previously created by @maxim-tschumak, and after he left the organization, and thus lost the write rights, a new one was created today by me (@ePaul).
This token gives read and write rights to all repositories I have access to, in my name. Unfortunately there seems to be no way of creating a token which has access just to a single repository.

This induces those risks:
* If I ever leave the organization, my token automatically loses write access to the repository, and thus breaks the publishing of new versions.
* If something goes wrong and some attacker gets hold of the token, that person can impersonate me on all repositories – both my personal ones, and ones in organizations where I have access.

We should think about setting up the build process in a way that a personal token is not needed. A possible solution might be using a repository-specific [deployment key](https://developer.github.com/v3/guides/managing-deploy-keys/#deploy-keys).

**Comment by ePaul** [comment]
Ideas: use github action for this (ask @vadeg)

**Comment by tkrop** [comment]
Yes, this should actually work. I found a howto describing a similar use case as ours.

**Comment by vadeg** [comment]
I have found several GitHub Actions (check [here](https://github.com/marketplace?type=actions&query=github+pages)). Most of them require GH personal access token. Build process consists of several actions requires push
1. Generate HTML from Asciidoc and push to the `gh-pages` branch
2. Generate PDF and EPUB
3. Create issues in [Zally](https://github.com/zalando/zally)

GitHub pages support Jekyll static site generator. Perhaps with help of [jekyll-asciidoc](https://github.com/asciidoctor/jekyll-asciidoc) the first action can be solved. But the rest two still require token. 
One of the options is to create a [machine user](https://developer.github.com/v3/guides/managing-deploy-keys/#machine-users) to push to `gh-pages` and create issues in Zally.

**Comment by ePaul** [comment]
1. [deployment keys](https://developer.github.com/v3/guides/managing-deploy-keys/#deploy-keys) can have write access (checkbox when adding it to the settings)
2. [github actions](https://github.com/marketplace/actions/github-pages-action) can use deployment keys, personal tokens (which we want to avoid) or "github tokens", which we don't understand yet, but might be what we want to use.

**Comment by vadeg** [comment]
@ePaul how do you do releases currently? I have a bunch of different scripts but I am not how up to date they are.

**Comment by vadeg** [comment]
I tested GH action in a forked repo. Seems works fine. 
Pull request to check: vadeg/restful-api-guidelines#2
Link to API guidelines deployed by PR: https://vadeg.dev/restful-api-guidelines/#introduction. 

The question I have is when it should published? Publish on every merge to `master` branch? 
@tfrauenstein @tkrop @ePaul

**Comment by tkrop** [comment]
@vadeg yes, that is our strategy. Every merge to `master` should get immediately published.

**Comment by tkrop** [comment]
:+1:

**Comment by vadeg** [comment]
@tkrop I am still testing and need to add Zally rules creation.

**Comment by vadeg** [comment]
I have successfully managed to deploy guidelines using Github actions, but there is a problem with creating issues in other repository. According to the [documentation](https://docs.github.com/en/free-pro-team@latest/actions/reference/authentication-in-a-workflow#about-the-github_token-secret) about `GITHUB_TOKEN` its permissions are scoped to this repository
> The token's permissions are limited to the repository that contains your workflow.

But we need to create issues in another repository. I don't see any options except creating a Github app or bot user which would have permissions to create issues in another repo. 

Please share you thoughts If you have other ideas how to do this.

**Comment by ePaul** [comment]
@vadeg will ask in open-source guild whether there are any guidelines/best practices for bot user registration and/or handling.
