### ISSUE TITLE
Rule 112 example in conflict with 240

### ISSUE THREAD

**Issue by dneuhaeuser-zalando** [zalando/restful-api-guidelines#569]
The example for [rule 112](https://opensource.zalando.com/restful-api-guidelines/#112) is in conflict with rule [240](https://opensource.zalando.com/restful-api-guidelines/#240).

Additionally rule 240 is highly relevant for 112 and should therefore be referenced from 112.

**Comment by tkrop** [comment]
Thanks for reporting. Yes, we forgot to update this example when we added [rule 240](https://opensource.zalando.com/restful-api-guidelines/#240). We will update soon.
