### ISSUE TITLE
Improve guidance on path acceptance/normalization

### ISSUE THREAD

**Issue by tkrop** [zalando/restful-api-guidelines#571]
When looking on how services usually handle variations of paths, we can see big differences between different frameworks and service implementations, which is not reflected in the API specification but has a negative impact on predictability of the behavior of an API and the way how it is or can be used. The keyword here is request path normalization, i.e.

1. How are adjacent slashes in a request are handled, and
2. How are trailing and leading slashes in a request are handled.

While we already have a rule for trailing slashes [#136](https://opensource.zalando.com/restful-api-guidelines/#136), we are missing more guidance how adjacent slashes should be handled - and subsequently, whether empty path variable values should be permitted.

**Note:** leading slashes should not be an issue as they are taken care by the HTTP request specification.

To create a consistent behavior of APIs and allow for efficient high quality API monitoring we should improve our guidance on path acceptance/normalization as follows:

1. Services MUST normalize request paths before matching, i.e.
1.1. Multiple adjacent slashes do not change the semantic and must be treated as a single slash,
1.2. Trailing slashes do not change the semantic and must be treated as if absent.
2. Consequently, empty strings as path parameters are not allowed, as these would conflict with the normalization requirement.

**Comment by tfrauenstein** [comment]
thx. for the contribution. As discussed, this is important to avoid 'implementation traps' and to make API gateway features, like API monitoring working as expected and in a defined way.  

When we prepare a PR, I propose to more strictly separate API spec and impl aspects -- in the spec we simply should not allow it and in the impl we recommend to be robust and handle it semantically equivalent. 

Rule: API endpoint specs MUST use 'standard path urls' without trailing slash or double slash are not allowed in 'standard paths'. 

As a consequence, for instance, '/orders/' or '/orders/{id}' with optional or empty {id} are not allowed.

Service implementations SHOULD be robust against violations, and handle adjacent slashes as single slash and trailing slash as absent. Services should normalize request paths via deletion of trailing and adjacent slashes before API endpoint matching for request processing. Note, some (but not all) frameworks already do this out of the box. Examples? It is also the way, how Zalando's API gateway matches requests paths with API definition endpoint path patterns for API monitoring.

**Comment by ePaul** [comment]
Just as clarification:
* `/orders/{id}/items` with an empty id is not permitted
* `/orders//items` → `/orders/items` which is likely not a valid resource (404)

→ Update rule 228 + 136.
