### ISSUE TITLE
Adapt OpenAPI specification of application/problem+json

### ISSUE THREAD

**Issue by tkrop** [zalando/restful-api-guidelines#581]
Since #561 we have changed our advice how to use [application/problem+json](https://opensource.zalando.com/restful-api-guidelines/#176) (now the type is not supposed to be dereference-able), however, we have not adapted our [global specification](https://zalando.github.io/problem/schema.yaml).

Should we do compatible description update?

**Comment by ePaul** [comment]
Discussion in the meeting:

* copy the schema into our repository
* do the changes here
* we can also change it in the problem library's documentation via a PR

@tkrop volunteered.
