### ISSUE TITLE
Replace custom Media type with "application/json"

### ISSUE THREAD

**Issue by vadeg** [zalando/restful-api-guidelines#583]
The [MUST use media type versioning [114]](https://opensource.zalando.com/restful-api-guidelines/index.html#114) rule provides an example with a custom media type. Replace the custom media type with a standard media type as described in [Rule 172](https://opensource.zalando.com/restful-api-guidelines/index.html#172).

**Comment by tfrauenstein** [comment]
editorial bugfix -- with discouraging the usage of custom media types (Rule 172), we forgot to consistently change the example for media type versioning.

**Comment by vadeg** [comment]
As agreed I reverted custom media type and added some formatting. Please review again.
