### ISSUE TITLE
Add references to all common objects

### ISSUE THREAD

**Issue by vadeg** [zalando/restful-api-guidelines#584]
Guidelines has a `Common Data types` section where `Money` and `Address` objects defined. Then it has `Problem` object defined in `HTTP status codes and errors` section.

What do you think about making a section or appendix, e.g. _Common objects index_ with all references to all common objects used in the API guidelines?

**Comment by ePaul** [comment]
We agreed to add link in the start of the [common data types](https://opensource.zalando.com/restful-api-guidelines/#common-data-types) section to all the things defined elsewhere in the guidelines, including Problem.
