### ISSUE TITLE
Pagination links value format

### ISSUE THREAD

**Issue by vadeg** [zalando/restful-api-guidelines#587]
[Rule 161](https://opensource.zalando.com/restful-api-guidelines/index.html#161) defines pagination links, e.g. `self`, `prev`, `next` and etc and references to [Link relation fields](https://opensource.zalando.com/restful-api-guidelines/index.html#link-relation-fields) section. 

This section defines that fields `self`, `first`, `prev`, `next` and `last` should be _the link or cursor in a pagination response or object pointing to the same collection object or page._ The `ResponsePage` model definition below specifies that the format of those fields should be `uri` which does not match the description where it is allowed to use the cursor value instead of uri. 

It is allowed to use in link relation fields values what are not URIs? Should we update field descriptions and remove _cursor_ from there?

**Comment by tfrauenstein** [comment]
Good catch -- yes, there are inconsistencies in the sections about (cursor- vs. offset based) pagination. Let us discuss in next guild meeting how to handle it.

**Comment by ePaul** [comment]
From the meeting:

* Rule 160 contains a JSON structure definition which doesn't really belong here.
   * throw it out, or make it a non-YAML-formatted informal list, as it's implementation details
* The example of the `cursors` object doesn't really fit there either – can we move it somewhere else?
* Rule 161 has links to the link relation fields section of rule 174, which itself says "link or cursor".
  * the note for "GET with body" mentions a case where a simple link can't be used – the cursors object example could go here (or into a separate rule).

→ Best practices could have a full example on how this looks on API level, and how it's implemented.

@tkrop will make a proposal.
