### ISSUE TITLE
Describe custom media type format

### ISSUE THREAD

**Issue by vadeg** [zalando/restful-api-guidelines#588]
[Rule 114](file:///Users/vshaigorodsk/projects/github/zalando/restful-api-guidelines/output/index.html#114) does not provide any guidance about what should be the custom media type format. 

What do you think about including this information in the rule? As an example how it may look like

### Custom media type format
Custom media type format should follow the following pattern:

```
application/x.<custom-media-type>+json;version=<version>
```

* `custom-media-type` is a custom type name, e.g. `zalando.cart`
* `version` is a number, e.g. `2`

**Comment by tfrauenstein** [comment]
+1 -- let us substitute the examples in rule 114 with more specific standardisation as you proposed above
