### ISSUE TITLE
Allow `self` in Urls /customers/self

### ISSUE THREAD

**Issue by raiskumar** [zalando/restful-api-guidelines#595]
The [API guideline](https://opensource.zalando.com/restful-api-guidelines/#134) has a MUST rule to always use plural resources. In some cases, we use adjectives like `self` to refer to the customer whose `Authorization` token is passed in the request (header).

```
GET /customers/self/personal-details
```
Pluralizing `self` to comply with guidelines or using `{customer-number}` doesn't look good. The `self` version is more readable and many customer-facing services are already using it. 
Can we allow `self` for cases like above in `zally` and add it to API guidelines. 

Discussion thread: https://chat.google.com/room/AAAAAqZDJ28/WSrq8o4lHTE

**Comment by ePaul** [comment]
*(Discussion in the guild meeting.)*

That's what we have currently:

* `/customers` → all customers
* `/customers/{id}` → one specific customer with this id
* `/customers/4711` → the customer with id 4711
* `/customers/{id}/personal-details` → personal details of this one customer
* `/customers/4711/personal-details` → personal details of the customer with id 4711.

Use-case: we want to fetch details for one specific customer (identified by context information, e.g. the authorization token, not the URL). So we don't have an id to provide, and providing one would also not be supported.

Proposed in this issue (and already used by some teams):

* `/customers/self/personal-details`, which is currently not allowed by rule 143 (alternate const + param segments) + 134 (plural), and gives Zally-violations.

Viewed as sequence of sub-resources:

* `/customers` – all customers
* `/customers/self` – the customer identified by the current token
* `/customers/self/personal-details` the personal details of the customer identified by the current token

`self` is here a pseudo-identifier, it takes the syntactic position where in rule 143 an identifier would be expected.
Alternative proposed names: `me`, `from-token`, ...

Workaround which is currently (by letter) allowed by Rule 143:

* Have an endpoint `/customers/{self_enum}/personal-details`, and define `self_enum` as a path parameter with `enum: ["self"]` or similar.
* This doesn't give any violations
* fits to the previous implementation
* if used with code generations, you get an additional parameter here, which needs to be provided.
* It is confusing when reading the API.

**Decision**:
We want to extend rule 143 to allow the replacement of up to one occurrence of the `{resource-id}` parameter with the direct path component `/self/`.
