### ISSUE TITLE
Shell script to get new number no longer exists

### ISSUE THREAD

**Issue by msooszalando** [zalando/restful-api-guidelines#614]
The README links to this script:

https://github.com/zalando/restful-api-guidelines/blob/master/check_uniqueness_of_rule_ids.sh

But that's a 404. Can you please update?

Thanks,

Mate

**Comment by tkrop** [comment]
It is now part of the [Makefile](https://github.com/zalando/restful-api-guidelines/blob/master/Makefile#L19) and thereby also part of the standard build process.

**Comment by tkrop** [comment]
Oh, thanks found it in the CONTRIBUTING.adoc guidelines.

**Comment by msooszalando** [comment]
Can you please update the README so I can generate the number? Apparently my pull request here https://github.com/zalando/restful-api-guidelines/pull/613 is invalid due to this. Thanks!

**Comment by tkrop** [comment]
@msooszalando Have done it, but #616 is still pending.
