### ISSUE TITLE
Add guidence to use path templates in access logs

### ISSUE THREAD

**Issue by tkrop** [zalando/restful-api-guidelines#618]
To anticipate growing privacy constraints (see also #613) with respect to GDPR and sensitive information provided by resource identifiers, it makes sense to guide users to log path templates instead of full blow paths and queries unless they can make sure not to expose sensitive information during logging, tracing, and monitoring (see also #617). E.g. for access logging:

* `GET /orders/123456` => `GET /orders/{order-id}`, or
* `GET /orders?customer_id=7890` => `GET /orders?customer_id={}`

**Comment by msooszalando** [comment]
Thank you @tkrop , this together with #617 would be a powerful combination to address privacy concerns. Katalin and myself are keen to support, please let us know how we can help!

**Comment by vadeg** [comment]
@tkrop you mean instead or `GET /orders/12345?history` log `/orders/<order_id>`?

**Comment by msooszalando** [comment]
Note that at least from a privacy perspective the `?history` part can stay:

`GET /orders/<orderid>?history`

 Only the exact OrderID is the issue. It's fine to strip `?history` too, of course, but it's not necessary from a privacy perspective.

Just my 2 cents :)

**Comment by ePaul** [comment]
Waiting for the narrative (see discussion in #617) before we do any guideline changes here.
