### ISSUE TITLE
Clarity for Business Event vs. Data Change Events

### ISSUE THREAD

**Issue by tfrauenstein** [zalando/restful-api-guidelines#620]
Discussion on Tech Exchange channel has shown that there is some uncertainty about 
difference Business Events vs. Data Change Events, and guidance when to use it. 
Guidelines should be improved to make clearer statements here -- see
https://groups.google.com/a/zalando.de/g/tech-exchange/c/q76CGcAbOB0/m/9R4p1kBrBAAJ (Zalando-internal link)

**Comment by ePaul** [comment]
From the meeting:
@tfrauenstein will read the thread again and decide whether we need to actually change anything here.

**Comment by tkrop** [comment]
@tfrauenstein came to the conclusion that no improvement is needed here. Uncertainty should be low enough for readers.
