### ISSUE TITLE
External references to header resources are incorrect

### ISSUE THREAD

**Issue by tkrop** [zalando/restful-api-guidelines#638]
In https://github.com/zalando/restful-api-guidelines/pull/636#discussion_r576111657 @tfrauenstein exposed a bug in how we publish links to our models. They are published to `/` instead of `/models` resulting in a publication path of
```
https://opensource.zalando.com/restful-api-guidelines/request-headers-1.0.0.yaml#/X-Flow-ID
```
instead of
```
https://opensource.zalando.com/restful-api-guidelines/models/request-headers-1.0.0.yaml#/X-Flow-ID
```

While the first makes the path shorter, the second prevents mistakes by guideline writers and enables readers to browse the models on the web-server. However, we have already 3 other models published before. How do we want to fix this?

**Comment by ePaul** [comment]
**From the meeting:**

Agreed to change the actual deployment to include `/models/`.
Leave the old ones around (or a redirect) if we find they were used.
