### ISSUE TITLE
Examples for event names are incorrect

### ISSUE THREAD

**Issue by tkrop** [zalando/restful-api-guidelines#648]
The examples provided for event names in [rule 197](https://opensource.zalando.com/restful-api-guidelines/#197) are inconsistent with requirements formulated in [rule 213](https://opensource.zalando.com/restful-api-guidelines/#213) - the contain additional `.` (see https://github.com/zalando/restful-api-guidelines/blame/master/chapters/events.adoc#L182)

**Comment by ePaul** [comment]
In addition to changing the examples in rule 197, we should also add a bit of explanation in rule 213 what the purpose of functional names for events is (and the relation to the API with the same functional name).

e.g.:
* events contain information somehow related to the functional component of the same name. Does not have to be implemented (sent/consumed) by the same application/component/service.
* mention that future tooling will/might use the functional names to display event types belonging to a functional component
