### ISSUE TITLE
Change proprietary headers format in the hint for Rule 183

### ISSUE THREAD

**Issue by vadeg** [zalando/restful-api-guidelines#651]
Proprietary headers in [Rule 183](https://opensource.zalando.com/restful-api-guidelines/#183) doesn't match [Rule 132](https://opensource.zalando.com/restful-api-guidelines/#132).

**Comment by tfrauenstein** [comment]
I think we should Rule 132 to the proprietary header section and include 'X-' prefixing -- Common / standard headers are anyway not in our naming responsibility. What additional concrete mismatches you see?

**Comment by vadeg** [comment]
> Common / standard headers are anyway not in our naming responsibility

Then it could happen that we will see a lot of `location` instead of `Location` and `accept-encoding` instead of `Accept-Encoding` headers in APIs with arguments like "headers are case-insensitive anyways". 

Should we mention in the [Rule 133](https://opensource.zalando.com/restful-api-guidelines/#133) than _you should preserve naming convension for standard headers_?

**Comment by tfrauenstein** [comment]
yes -- see my proposal https://github.com/zalando/restful-api-guidelines/pull/653

**Comment by tkrop** [comment]
Replaced by #660.
