### ISSUE TITLE
Add example for embedding resources

### ISSUE THREAD

**Issue by whiskeysierra** [zalando/restful-api-guidelines#67]
The current [section ](http://zalando.github.io/restful-api-guidelines/hyper-media/Hypermedia.html#should-allow-optional-embedding-of-subresources) doesn't contain a useful example. See [HAL](http://stateless.co/hal_specification.html).

**Comment by ePaul** [comment]
Discussion in the meeting:

* move this to the performance section (beside the filtering)
* remove the content type rule
* actually add the example
* still to be discussed: use HAL syntax or ad-hoc

**Comment by whiskeysierra** [comment]
What's wrong with the content type?

**Comment by ePaul** [comment]
One problem is that the Accept header of the request doesn't fit to the Content-Type header of the response (which makes this actually very difficult to implement).
The other point is that we don't really want custom content types anymore.

**Comment by whiskeysierra** [comment]
> The other point is that we don't really want custom content types anymore.

Ok

**Comment by fmueller** [comment]
@whiskeysierra Except for versioning, of course - but we don't wanna have one of them neither
