### ISSUE TITLE
Restructuring the Guideline Sections

### ISSUE THREAD

**Issue by tfrauenstein** [zalando/restful-api-guidelines#674]
Today it is not easy to find the relevant rules, because we do not have a clear structuring concept.

We should separate API Endpoint related rules, from overall design related rules.
The former should be oriented on the basic syntactic categories (analog to OpenAPI structure), like Data Formats, Resource Paths and Query Parameters, JSON Payload, HTTP requests / responses, HTTP status codes and errors, Headers. The latter should start with the basics like Hypermedia, Performance and end with the more specific design aspects like Compatibility and Deprecation (proposal see [internal link](https://docs.google.com/document/d/1zOvQHVyPyinmT6JdYk1NWYBk-yBcaWMm98_n5hISA-o/edit)).

**Comment by ePaul** [comment]
@tfrauenstein and @vadeg : please coordinate whether to do this or #660 first, as there will be a lot of conflicts.

**Comment by tkrop** [comment]
I think this is done, so lets close this.
