### ISSUE TITLE
Update for OpenAPI 3.1

### ISSUE THREAD

**Issue by scop** [zalando/restful-api-guidelines#679]
Any plans to update the guidelines for OpenAPI 3.1?

For example, the standard data formats section https://opensource.zalando.com/restful-api-guidelines/#238 would receive some new formats per https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#data-types and https://datatracker.ietf.org/doc/html/draft-bhutton-json-schema-validation-00#section-7.3. I could submit a PR for this particular part if you think it would be useful and make it to the guidelines soon, let me know.

**Comment by scop** [comment]
> I could submit a PR for this particular part if you think it would be useful and make it to the guidelines soon, let me know.

#680 does that.

**Comment by tkrop** [comment]
@scop Thanks for taking the initiative here, and we very much appreciate it, but we currently waiting for the swagger library supporting OpenAPI 3.1 to align our tooling before adjusting the guidelines and prominently ask our users to migrate.

**Comment by tkrop** [comment]
@scop thanks for the contribution. We now support data-formats from OpenAPI 3.1 but we need to wait for updating the general support for OpenAPI 3.1 until our tooling is ready to accept this format. So for now we close the issue.
