### ISSUE TITLE
Suggestion: Mention kebab-case in rule 129 for consistance

### ISSUE THREAD

**Issue by Retro64** [zalando/restful-api-guidelines#688]
https://opensource.zalando.com/restful-api-guidelines/#129

```
MUST use lowercase separate words with hyphens for path segments [129]
```

"lowercase separate words with hyphens" is widely called `kebab-case`. I must admit I am not sure if this might offense someone. On the other hand camelCase might be seen offensive as well. At least it would better fit the other rules, using the name and not the description, how the case looks like (like rule [130](https://opensource.zalando.com/restful-api-guidelines/#130)).

**Comment by tfrauenstein** [comment]
thx. for the proposal. Agreed see https://github.com/zalando/restful-api-guidelines/pull/690
