### ISSUE TITLE
Add LICENSE and MAINTAINERS files

### ISSUE THREAD

**Issue by hjacobs** [zalando/restful-api-guidelines#7]
Please add `LICENSE` and `MAINTAINERS` files as described in our "How To Open Source" guide: https://github.com/zalando/zalando-howto-open-source

**Comment by hjacobs** [comment]
And also add a `.catwatch.yaml` file to have a proper title on our Open Source page, example: https://github.com/zalando/zmon-controller/blob/master/.catwatch.yaml

**Comment by fmueller** [comment]
Under which license do we maintain the guidlines? Creative commons?

**Comment by ePaul** [comment]
I think CC-BY is suitable here (we don't need share-alike, do we?). It seems equivalent to the MIT license for software. (You can follow the examples of the "howto open-source" repository there.)

I volunteer to be one of the names in the MAINTAINERS file.

**Comment by fmueller** [comment]
For MAINTAINERS file I'll add all from the API guild.

CC-BY seems to do the job.

**Comment by fmueller** [comment]
Solved.
