### ISSUE TITLE
Appendix is not rendered properly

### ISSUE THREAD

**Issue by jvyang** [zalando/restful-api-guidelines#703]
The `References` section is not being rendered properly. See screenshots below:

Web Version:
![web version](https://user-images.githubusercontent.com/4486052/145883020-3c653fd2-fe44-45ed-99b3-01e7371129c5.png)

PDF version:
![pdf version](https://user-images.githubusercontent.com/4486052/145883019-d3fa1a26-3b1a-435d-9aa4-669cffad6144.png)

**Comment by ePaul** [comment]
Thanks for opening this issue. I'm not quite sure what caused this, but adding an empty line before the part header seemed to have helped (see PR #710).
