### ISSUE TITLE
Unclear scope of recommendation against total count remark

### ISSUE THREAD

**Issue by scop** [zalando/restful-api-guidelines#731]
https://github.com/zalando/restful-api-guidelines/blob/4d7b9d0ffd2ff65bd0ad5252c367aa49beac4dae/chapters/pagination.adoc#should-use-pagination-links-where-applicable

The "You should avoid providing a total count..." remark in that section can arguably be thought to apply to the whole concept of pagination instead of just the "SHOULD use pagination links where applicable" one where it is structurally located.

Would it be possible to clarify the intent somehow? For example, by moving it to the "MUST support pagination" section it would be clearer that it applies to all of the chapter's alternative pagination approaches, or by amending the remark with a few words like "You should avoid providing a total count along with pagination links unless there is a clear need to do so." would make it clear that it applies to this particular section only.

**Comment by ePaul** [comment]
_(This is about rule [161](https://opensource.zalando.com/restful-api-guidelines/#161).)_

I agree, the remark doesn't really fit there. I see these options:

* move it to [MUST support pagination](https://opensource.zalando.com/restful-api-guidelines/#159)
* move it to [SHOULD use pagination response page object](https://opensource.zalando.com/restful-api-guidelines/#248)
* create a new rule – but that seems like a too detailed rule.

**Comment by scop** [comment]
Thanks for looking into this! However I feel there is a bit of a disconnect between the resolution in #788 and the note above about how this would be brought forward: https://github.com/zalando/restful-api-guidelines/issues/731#issuecomment-1155168458

Just to understand, was there some further discussion/decision that's not recorded here?

While #788 does improve the guidance, I feel the original point of this issue about the scoping or placement of the guidance still persists. (Just based on reading the diffs, haven't looked at the whole doc picture at that change.)
