### ISSUE TITLE
How to get API key activated again

### ISSUE THREAD

**Issue by ButcherFromHell** [zalando/restful-api-guidelines#754]
Hello,

our e-commerce was using API but it looks like our key is not working anymore. How to activate it again? Is there a form for this? 
I have contacted the zalando support via emial and after two weeks got response but with no details on that subject.

Any help would be great. Thank you.

**Comment by ePaul** [comment]
Hi! This repository is about the Restful API guidelines, not about any specific API. If you tell us which API you were using, we might point you to the right contact, but currently there is not enough information to help you.
