### ISSUE TITLE
Make rule 111 consistent to 109

### ISSUE THREAD

**Issue by ePaul** [zalando/restful-api-guidelines#765]
* [Guideline 109](https://opensource.zalando.com/restful-api-guidelines/#109) describes a conservative approach to API design – servers are supposed to reject unknown properties in inputs.
* [Guideline 111](https://opensource.zalando.com/restful-api-guidelines/#111) says that "servers _may_ reject requests whose entities contain undefined fields".

This sentence (and the following one) should be changed to match the approach in rule 109 (and also link to it).

**Comment by pablosaraiva** [comment]
> * [Guideline 109](https://opensource.zalando.com/restful-api-guidelines/#109) describes a conservative approach to API design – servers are supposed to reject unknown properties in inputs.
> * [Guideline 111](https://opensource.zalando.com/restful-api-guidelines/#109) says that "servers _may_ reject requests whose entities contain undefined fields".
> 
> This sentence (and the following one) should be changed to match the approach in rule 109 (and also link to it).

Both links point to guideline #109.

Here is suggested edit to the issue:

[Guideline 111](https://opensource.zalando.com/restful-api-guidelines/#111)

**Comment by ktsypkina** [comment]
raised a PR with suggested changes, please have a look!
https://github.com/zalando/restful-api-guidelines/pull/793
