### ISSUE TITLE
Capture well-known field names in JSON Guidelines

### ISSUE THREAD

**Issue by dehora** [zalando/restful-api-guidelines#79]
There are some data fields that come up again and again and it's maybe worth writing them down -

 - `id`: the identity of the object, often plugged into a url to be dereferenced. 
 - `created_at`: when the object was created as a date. 
 - `updated_at`: when the object was updated as a date
 - `type`: the kind of thing this object is

The `id` field name is probably easy to get consensus around. The date fields are nearly as common but you could argue for different name conventions (eg `created`, `created_date` or `created_timestamp`). The `type` field is arguably not as ubiquitous as the other three, might not be needed as much given the use of OpenAPI, but it is common in public APIs.

Somewhat related is https://github.com/zalando/restful-api-guidelines/issues/62, which talks about the `id` field. Also as a datapoint the [Google JSON Styleguide](https://google.github.io/styleguide/jsoncstyleguide.xml) gives a lot of space over to reserved property names.

**Comment by whiskeysierra** [comment]
> eg created, created_date or created_timestamp

`last_modified` or `last_modified_at` are also common names for this.

**Comment by ePaul** [comment]
Just as a datapoint: We (several teams in Zalando Wholesale, basically the previous Purchasing team) are often using the name `id` for internal database identifiers (which are not exposed externally, and thus don't appear in any API), and then something else like `number` or `code` for the functional identifiers (which appear in the API, and might also be shown to human users).

For the timestamps, we use just `created` and `last_modified` (together with `created_by` and `last_modified_by`).

**Comment by whiskeysierra** [comment]
> For the timestamps, we use just created and last_modified (together with created_by and last_modified_by).

My team uses `created_at` and `modified_at`. We explicitly decided to **not** support the `created_by`/`modified_by` fields, since it's basically impossible (at least for us) to define what goes in there (I've seen Flow-IDs, IPs and E-Mail addresses, sometimes combinations).

**Comment by whiskeysierra** [comment]
> We explicitly decided

We = my team (if that wasn't clear from the context).

**Comment by hjacobs** [comment]
> For the timestamps, we use just created and last_modified (together with created_by and last_modified_by).

I think that's what most of Zalando systems use traditionally (including all STUPS services), so I vote for that.

**Comment by fmueller** [comment]
I don't see the advantage in providing such a guideline. What would be the intention @dehora @hjacobs @whiskeysierra @ePaul?

**Comment by ePaul** [comment]
I guess the intention is as most of the guidelines: to make Zalando's API's look more similar ("have a common look and feel", from the introduction).

**Comment by tkrop** [comment]
I would not provide such detailed guidelines. We should try to focus our guidelines to the aspects that are most important. I have the feeling the guidelines are already starting to be to detailed for joe average.

**Comment by fmueller** [comment]
After discussing this with several devs, I think we should add this to the guidelines for the sake of 'same look-and-feel' of our APIs.

@dehora Would you like to prepare a PR for JSON sections?
