### ISSUE TITLE
Clarify when to use `date` vs `datetime`

### ISSUE THREAD

**Issue by SmilyOrg** [zalando/restful-api-guidelines#797]
Adjust rule 169 to consider the following points (up for discussion)

- `date` should be used for cases where the day itself matters, e.g. holidays, document dates, ETAs (shipping notices), birthdays. Usually this means the "local day", i.e. the time period midnight to midnight in the local time zone.
- `datetime` should be used to indicate instants/moments in time, i.e. a form was submitted at 2024-02-16T16:19:00Z, it may also be better to implement filtering by dates (e.g. with date picker) as `datetime` to make the client decide on whether a date is implicit or explicit and which timezone it refers to (unless the filtering would filter to events that happened on a certain day in every timezone,)

**Comment by ePaul** [comment]
Done with #808.
