### ISSUE TITLE
{{ book.must }}: artefact from some templating engine?

### ISSUE THREAD

**Issue by etorreborre** [zalando/restful-api-guidelines#8]
In [Data formats](https://github.com/zalando/restful-api-guidelines/blob/master/data-formats/DataFormats.md) there is `{{ book.must }}`. Should it be displayed as `MUST`?

**Comment by ePaul** [comment]
In the [rendered version](http://zalando.github.io/restful-api-guidelines/data-formats/DataFormats.html) it is displayed in red. The source code have this `{{ book.must }}` instead, which is then processed by the rendering engine. (Same for `should` and `could`.)

**Comment by fmueller** [comment]
Because we're are using Gitbook for rendering the markdown files, reading them is propbably not convenient.

**Comment by ePaul** [comment]
Closing this. #9 is also about the question of reading directly on Github.
