### ISSUE TITLE
Grammar and syntax edits for the style guide

### ISSUE THREAD

**Issue by Kenneth-Stanfield** [zalando/restful-api-guidelines#813]
I've been carefully reviewing the **Zalando RESTful API Guidelines** document for a project I'm working on. As a native English speaker, I've noticed a number of sentences and phrases in the Zalando document with incorrect grammar or syntax.

I'd like to correct these small errors by making a PR consisting of extremely targeted edits. My intention is NOT to re-write sentences. I only want to correct grammar and syntax mistakes in the simplest way possible.

Before I undertake this work with a feature branch and a PR, I'd like one of the owners of this repo to weigh in with an opinion about whether this work would be a worthwhile expenditure of my time.

**Comment by tfrauenstein** [comment]
Hi Kenneth, great, we highly appreciate a PR for improving the language. (The authors are no native English speakers.)

**Comment by tkrop** [comment]
Hi @Kenneth-Stanfield can only confirm what @tfrauenstein has added. We will gladly support you to get any improvement to our strange grammar merged.

**Comment by Kenneth-Stanfield** [comment]
Thank you for the quick responses, @tkrop & @tfrauenstein 

I will create a feature branch for making simple edits and corrections.

We'll need to discuss some sentences and phrases before I can suggest improvements. There are two ways to manage this:

- via in-line comments in the `PR`
- via comments in this `Issue` discussion

I look forward to collaborating with you on this project. Overall, I think the authors of this widely-used document from Zalando did great work. I hope I can add some value to the mix.

**Comment by tfrauenstein** [comment]
@Kenneth-Stanfield great. It is editorial work where we prefer in-line comments in the PR. Looking forward to your PR, thx.

**Comment by Kenneth-Stanfield** [comment]
I created a local branch (with no changes) and tried to make an initial push to the remote. But I'm getting a 403 error inside SourceTree, my visual front-end to Git.

> remote: Permission to zalando/restful-api-guidelines.git denied to Kenneth-Stanfield.
fatal: unable to access 'https://github.com/zalando/restful-api-guidelines.git/': The requested URL returned error: 403

The branch name I want is `kstanfield-grammar`

Do I need permission to push to a remote feature branch?

**Comment by ePaul** [comment]
Hi, for making a pull request to a repository where you don't have write access, the usual approach is to [fork the repository](https://github.com/zalando/restful-api-guidelines/fork), and then push a branch to your own fork. Github will then automatically suggest to create a PR to the original repository.

(As this is a corporately owned repository, we generally won't give direct write access to non-employees.)

**Comment by Kenneth-Stanfield** [comment]
Thanks for that information, ePaul. I'll fork of the repo as suggested.

I have a follow-up question. I'd like to get some initial feedback from the community (for changes to a single file) before moving forward. If I work inside my own fork, making regular checkins, will it be easy for folks on this thread to review my in-progress work?

Thanks

**Comment by ePaul** [comment]
> I have a follow-up question. I'd like to get some initial feedback from the community (for changes to a single file) before moving forward. If I work inside my own fork, making regular checkins, will it be easy for folks on this thread to review my in-progress work?

Just open a (possibly draft) PR from your branch (and link it to this issue).
We can either merge the changes to the one file when fine (and you then continue with the others and open a new one), or you can just continue working on the branch (which will show up in the PR) and we merge it at the end, as you prefer.

**Comment by ePaul** [comment]
Hi, are you still working on this topic, or can we close the issue?

(Even if closed, you are still welcome to open a PR with improvements.)

**Comment by Kenneth-Stanfield** [comment]
I'm still working on this, but please close the ticket for housekeeping. The changes are more extensive than expected. I'll open a new PR when the draft is ready for review.
