### ISSUE TITLE
Which status code to use for semantic error on GET parameters

### ISSUE THREAD

**Issue by kakawait** [zalando/restful-api-guidelines#82]
On [Client Side Errors](http://zalando.github.io/restful-api-guidelines/http/Http.html#client-side-error-codes) you define that `422 Unprocessable Entity` should be use for *semantic errors*. Nevertheless you are limiting to `POST`, `PUT`, `DELETE`, `PATCH` *HTTP verbs*.

I understand the limitation because *request entity* is about *Headers* + *body* thus there is no sense for `GET` *HTTP verb*.

However `GET` can be requested with parameters (here *query string parameter*) that we could validate like:

```
/feed?url=XXX
```

Where `url=XXX` should be respect following validation:

1. Present, if not `400 Bad Request` because is not semantic error
2. To be a valid URL (so not empty) (`@URL`)
3. To be a valid Feed URL

For *2.* I really think is semantic error if user does not pass correct URL. Moreover there is also a edge case for *post-validation* (it may out-scope, *2.* is the main goal of this issue), because it is not possible to determine validity without fetching it.

To conclude which status code should I return for *2.* (and if you have advice for *3.*)?

- `422 Unprocessable Entity` seems to not appropriate because of *Unprocessable Entity*. There is no *entity* on `GET` request
- `400 Bad Request` seems to be the least bad?
- `404 Not Found` can be a great alternative and most *RFC respectful* but can deceive user.

--- 

Upstream discussion: https://github.com/zalando/problem-spring-web/issues/49

**Comment by tkrop** [comment]
I would still return 400 for 2. and 3. as it is detectable in an initial validation process that the url has not the required characteristics, and the client should have known this in advance. The subtle difference between semantic and synthax does not really add additional value for the client here.

**Comment by fmueller** [comment]
Decided in last API guild meeting: we propose 400 for all cases.

**Comment by kakawait** [comment]
@fmueller Ok I think is best solution!

**Comment by kakawait** [comment]
@fmueller should we close issue?

**Comment by whiskeysierra** [comment]
I'd leave this open for now, because I feel like we need to adjust the guidelines.

**Comment by fmueller** [comment]
Yes @kakawait Thank you for your input. Based on this we realized that for our setup 422 would be over-designed and that we should stick to 400. We need to adjust the guidelines on this and make this clear.
