### ISSUE TITLE
Guidance on custom media types needs to be reworded

### ISSUE THREAD

**Issue by ePaul** [zalando/restful-api-guidelines#84]
http://zalando.github.io/restful-api-guidelines/data-formats/DataFormats.html#could-use-applicationspecific-content-types

**Comment by ePaul** [comment]
@fmueller do you remember what this was about? If so, feel free to reopen.

**Comment by fmueller** [comment]
What needs to be done:
- remove all custom media types in examples
- explain that we do not see any big value-add in custom media types
- only allow them for versioning (which is not wanted neither)
