### ISSUE TITLE
Explain difference between POST and PUT for resource creation

### ISSUE THREAD

**Issue by ePaul** [zalando/restful-api-guidelines#88]
Several times during review I noted that API designers often think "Create = POST, Update = PUT".

The actual meaning is more like this:

* PUT means »*please put the enclosed representation at the resource mentioned by the URL*«, which will either create that resource (if it didn't exist before) or replace the resource currently there (if there was one). This should be used for creation when the client decides the URI where the resource will live.
   It has the additional benefit that it is idempotent, i.e. you can send the request twice without having two resources created (because the second one will simply update), and thus are resilient against connection failures.

* POST means (beyond other meanings like "fallback if no other method fits") »*please add the enclosed representation as a new element of the collection resource identified by the URL*«. The server will "invent" a new URI and put the new resource there. This should be used for creation when the server is deciding the resource identifier.

We should adapt the wording in the [HTTP](http://zalando.github.io/restful-api-guidelines/http/Http.html) section to make this clearer.

**Comment by dehora** [comment]
:+1: 

- I'd love to see the Location/Content-Location headers covered as well around 201, as they vary for PUT/POST, and we currently lump the behaviours in together.

- I think for POST we can say it's idiomatically used for create via a collection resource like you point out (this is absolutely the case in public APIs and is captured in older standards like AtomPub). POST is mostly problematic when some other uniform method does fit, so you need to think it through (an example of needs thinking through is using POST as a means to send complex queries to a server as a surrogate for a GET).

- Personally I find PUT problematic to the extent I'm always not sure it's better for API design than POST. Idempotency in HTTP tends to be a confusing subject. PUT to update/create can have real issues in the absence of some kind of namespacing/tenacy model that provides an application level sandbox to stop people trashing each other's data (which is to say, I'm nervous seeing PUT used against flat namespaces for public systems, and it makes APIs hard to externalise when the trust model changes). PUT means "replace" which is arguably not that common a usecase in modern APIs that are manipulating structured data (it's awesome where it fits, such as storage/media style systems). It's also common to have different semantics for creating a new thing versus updating an existing thing such that you really want to know which is which. It's not that well known that a resource owner is supposed to signal a different response for first time versus already existing with PUT, this could be worth highlighting as folks tend to get caught up in the idempotency thing.

**Comment by mostlymagic** [comment]
@dehora I strongly agree to the case you make for namespacing

**Comment by fmueller** [comment]
We've decided in guild meeting to explain in more detail what POST and PUT operations are, how these http verbs can be used and what the trade-offs are to give more guidance for teams.
