### ISSUE TITLE
Table markup is not displaying properly

### ISSUE THREAD

**Issue by etorreborre** [zalando/restful-api-guidelines#9]
[There](https://github.com/zalando/restful-api-guidelines/blob/master/http/Http.md#success-codes) for example.

**Comment by fmueller** [comment]
Please use the rendered version: http://zalando.github.io/restful-api-guidelines/http/Http.html In rendered version it looks good.

**Comment by ePaul** [comment]
Maybe we can somehow make it clear in the README that the `.md` files in the repository are not meant to be read directly in Github, but only after formatting?

But the README.md itself is also the introduction section of the book, so this would need some rearranging.

Or can we tell Github to use a different formatting engine?

**Comment by fmueller** [comment]
What about separating introduction section and Readme completely?

**Comment by etorreborre** [comment]
Get it, thanks. Maybe a link to the rendered doc at the beginning of the README will help.

**Comment by ePaul** [comment]
There is one, it is just not that prominent above the image.

**Comment by tfrauenstein** [comment]
Good proposal -- yes we should do it like this.
More open source standard conform with info about scope, usage, license, ... and links to html and pdf versions.

**Comment by fmueller** [comment]
Solved.
