### ISSUE TITLE
Give more guidance on generation of flowId header

### ISSUE THREAD

**Issue by fmueller** [zalando/restful-api-guidelines#92]
From my point of view we should give a default implementation for generating the FlowId Header. Just a UUID in Java, for instance. What do you think?

**Comment by ePaul** [comment]
Hmm, switch "default" to "example".

Also, I'm not sure if using code (other than JSON/YAML) in the guidelines fits. Better link to libraries made to implement this (like https://github.com/zalando/tracer).

**Comment by whiskeysierra** [comment]
> Just a UUID

In theory that should work, but I'm not sure if we have some components that expect the Flow-ID in a specific format.

The algorithm looks like [this](https://github.com/zalando/tracer/blob/master/tracer-core/src/main/java/org/zalando/tracer/FlowIDGenerator.java):

```java
final UUID uuid = UUID.randomUUID();
final byte[] high = toByteArray(uuid.getMostSignificantBits());
final byte[] low = toByteArray(uuid.getLeastSignificantBits());
final byte[] bytes = concat(high, low);

return "R" + encoder.encodeToString(bytes).replaceAll("=", "").substring(1);
```

But I agree with @ePaul, we shouldn't include code directly.

**Comment by fmueller** [comment]
Ok, right. I was just thinking about making it more clear for readers because we were approached several times during last weeks what FlowId is and how it should be handled or generated.

**Comment by ePaul** [comment]
@whiskeysierra I think we should make it a priority to find out which legacy systems actually depend on this format, and then push to change them to have a more flexible view, allowing to use a UUID (or also some user-formatted strings) directly. (I'm thinking about Exception-Monitor, EventLog, etc. Hopefully the more modern tools like Nakadi and AppDynamics already support other formats.)

In manual tests I often use something like `PAUL-TEST-1` as flow-id for my soap requests, I didn't yet see problems with this, though I also didn't try to trace this through several systems.

(I guess we should exclude whitespace, at least, for common log formats.)

**Comment by whiskeysierra** [comment]
> In manual tests I often use something like PAUL-TEST-1 as flow-id for my soap requests, I didn't yet see problems with this, though I also didn't try to trace this through several systems, just looked them up in the logfile.

That sounds promising.

My fear are systems that persist them with a specific length, e.g. SAP:

**Comment by tkrop** [comment]
I have the feeling this is more a platform than an API aspect. FlowIDs, BusinessProcess IDs etc. are a cross cutting concern that goes far beyond what should be defined in an API. May be we should not define such thing in this guidelines but in a platform guideline. I'm not even sure whether it should be required to be defined explicitly in the API, as this would ad unnecessary noise for reading/reviewing APIs.

**Comment by ePaul** [comment]
We just talked about this in the meeting.

We want to define this:

* A flow ID uniquely identifies a flow through the system.
* It should be a string consisting of just printable ASCII characters (i.e. without whitespace).
* If a legacy subsystem can only work with flow-ids of a specific format, it needs to define this in its API, or make its own ones.

**Comment by whiskeysierra** [comment]
The eventlog will truncate flow ids to 22 characters, as of today.

**Comment by ePaul** [comment]
From today's meeting, mention, that:

* like every input value the flow ID needs to be verified by services before using it for logging.

**Comment by fmueller** [comment]
@ePaul Can you please again explain why you would validate flow id before logging? Imho this would make services more brittle.

**Comment by ePaul** [comment]
@fmueller This is not meant to verify that it fits to a specific format, but have a sensible maximum length (so e.g. now allow megabyte strings) and possibly throw out or escape characters/bytes which throw off your log parsing (line breaks, tabs, spaces, NULL), etc. Just basic validation as for every input you take.

**Comment by fmueller** [comment]
Ok, I agree with this point and will add it to the PR.
